### ISSUE TITLE
Markdown rich diff tooltip appears underneath diff settings bar

### ISSUE THREAD

**Issue by dcwither** [sindresorhus/refined-github#1295] opened 2018-05-03 03:05 UTC
![image](https://user-images.githubusercontent.com/1641405/39558487-d9ea079a-4e43-11e8-9a88-11fca0085f2c.png)

Steps to repro:

1. Open a diff with markdown changes (e.g. https://github.com/dcwither/react-editable-decorator/pull/4/files?utf8=%E2%9C%93&diff=unified&w=1&short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)
2. Scroll down until the button is sticking to the top of the screen
3. Hover over the button

Expected Behavior:

The tooltip either appears below the button or on top of the toolbar

Actual Behavior:

The tooltip appears underneath the PR toolbar.

System Info:
OS X 10.13.4
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by notlmn** [comment] 2018-05-03 07:03
This is an known issue from #689, because of the sticky behavior of header items of each file and the main diff header.

The solutions were to just hide tooltips (#799, merged), or use JS to change tooltip direction (https://github.com/sindresorhus/refined-github/issues/689#issuecomment-336694139).

Maybe we should change tooltip direction for icon-only buttons!? @bfred-it?

**Comment by bfred-it** [comment] 2018-05-04 09:38
Duplicate of #1212 

This was fixed by #1234 but something might have changed. PR welcome to hide it again.

**Comment by notlmn** [comment] 2018-05-05 09:52
@bfred-it This is not a duplicate, #1234 only tried to remove tooltips on "Open file in GitHub desktop" and "Edit file" buttons, which still works. This issue is for tooltips on Markdown diff buttons ([sample diff](https://github.com/sindresorhus/refined-github/pull/1140/files#diff-cc4aac3e9be04e0413c9520f223b493c)).

These buttons have the following `aria-label`s, and either the tooltips need to be hidden (not preferred) or their direction needs to be changed (needs JS).

``` css
[aria-label="Display the source diff"]
[aria-label="Display the rich diff"]
```

**Comment by bfred-it** [comment] 2018-05-05 14:04
This #1234:

![091545b3-8ff8-476c-8236-dfb917364552](https://user-images.githubusercontent.com/1402241/39664060-2b562a52-5086-11e8-90da-28219fdd057e.jpeg)

Hiding all of them was the intent, perhaps it only failed to do so. Either way they should be hidden to solve the current issue.

**Comment by bfred-it** [comment] 2018-05-05 14:07
You’re right. These icons aren’t not completely clear though, so… maybe we have to move their tooltip downwards via js, perhaps as part of a new “sticky file header.js” feature since it wouldn’t stand on its own

**Comment by notlmn** [comment] 2018-05-05 14:54
Overriding position with CSS would be a better idea than JS. Also "Left/Right" would be a better position than "Down", as most of the time your cursor would be hiding the tooltip.

**Comment by bfred-it** [comment] 2018-05-05 15:50
> most of the time your cursor would be hiding the tooltip

It's far enough that that doesn't really happen. Even hovering the last pixel only covers a pixel of the text:

![a](https://user-images.githubusercontent.com/1402241/39664990-26fe8e4a-5095-11e8-877b-954cd50a6502.gif)

**Comment by notlmn** [comment] 2018-05-05 19:32
> It's far enough that it doesn't really happen.

Not on every OS!

![cursor](https://user-images.githubusercontent.com/37769974/39666903-c2916606-50c8-11e8-9250-eeec5a229d15.gif)

------------

And it's too annoying to have anything popup below your cursor anyway (takes time to interpret what is happening).

**Comment by mngatewood** [comment] 2018-05-07 21:08
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by yakov116** [comment] 2018-05-07 21:11
@dcwither Go for it!

**Comment by mngatewood** [comment] 2018-05-08 20:42
Thanks! PR #1308 addresses this issue.

**Closed** 2018-11-06 15:43 UTC
Labels: bug, good first issue, help wanted
