### ISSUE TITLE
i see double file icons with the github file icons plugin

### ISSUE THREAD

**Issue by muescha** [sindresorhus/refined-github#2045] opened 2019-05-16 18:41 UTC
when:

- i have installed the octotree icon set with the plugin https://github.com/lvarayut/github-file-icons
- i have new installed refined-github plugin

what i see:
- 2 icons per file

what i expected:
- the github-file-icons

Screenshot:

![Bildschirmfoto 2019-05-16 um 20 40 15](https://user-images.githubusercontent.com/184316/57878684-ddf7d400-781a-11e9-92a4-1e4ecce91bd8.png)

PS: the left side bar is the octotree plugin.

**Comment by bfred-it** [comment] 2019-05-16 18:57
Duplicate of https://github.com/sindresorhus/refined-github/issues/1993

**Closed by bfred-it** 2019-05-16 18:57 UTC
Labels: bug
