### ISSUE TITLE
Milestone does not appear in PR sidebar anymore

### ISSUE THREAD

**Issue by jeherve** [sindresorhus/refined-github#2942] opened 2020-03-26 16:53 UTC
This happens when Refined GitHub is active, on all Pull Request pages. 

1. In the discussion sidebar, click on the cogwheel next to the Milestone Heading
2. Add a Milestone to your PR. 
3. Observe the event being logged in the PR body:
![image](https://user-images.githubusercontent.com/426388/77673462-7f4acd00-6f8a-11ea-88b7-be8d1d9f0a8d.png)
4. The sidebar, however, does not display the milestone:
![image](https://user-images.githubusercontent.com/426388/77673512-8eca1600-6f8a-11ea-9133-40c173d66e7b.png)
5. Clicking on the cogwheel shows that we have in fact a milestone:
![image](https://user-images.githubusercontent.com/426388/77673573-a0132280-6f8a-11ea-95d5-cfc7f1179d6d.png)

Here is an example where I saw this happening:
https://github.com/Automattic/jetpack/pull/15103

**Comment by yakov116** [comment] 2020-03-26 17:02
Duplicate of #2924

The fix was not pushed yet

**Comment by fregante** [comment] 2020-03-26 17:04
> The fix was not released yet


Releasing today ✅

**Closed by fregante** 2020-03-26 17:04 UTC
Labels: bug

**Comment by fregante** [comment] 2020-03-26 17:14
20.3.26 released with this fix. Firefox has it, Chrome will take a few days

**Comment by jeherve** [comment] 2020-03-26 18:15
Thank you!

**Comment by dwijnand** [comment] 2020-03-27 19:24
Note you can get a fixed version from the CI builds, see https://github.com/sindresorhus/refined-github/issues/2796#issuecomment-587428669 but look for a more recent build.
