### ISSUE TITLE
Contribution graph keeps switching back to 2018

### ISSUE THREAD

**Issue by darahak** [sindresorhus/refined-github#1690] opened 2019-01-02 09:56 UTC
Hi,

I'm not sure this was already reported, at least I haven't found anything in the existing issues.

I just noticed when I visit a profile, their contribution graph keeps switching back to last year and hides any contributions from the new year.

This was on Chrome and I don't reproduce the issue if I disable the extension.

Here's an example with my profile where I reload it by clicking on the `Overview` link.

[![](https://j.gifs.com/xvZAVE.gif)]()

**Comment by bfred-it** [comment] 2019-01-02 10:22
Essentially a duplicate of https://github.com/sindresorhus/refined-github/issues/1627

The problem is this feature https://github.com/sindresorhus/refined-github/blob/master/source/features/infinite-scroll.js#L60

I'll continue the discussion there

**Closed by bfred-it** 2019-01-02 10:22 UTC

**Comment by notlmn** [comment] 2019-01-02 12:02
Oh, my!

2019 starts bugging already and sends you back to 2018!

🤣

**Comment by bfred-it** [comment] 2019-01-07 03:45
Fixes by #1698
