### ISSUE TITLE
Add configurability to the extension

### ISSUE THREAD

**Issue by kumarharsh** [sindresorhus/refined-github#515] opened 2017-06-22 06:46 UTC
I couldn't find an issue regarding this, but wanted to discuss this: would it be possible to add some sort of configuration to the extension to switch certain features on/off? I can create a new issue regarding this if none exists yet.

For example, I have found out that I don't really like the 'real name' being displayed against the username.
 😆 and would like to switch it off. But right now, I have to disable the whole extension for this.

**Comment by bfred-it** [comment] 2017-06-22 07:08
Duplicate of #193 

You can open specific issue about the options you'd like. While they're unlikely to get added, as mentioned in the readme, perhaps there are solutions.

In your case, you can probably just hide the name with `.comment-full-name {display: none}` in a userstyle.

**Closed by bfred-it** 2017-06-22 07:08 UTC
