### ISSUE TITLE
Incompatible with Firefox-ESR 78.14.0

### ISSUE THREAD

**Issue by nerdCopter** [sindresorhus/refined-github#4831] opened 2021-09-29 13:40 UTC
### What I don't like

Incompatible with ESR ☹️

**Comment by fregante** [comment] 2021-09-29 14:33
Duplicate of https://github.com/sindresorhus/refined-github/issues/4561

**Closed by fregante** 2021-09-29 14:33 UTC
Labels: change request

**Comment by busches** [comment] 2021-09-29 15:00
ESR 91.2 comes out next week!

**Comment by nerdCopter** [comment] 2021-09-29 15:11
Now for Debian 11 to actually use it :P :wink:
