### ISSUE TITLE
Idea: Have an obvious badge for "draft" pr's in the list of open pr's

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#2531] opened 2019-11-11 23:44 UTC
The grey colored PR logo and tiny *Draft* text in the subtitle are just not very visible and eye catching!

![draft](https://user-images.githubusercontent.com/9874850/68629841-927e6400-04e5-11ea-830d-b6c454fb7f65.png)

Addon version: 19.11.10

**Comment by fregante** [comment] 2019-11-12 03:47
Indeed! We agree

**Comment by fregante** [comment] 2019-11-12 03:48
Duplicate of https://github.com/sindresorhus/refined-github/issues/2450

**Closed by fregante** 2019-11-12 03:48 UTC
Labels: enhancement, under discussion

**Comment by tooomm** [comment] 2019-11-14 01:25
Thanks for linking the other request! I couldn't find it
