### ISSUE TITLE
Edit Pen does not Appear for New Comments

### ISSUE THREAD

**Issue by Modelmat** [sindresorhus/refined-github#2622] opened 2019-12-12 06:47 UTC
When you add a new comment, the edit pen does not appear. It only appears after you refresh the page.
Before refreshing:
![image](https://user-images.githubusercontent.com/25718989/70689032-46525980-1d07-11ea-87a9-27fce9f9dbdd.png)
After refreshing:
![image](https://user-images.githubusercontent.com/25718989/70689069-5cf8b080-1d07-11ea-8cf3-24e4fe2d21e4.png)

**Comment by fregante** [comment] 2019-12-12 07:23
Test

**Comment by fregante** [comment] 2019-12-12 07:24
Duplicate of #2572

**Closed by fregante** 2019-12-12 07:24 UTC
Labels: bug

**Comment by Modelmat** [comment] 2019-12-12 08:53
Ah, didn't see this.
