### ISSUE TITLE
Feature request: Pin issues

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/refined-github#1571] opened 2018-10-08 13:47 UTC
There are a few issues at a time that I absolutely cannot lose track of, and sometimes I'll go back to read them and forget to mark them as unread later on.

Any chance of getting a thumbtack icon next to "mark as unread" or something that keeps them in the notifications view until I manually un-pin them?

The notification color would probably red, and would be the least prioritized (e.g. blue if there are _any_ new notifications, green if there are _any_ manually unread notifications, and finally red if there are _any_ pinned issues).

This is similar to #1481 in nature but a different use-case. Also, "just use browser bookmarks" is a complete non-starter as far as solutions go.

**Comment by bfred-it** [comment] 2018-10-09 05:32
This is a complete duplicate of the #1481 you mentioned.

> #1571: something that keeps them in the notifications view until I manually un-pin them?

> #1481: will not be cleared from notifications list until you manually 'resolve' them

**Comment by sindresorhus** [comment] 2018-10-09 06:54
Duplicate of #1481

**Closed by sindresorhus** 2018-10-09 06:54 UTC

**Comment by sindresorhus** [comment] 2018-10-09 06:55
Sorry @Qix-, but the current "mark as unread" functionality is quite complex and we would prefer to not add even more bloat to it. This functionality is also not something we or I guess most people would need.
