### ISSUE TITLE
Github Browse Activity Tab does not work anymore

### ISSUE THREAD

**Issue by deadcoder0904** [sindresorhus/refined-github#1114] opened 2018-02-23 15:19 UTC
Goto https://github.com 

Once I disable the extension, it works obviously 😂

**Comment by bfred-it** [comment] 2018-02-23 15:51
Define "does not work"

**Comment by deadcoder0904** [comment] 2018-02-23 15:54
# Disabled Refined Github

![disabled](https://user-images.githubusercontent.com/16436270/36603156-ecec91c6-18df-11e8-8a94-c2b7effb722b.png)

# Enabled Refined Github

![enabled](https://user-images.githubusercontent.com/16436270/36603167-f5c46b02-18df-11e8-9e2f-2f5565a8a290.png)

**Comment by bfred-it** [comment] 2018-02-23 15:56
Oh wow, can you look into the Developer Tools to see what's being hidden by what?

**Comment by yakov116** [comment] 2018-02-23 15:57
@bfred-it this is not #1063?

**Comment by bfred-it** [comment] 2018-02-23 15:58
@yakov116 starred items should not be hidden, so something isn't working right.

**Comment by bfred-it** [comment] 2018-02-23 16:01
Oh, wait, that's covered by `hide-own-stars`, so probably @deadcoder0904's feed is just that. Closing as working as intended. 

This can be configured by disabling `hide-own-stars` and `hide-useless-newsfeed-events`

**Closed by bfred-it** 2018-02-23 16:01 UTC

**Comment by bfred-it** [comment] 2018-02-23 16:06
Yep that's it, you're not following anyone and by default Refined GitHub hides most _ego_ events.

<img width="147" alt="" src="https://user-images.githubusercontent.com/1402241/36603648-0c05d6ea-18ee-11e8-9e8c-2fc64a46e2b7.png">

**Comment by Mifrill** [comment] 2018-04-09 07:05
This definitely does not work correctly.
First, nothing is displayed at all. Secondly, there are no new followers. I think it's better to reopen this issue. Thanks

http://prntscr.com/j2rbyf

**Comment by bfred-it** [comment] 2018-04-09 09:27
Try disabling `hide-useless-newsfeed-events` and post a screenshot. What do you see?

**Comment by bfred-it** [comment] 2018-04-09 09:29
You, like the original poster, are not following anyone. All of your newsfeed events are hidden because they're all **your events**.

They are hidden by default.

Disable `hide-own-stars` and `hide-useless-newsfeed-events` if you want to see them.
