### ISSUE TITLE
Shortcut compare & pull request header interface broken

### ISSUE THREAD

**Issue by tcelestino** [sindresorhus/refined-github#3763] opened 2020-11-24 13:49 UTC
Using Firefox 83 on Ubuntu 18.04, shortcut `compare & pull request` in the header is broken.

![Screenshot from 2020-11-23 18-42-35](https://user-images.githubusercontent.com/190265/100100779-192b8800-2e40-11eb-8b5d-76d1a578b65a.png)

**Comment by yakov116** [comment] 2020-11-24 13:51
@tcelestino what version of the extension are you on?? This was disabled globally.

**Comment by fregante** [comment] 2020-11-24 19:13
Duplicate of #3748

**Closed by fregante** 2020-11-24 19:13 UTC
Labels: bug

**Comment by tcelestino** [comment] 2020-11-28 09:55
@fregante after update this issue is done. 

@yakov116 sorry man, this week I worked a lot 😄  

thanks guys!!
