### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#1935] opened 2019-04-18 01:39 UTC
- [ ] On pr page

```
❌ pr-branches
content.js:1865 Error: GraphQL:
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
Argument 'number' on Field 'NaN' has an invalid value. Expected type 'Int!'.
```

- [ ] Almost all pages

```
❌ remove-projects-tab
content.js:1865 TypeError: Cannot read property 'parentElement' of null
    at content.js:2490
    at content.js:478
    at remove_projects_tab_init (content.js:2501)
    at async features_run (content.js:1860)
```

- [x] Doesnt always give the error but it stopped working: https://github.com/sindresorhus/refined-github/issues/1940

```
❌ show-names
content.js:1865 TypeError: Cannot read property 'name' of undefined
    at show_names_init (content.js:4586)
    at async details.init (content.js:1903)
    at async features_run (content.js:1860)

```

**Comment by yakov116** [comment] 2019-04-18 02:32
@bfred-it (dont want to open a new issue) side thing. Is it a new thing that clicking on the RG icon it does not open the options. Rather it takes you to github.com?

**Comment by bfred-it** [comment] 2019-04-18 02:47
Yeah, I dropped the pop up because it’s options are already accessible via right click and it’s not something people actually need it that frequently. The only reason why we have a “browser_action” at all is for GHE users.

**Comment by robbiet480** [comment] 2019-04-18 06:03
Also seeing this problem. Seems the `parentElement` issue is causing names to not appear properly, like so:

![image](https://user-images.githubusercontent.com/18516/56339913-f5cd3100-6164-11e9-868c-926bd88ae8fe.png)

**Comment by bfred-it** [comment] 2019-04-18 17:42
That's been fixed by https://github.com/sindresorhus/refined-github/issues/1940

**Comment by bfred-it** [comment] 2019-04-19 10:50
One more bug caused by `pr-branches` in combination with `view-markdown-source`:


https://github.com/sindresorhus/refined-github/blob/afac4478c1eea65f98cac19e80ce81e0f975b15e/.github/ISSUE_TEMPLATE/bug_report.md

Click on the `View Source` button and this happens:

<img width="788" alt="Screenshot 2019-04-19 at 18 49 53" src="https://user-images.githubusercontent.com/1402241/56421205-f2a48300-62d3-11e9-8917-b1e5bfdcc4b1.png">

**Comment by HardikModha** [comment] 2019-04-19 20:23
`releases-tab` is also broken.

**Comment by HardikModha** [comment] 2019-04-19 20:28
@bfred-it I think a simple fix would be not to add the buttons if they are already added. What do you think? Are there any edge-cases that we may miss?

**Comment by HardikModha** [comment] 2019-04-19 20:34
I tested with the above changes and the issue is not being reproduced. I've pushed the changes.

**Comment by bfred-it** [comment] 2019-04-20 01:50
> `releases-tab` is also broken.

Indeed. We are in a unique situation _we_ are triggering `pjax:end` to the same page to potentially add features to the newly-injected `markdown-source`, but this means that any listener will expected a new page to be injected.

Come to think of it, this should already be prevented by `<has-rgh>`/`onAjaxedPages` 🤔

I think that maybe I should just drop the `pjax:end` event in `view-markdown-source` because it's not entirely correct.

**Closed** 2019-04-20 02:11 UTC
Labels: bug, has PR
