### ISSUE TITLE
File info overlay no longer present

### ISSUE THREAD

**Issue by TomasBarry** [sindresorhus/refined-github#1732] opened 2019-01-17 13:09 UTC
The features described [here](https://github.com/sindresorhus/refined-github/issues/943) seems to no longer be present. Was this feature deliberately removed or is there an issue with the feature?

**Comment by bfred-it** [comment] 2019-01-17 14:02
I think this is a duplicate of #1727

**Closed** 2019-01-17 14:30 UTC
