### ISSUE TITLE
TypeError on page load, "more" dropdown always visible & not dismissable

### ISSUE THREAD

**Issue by khaled** [sindresorhus/refined-github#2366] opened 2019-08-21 13:52 UTC
* Extension version: 19.8.20
* URL: any page where the tab menu is displayed (e.g. https://github.com/sindresorhus/refined-github)
* I tried disabling the extension and the problem goes away (both the TypeError and the stuck dropdown)

Error that appears in the console:

<img width="762" alt="Screen Shot 2019-08-21 at 9 44 50 AM" src="https://user-images.githubusercontent.com/11412/63437577-c96a3f80-c3f8-11e9-9181-c02891e07ad7.png">

Stuck "more" dropdown:

<img width="794" alt="Screen Shot 2019-08-21 at 9 45 05 AM" src="https://user-images.githubusercontent.com/11412/63437643-e43cb400-c3f8-11e9-9e1b-dec015f65036.png">

**Comment by anowlcalledjosh** [comment] 2019-08-21 13:53
It's not just the "More" dropdown that this affects:

![image](https://user-images.githubusercontent.com/9433472/63437937-6c37b380-c423-11e9-98d4-db7ab060ea11.png)

**Comment by pedrosimao** [comment] 2019-08-21 13:55
I am also experiencing this. I have to disable the extension for now.

**Comment by Drapegnik** [comment] 2019-08-21 14:01
@pedrosimao, FIY: you can disable just `more-dropdown` options, not the entire extension: 

<img width="576" alt="Screen Shot 2019-08-21 at 16 59 23" src="https://user-images.githubusercontent.com/11758660/63438523-1c61e800-c435-11e9-8812-4f850c80aace.png">

**Comment by kidonng** [comment] 2019-08-21 14:01
For the error message please see #2334
For the dropdown see #2357
@anowlcalledjosh hzoo/contributors-on-github#28

**Comment by anowlcalledjosh** [comment] 2019-08-21 14:04
aha, cheers – I forget which extensions I have installed :P

**Comment by notlmn** [comment] 2019-08-21 14:33
Duplicate of #2357.

**Closed by notlmn** 2019-08-21 14:33 UTC
Labels: bug
