### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#1305] opened 2018-05-07 15:52 UTC
- [x] When clicking on the add emoji where the delete option is not there.
```
VM1188 content.js:3091 Uncaught TypeError: Cannot read property 'querySelector' of null
    at HTMLDocument.event (VM1188 content.js:3091)
    at HTMLDocument.<anonymous> (VM1188 content.js:167)
```
- [x] When going the projects tab
```
content.js:1391 Uncaught (in promise) TypeError: Cannot read property 'classList' of null
    at updateUnreadIndicator (content.js:1391)
    at github_injection_default (content.js:1481)
    at gitHubInjection (content.js:357)
    at mark_unread (content.js:1465)
```
- [x] When going to `https://github.com/organizations/**{org}**/settings/apps/new`
```
TypeError: Cannot read property 'after' of null
    at add_your_repositories_link_to_profile_dropdown (content.js:2271)
    at enableFeature (content.js:1108)
```
- [x] https://gist.github.com/discover
```
Error: Missing required `user` and `repo` options
    at module.exports (content.js:478)
    at editTextNodes (content.js:1824)
    at linkify_urls_in_code (content.js:1849)
    at enableFeature (content.js:1108)
```
- [x] When going to a profile
```
content.js:3120 Uncaught (in promise) TypeError: Cannot set property 'textContent' of null
    at add_scoped_search_on_user_profile (content.js:3120)
```
- [ ] Going to a gist profile
```
content.js:1095 TypeError: Cannot read property 'before' of null
    at copy_file (content.js:1773)
    at enableFeature (content.js:1091)
``` 
- [ ] Clicking on More (Next to releases)
```
content.js:3102 Uncaught TypeError: Cannot read property 'querySelector' of null
    at HTMLDocument.event (content.js:3102)
    at HTMLDocument.<anonymous> (content.js:167)
```

**Comment by yakov116** [comment] 2018-05-09 18:12
*New* Going to a gist profile
```
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at add_scoped_search_on_user_profile (content.js:3108)
```

**Comment by bfred-it** [comment] 2018-05-09 18:14
As I said it's a duplicate of #1282

**Comment by yakov116** [comment] 2018-05-09 19:37
**New** Clicking on More (Next to releases)

```
content.js:3091 Uncaught TypeError: Cannot read property 'querySelector' of null
    at HTMLDocument.event (content.js:3091)
    at HTMLDocument.<anonymous> (content.js:167)
```

**Comment by yakov116** [comment] 2018-05-16 13:47
@bfred-it 
>Duplicate of #1282

Should this have been fixed (You deployed the change when you did the test release)? I tried it now and the error is still there.

**Closed** 2018-06-04 18:49 UTC
Labels: bug, good first issue, help wanted
