### ISSUE TITLE
Collapse large sequences of label, milestone, etc changes

### ISSUE THREAD

**Issue by aaronbushnell** [sindresorhus/refined-github#615] opened 2017-07-12 18:57 UTC
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/615)

I apologize if this has already been mentioned, but I did not see an issue for it.

Sometimes issues get very noisy when labels and milestones are added/removed. They push comments down and make it difficult to see updates to the item that aren't related to the project management side.

It would be nice if these large sequences (excluding comments) could "collapse". Here's an example of what I'm describing.

![screenflow](https://user-images.githubusercontent.com/315202/28134893-677e8e60-6712-11e7-9228-f9c8da1b26a5.gif)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)

### Submitted pull Requests
- [#4029 Add `conversation-activity-filter` feature](https://issuehunt.io/r/sindresorhus/refined-github/pull/4029)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by bfred-it** [comment] 2017-07-13 02:03
The name changes are definitely annoying so I'd put a vote to hide _those_, but references from other issues are useful.

**Comment by jgierer12** [comment] 2017-07-13 16:18
I also think references and commits should stay expanded. But hiding title changes, deploys and label changes would be great. Some things like assignments don't occur very often per issue, so I think they should stay expanded too.

---

Hidden events should be as unobstrusive as possible IMO, perhaps something like this would work:
![Hidden events mockup](https://user-images.githubusercontent.com/4331946/28176188-c989f696-67f6-11e7-8062-46e4af70d80d.png)
Clicking the "+" would expand the hidden events

**Comment by hkdobrev** [comment] 2017-07-13 16:20
I'd prefer collapsing title changes with title changes, label changes with label changes, milestone changes with milestone changes, project changes with project changes, reviewers changes with reviewers changes and assignees changes with assignees changes.

**Comment by jgierer12** [comment] 2017-07-13 16:21
Another idea, perhaps we could hide or group events that are reverted in a short period of time, such as closing and re-opening an issue within a few minutes as that's almost always an accident

**Comment by hkdobrev** [comment] 2017-07-13 16:37
> Another idea, perhaps we could hide or group events that are reverted in a short period of time, such as closing and re-opening an issue within a few minutes as that's almost always an accident

I consider closing/re-opening or restoring and re-deleting a branch to be significant events.

**Comment by bfred-it** [comment] 2017-07-14 06:23
Closing/reopening within minutes is probably because of a mistake and IMHO it should be hidden.

Restoring/deleting branches... not sure of when they are ever useful (other than "let's display every event")

**Comment by sindresorhus** [comment] 2017-10-18 05:23
Pull request welcome if anyone wants to see this feature :)

**Comment by yakov116** [comment] 2018-02-07 06:04
Going to give this a bump,  could have used this today

**Comment by bfred-it** [comment] 2018-12-09 17:50
This could be made part of `hide-useless-comments` and the feature can become `hide-noise`

The logic should already be there. If anyone is interested you probably just need to tweak the selector and update the name/docs.

**Comment by bfred-it** [comment] 2018-12-09 18:31
> sometimes I need to look at _noise_.

Same goes for this issue

**Comment by yakov116** [comment] 2018-12-09 18:33
@bfred-it good point, however I think these are 2 different types of noise.
>  It makes sense to have a single button to show all the noise at once, instead of two.

Not sure. 

Lets hear what others have to say.

**Comment by sindresorhus** [comment] 2019-06-24 17:51
I would prefer one button too. Something like "Show 23 useless comments and events".

**Comment by bfred-it** [comment] 2019-07-02 05:31
I made some noise in #2201 

Can _all_ those events be hidden? Or just nearby events that cancel each other out?

What do you think about:

- Labels: hide all
- Title changes: hide all but the last one
- Assignments: only when they cancel each other out
- Open/close: only when they cancel each other out
- Milestones: only when they cancel each other out
- Projects only when they cancel each other out

And then:

- Lock/unlock: leave unchanged

**Comment by sindresorhus** [comment] 2019-07-25 22:20
What you suggested above sounds good to me.

**Comment by AnthonyLenglet** [comment] 2019-08-27 11:10
to combined #2384 here, this issue is an exemple of issue noise caused by bots that upgrade dependencies when an issue is mentioned in the release note

FortAwesome/Font-Awesome#15396

![image](https://user-images.githubusercontent.com/36004334/63694083-ef874980-c815-11e9-8668-e45c74d38f39.png)
![image](https://user-images.githubusercontent.com/36004334/63694096-f4e49400-c815-11e9-9325-f06086d56e67.png)

stuff like this makes it simply impossible to read anything easily :/

I really like the idea @fregante proposed here, for the projects I would suggest `only when they cancel each other out` just like most of those (moving a card back and forward between columns)

**Comment by fregante** [comment] 2019-10-29 16:17
@AnthonyLenglet Bots are best handled by https://github.com/sindresorhus/refined-github/issues/1745

**Comment by Tiramisu77** [comment] 2019-11-10 09:41
I'm working on this feature (as per @fregante 's comment), and it's not clear to me what exactly should count as a sequence of actions. So far I have the following ideas:

1. Don't use sequences at all and handle actions on the whole page
2. Group actions by date
3. Select all actions between comments

**Comment by pradyunsg** [comment] 2020-05-25 18:44
Flagging that #1745 was closed since straight-up hiding bot comments isn't a good idea (and I agree!).

Coming from https://github.com/pypa/pip/issues/5182#issuecomment-603169486, I think it'd be great to have some way to collapse commit/PR references as well.

**Closed** 2021-03-05 05:08 UTC
Labels: :dollar: Funded on Issuehunt, enhancement, help wanted, under discussion
