### ISSUE TITLE
` highlight-closing-prs-in-open-issues` is broken

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#2455] opened 2019-09-25 02:38 UTC
```console
❌ highlight-closing-prs-in-open-issues
content.js:2847 TypeError: Cannot read property 'querySelector' of null
    at MutationObserver.highlight_closing_prs_in_open_issues_add (content.js:5738)
    at observeEl (content.js:2735)
    at highlight_closing_prs_in_open_issues_init (content.js:5751)
    at features_run (content.js:2842)
    at content.js:2889
    at content.js:2804
    at onAjaxedPagesRaw (content.js:2799)
```

**Comment by fregante** [comment] 2019-11-10 18:44
Closing in favor of https://github.com/sindresorhus/refined-github/issues/2372

The feature is basically unnecessary now. If a PR comes, it should be to change the feature to use the information GitHub already provides and make it prettier. Not a bug fix

**Closed by fregante** 2019-11-10 18:44 UTC
Labels: bug, good first issue, help wanted
