### ISSUE TITLE
The more drop-down is always open

### ISSUE THREAD

**Issue by LalyStana** [sindresorhus/refined-github#2369] opened 2019-08-21 16:32 UTC
![Screenshot from 2019-08-21 12-31-20](https://user-images.githubusercontent.com/11777927/63450301-b1ea8100-c40f-11e9-97ab-aa357a8e7b9c.png)

**Comment by goodevilgenius** [comment] 2019-08-21 16:36
I had to disable the extension because of this. I just noticed it this morning, but I wasn't on GitHub at all yesterday, so it could've started yesterday as well.

**Comment by jalessio** [comment] 2019-08-21 16:45
@LalyStana This is a duplicate of https://github.com/sindresorhus/refined-github/issues/2357

**Comment by wachunei** [comment] 2019-08-21 16:45
duplicate of #2357

**Comment by yakov116** [comment] 2019-08-21 16:46
@LalyStana 	update your extension

**Closed** 2019-08-21 16:51 UTC
Labels: bug
