### ISSUE TITLE
Display rich diff for pictures by default

### ISSUE THREAD

**Issue by LOuroboros** [sindresorhus/refined-github#4703] opened 2021-08-23 06:41 UTC
### Description

Hi. I wanted to drop a quick suggestion.
It would be cool to have a setting to make the addon display the rich diffs for changes done to graphic files using formats as .jpg, .png, and similar when looking at a commit by default, instead of the source diff.

### Example URL

https://github.com/sindresorhus/refined-github

**Comment by fregante** [comment] 2021-08-23 07:43
Duplicate of https://github.com/sindresorhus/refined-github/issues/2673

**Closed by fregante** 2021-08-23 07:43 UTC
Labels: enhancement, under discussion
