### ISSUE TITLE
Why cant i use it with github enterprise ?

### ISSUE THREAD

**Issue by nobso** [sindresorhus/refined-github#318] opened 2016-10-18 21:55 UTC
First of all, Thanks! this is really useful! 

I see that this package allows only ``` https://github.com/*,  https://gist.github.com/* ``` origins, but i've a github enterprise and i dont want to do any host mapping to get it working.  I thought i would introduce an option that can be taken from the user, but the below comment stops me doing that 😃 

> We're happy to receive suggestions and contributions, but be aware this is a highly opinionated project. We're not interested in adding options as it's a slippery slope into adding it for everything. Users will always disagree with something. That being said, we're open to discussing things.

Anyway, i could manually add an origin in the manifest.json and import it into my browser to make it work for now.

Can we take this as an enhancement?

**Comment by hkdobrev** [comment] 2016-10-18 22:01
Thanks for opening the issue! However I'm closing this as duplicate of #315. Please subscribe to it and participate in any discussion there. Cheers!

**Closed by hkdobrev** 2016-10-18 22:01 UTC

**Comment by nobso** [comment] 2016-10-18 22:08
Thanks for the quick response!
