### ISSUE TITLE
Allow comments on unchanged lines

### ISSUE THREAD

**Issue by MatthiasSchmalz** [sindresorhus/refined-github#3892] opened 2021-01-12 16:05 UTC
When reviewing a PR the diff view only allows commenting on changed lines and some lines around but not everywhere in the file. Sometimes this would be beneficial.
A long reasoning for this can be found here: 
https://github.com/isaacs/github/issues/284
Since Github does not seem to implement this, it would be great if refined Github could enable it.
Unfortunately I am not able to judge whether this is technicaly feasible.

**Comment by sindresorhus** [comment] 2021-01-12 16:42
I don't think this is technically possible. You should send this feature request to GitHub regardless.

**Comment by fregante** [comment] 2021-01-12 20:12
Duplicate of https://github.com/sindresorhus/refined-github/issues/2588

**Closed by fregante** 2021-01-12 20:12 UTC
Labels: enhancement, under discussion
