### ISSUE TITLE
Too much whitespace under some news feed events

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#475] opened 2017-06-06 14:17 UTC
<img width="656" alt="screen shot 2017-06-06 at 17 32 04" src="https://cloud.githubusercontent.com/assets/170270/26833750/8cbdc942-4afd-11e7-9776-b98ed090ebf2.png">

**Comment by fnky** [comment] 2017-06-23 13:41
Is it also supposed to put the humanized time above the event text? GitHub's default feed seems much cleaner compared to Refined:

![image](https://user-images.githubusercontent.com/995050/27484686-6be657fe-582a-11e7-9978-d233a7ea55ae.png)

**Comment by plessbd** [comment] 2017-06-23 13:53
I personally like that the time is above, makes it easier to scan for the time since it is always in the same spot.

**Comment by fnky** [comment] 2017-06-23 13:54
True. However I'd still like it to be a lot smaller than it currently is, as it fills the page a lot more on smaller screens.

**Comment by sindresorhus** [comment] 2017-06-23 13:58
> Is it also supposed to put the humanized time above the event text? GitHub's default feed seems much cleaner compared to Refined:

Consistency.

> True. However I'd still like it to be a lot smaller than it currently is, as it fills the page a lot more on smaller screens.

Happy to consider design tweaks, but it should apply consistently to all news items.

**Comment by sindresorhus** [comment] 2017-06-23 13:59
@fnky Can you open a separate issue about it? It's unrelated to this issue.

**Comment by abnersajr** [comment] 2017-06-29 12:39
@sindresorhus this problem has been caused by some `.create.simple` elements.
Inspecting the DOM is possible to see what kind of content normally has been shown there. Is simple alerts like create a branch.

Can you assign this issue to me?
I'm fixing that.

**Comment by sindresorhus** [comment] 2017-06-29 12:55
Done

**Comment by bfred-it** [comment] 2017-07-18 07:22
Reported as fixed by #599

**Closed** 2017-07-18 07:22 UTC
Labels: assigned, bug, has PR
