### ISSUE TITLE
Daily deploy is failing

### ISSUE THREAD

**Issue by xzyfer** [sindresorhus/refined-github#626] opened 2017-07-18 06:43 UTC
The daily cron deploy has been failing for ~3 days with this error

```
Module build failed: Error: Couldn't find preset "babili" relative to directory "/home/travis/build/sindresorhus/refined-github"
```

See https://travis-ci.org/sindresorhus/refined-github/builds/254436866

**Comment by bfred-it** [comment] 2017-07-18 06:43
Duplicate of #623

**Closed by bfred-it** 2017-07-18 06:43 UTC
