### ISSUE TITLE
Minor feature request: option to hide whitespace changes by default in PR file view

### ISSUE THREAD

**Issue by fluffynuts** [sindresorhus/refined-github#3655] opened 2020-10-15 06:36 UTC
Similar to the option to preserve the setting whilst moving between PRs, I'd really find it helpful if there was a "hide whitespace changes by default" option which would append `w=1` to the "add your review" button link.

I basically never care about whitespace changes (I'm certainly not alone here in our team, but I'm not sure how global a stance this is) -- we have .editorconfig settings which help the team to be consistent and there are occasionally old files which have been auto-formatted, so of course it looks like the whole file changed. I typically find one of these about 1/2-way through a review, so have to scroll back up to the top to tick the box to hide whitespace changes.

**Comment by yakov116** [comment] 2020-10-15 13:06
Duplicate of #2503

**Comment by yakov116** [comment] 2020-10-15 13:06
>We're are going to pass on this. The whitespace setting is meant to be temporary. If you ignore whitespace, you'll miss mistakes in PRs.

_Originally posted by @sindresorhus in https://github.com/sindresorhus/refined-github/issue_comments/559747899_

**Closed by yakov116** 2020-10-15 13:06 UTC
Labels: enhancement, under discussion

**Comment by fregante** [comment] 2020-10-15 17:53
Hopefull https://github.com/sindresorhus/refined-github/issues/2597 will restore the shortcut key (<kbd>w</kbd>) so that it's easier to toggle it
