### ISSUE TITLE
`forked-to`: element not found

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#2334] opened 2019-08-15 04:24 UTC
![1](https://user-images.githubusercontent.com/44045911/63072310-b61d2700-bf55-11e9-9856-e92aec86cb35.png)

https://github.com/sindresorhus/refined-github/blob/f8c2fab4cfd8f85f19552a897f1a6df49ea441d9/source/features/forked-to.tsx#L54-L56

Browser: Chrome 78.0.3880.4
Extension: 19.8.14
Example URL: all repos 💥

I don't know if this only happens to me, but there seems to be no `details-dialog[src*="/fork"]` element it is looking for.
I've tried only enabling Refined GitHub and still the same.

Well, this bug has been there quite a while, but I thought it was network error caused by uBlock (at first glance) and didn't mind 😅

**Comment by fregante** [comment] 2019-08-15 08:48
Yes, it's because we're expecting a list of organizations on that element but you don't have any. This will be fixed by #2230

**Comment by jerone** [comment] 2020-01-20 21:45
To reproduce this error, you have to comply to the following conditions; it happens when the user is 1) not part of an organization and 2) has not forked the repo.

**Closed** 2020-01-22 04:39 UTC
Labels: bug, has PR, help wanted
