### ISSUE TITLE
Tooltip not visible on PR collapse file diff button

### ISSUE THREAD

**Issue by Glennmen** [sindresorhus/refined-github#1609] opened 2018-11-05 09:27 UTC
This only seems to happen when the extension is active (default Github has no issue) and it also only happens on the first file diff container.

The tooltip `Toggle diff contents` is hidden by the top bar, I think this is a z-index issue.

Extension disabled:
<img width="416" alt="screenshot at nov 05 10-22-04" src="https://user-images.githubusercontent.com/11406433/47989325-f5743880-e0e4-11e8-8ddd-b164c625ccc0.png">

Extension enabled:
<img width="469" alt="screenshot at nov 05 10-21-45" src="https://user-images.githubusercontent.com/11406433/47989356-08870880-e0e5-11e8-9514-4c79162a457e.png">

**Comment by sindresorhus** [comment] 2018-11-06 15:38
Duplicate of #1295

**Closed by sindresorhus** 2018-11-06 15:38 UTC
