### ISSUE TITLE
#751 introduced the inability to post multiline comment

### ISSUE THREAD

**Issue by casz** [sindresorhus/refined-github#794] opened 2017-11-03 09:13 UTC
Because it assumes I am only intend on submitting a single line comment....
on windows Shift+Enter is reserved for making single new line.

However enter on Github is new line yes, but I cannot change my habit cause I always assume Enter is for submitting. That's why shift enter is my gotoguy for new line.

**Comment by bfred-it** [comment] 2017-11-03 09:54
shift+enter is used to make new lines on Mac too, when the standard enter is mapped to “new paragraph”. As far as I know this only happens in word processing software and not code editors, which don’t have the concept of “paragraph”

I’m the browser, in the comment’s `<textarea>`, they both do the same, and since enter is easier to press than shift+enter, people just use enter.

**Comment by bfred-it** [comment] 2017-11-03 09:55
Reminds me of:


<a href="https://xkcd.com/1172/"><img width="278" alt="workflow_2x" src="https://user-images.githubusercontent.com/1402241/32368272-36e9321a-c053-11e7-9f31-4dc92e690fbc.png"></a>

**Comment by fwextensions** [comment] 2017-11-04 02:40
I hate changes that break muscle memory, too.  But <kbd>shift</kbd><kbd>enter</kbd> seemed like the least-bad option for the shortcut, since <kbd>ctrl</kbd><kbd>shift</kbd><kbd>enter</kbd> triggers the full review as well.

**Comment by sindresorhus** [comment] 2017-11-06 06:47
Closing as it's working as intended.

**Closed by sindresorhus** 2017-11-06 06:47 UTC
Labels: change request

**Comment by saurabhshri** [comment] 2018-01-14 07:38
Is it possible to disable `shift` + `enter` for single line comment, I would like to keep the default behaviour of new line? What do I enter in the "Disable Features" box to disable it? I have enabled logging, but my console is still empty. I might need to restart my browser - but way too many tabs opened to do that right now. :)

**Comment by bfred-it** [comment] 2018-01-14 07:44
> I have enabled logging, but my console is still empty.

You probably just have to reload GitHub's tab

> What do I enter in the "Disable Features" box to disable it?

```
add-keyboard-shortcuts-to-comment-fields
```

**Comment by saurabhshri** [comment] 2018-01-14 07:49
@bfred-it Thanks! :) Looks like it disables everything in that file. I'll edit that part of code and prepare my own extension - because I am happy with the remaining ones. Thanks!

>You probably just have to reload GitHub's tab

Yep :)
