### ISSUE TITLE
Add a global toggle to switch between light  and dark themes

### ISSUE THREAD

**Issue by maximousblk** [sindresorhus/refined-github#3960] opened 2021-02-09 13:13 UTC
many people (read "I") prefer to use "dark mode" only at night but there is no quick way to easily toggle it if working on something. There are currently 2 ways (that I know) to toggle the dark mode: 1. settings, 2. toggle on the profile page.

It would be more convenient to move the toggle from the profile page to either the navbar or the profile dropdown on the navbar.

---

alternative suggestions:

It would be even more convenient to not need to switch to dark mode manually and it would automatically switch depending on the time of the day but as mentioned in #2960, this would most probably be disabled by default and many people would want to configure at what time should the theme switch, so doesn't really fit this project but up for grabs for userscripts and the likes.

**Comment by yakov116** [comment] 2021-02-09 13:32
Duplicate of #3802

**Closed** 2021-02-09 13:42 UTC
Labels: enhancement, under discussion

**Comment by fregante** [comment] 2021-02-09 17:44
> it would automatically switch depending on the time of the day

I'd suggest looking into a global solution for this. macOS does so natively, for example.

**Comment by kidonng** [comment] 2021-11-11 17:09
GitHub (sort of) implemented this, see https://github.com/refined-github/refined-github/issues/3802#issuecomment-966471452
