### ISSUE TITLE
Make it easy to delete forks

### ISSUE THREAD

**Issue by ostrolucky** [sindresorhus/refined-github#776] opened 2017-10-27 12:00 UTC
You know the drill. You want to contribute, so you create a fork, do a simple change and create pull request. You repeat this few times and you have created tons of unused forks in your account which just make it harder to find your repos you actually care about. Can we do something about this? Make it easier to delete fork repos? Or maybe toggle to hide such repos?

**Comment by hkdobrev** [comment] 2017-10-27 21:48
We have added a link to delete your fork on a merged PR in #49 and fixed it in #321:
![](https://cloud.githubusercontent.com/assets/170270/13520281/b2c9335c-e211-11e5-9e36-b0f325166356.png)

However, I think this has been broken again for some time now. I'll mark this issue as a bug.

@ostrolucky Are you willing to look into the code from the mentioned pull requests, find the cause why it's not working and submit a pull request? That would be awesome!

**Comment by yakov116** [comment] 2017-10-30 19:15
I am seeing this even if i dont have access. Can we test the link to see if its leads to 404?

**Comment by bfred-it** [comment] 2017-10-31 00:06
How can you not delete the fork if you can delete a branch (of a fork)? Where are you seeing this?

**Comment by yakov116** [comment] 2017-10-31 00:12
@bfred-it very simple if you have write access to a repo and that repo made a pull request to a fork

**Comment by bfred-it** [comment] 2017-10-31 00:56
I think this can be verified by looking for the Settings tab in the repo. You can’t access that page, right?

PRs welcome

**Closed** 2017-11-15 02:37 UTC
Labels: bug, has PR, help wanted

**Comment by dwijnand** [comment] 2019-01-11 10:20
It would be lovely if this were available even before the PR is merged.  GitHub PRs don't actually require the fork to exist in order to merge the PR, so I'd love to be able to insta-delete my fork after PRing.  What do you think?

**Comment by dwijnand** [comment] 2019-01-11 11:33
Does deleting the repo indicate a PR is not "good to go"?  It does make the PR immutable but that's an option for contributors even without deleting the repo.

**Comment by bfred-it** [comment] 2019-01-11 11:54
It means that either the PR is good at first try or it **has** to be thrown out. It smells like “what I changed is good to go and I don’t care if it isn’t”

**Comment by dwijnand** [comment] 2019-01-11 15:35
> it **has** to be thrown out

No, it doesn't.  Once you've re-forked, I haven't tested if you can or can't restore the branch from the web UI, but you can do it from the command line.  Sure, if you can't from the web UI then it makes it a bit cumbersome, but maybe sometimes you want that choice.

**Comment by bfred-it** [comment] 2019-01-12 04:52
It’s not a behavior I’d personally facilitate. It’s easier to just wait for the merge (you’ll be notified) and then delete it. 

If you don’t want to have *any* forks on your repo, you can create an org and fork everything to that one. I use an org to archive my repos and anything I don’t want on my main profile, for example.

**Comment by dwijnand** [comment] 2019-01-12 07:41
Yep, it's an alternative I've considered.

**Comment by dwijnand** [comment] 2019-02-15 08:28
GitHub provides deleting a fork after merge/close out the box now:

![image](https://user-images.githubusercontent.com/344610/52844055-a3877980-30fb-11e9-8dae-9ffd6cb9237a.png)

**Comment by bfred-it** [comment] 2019-02-15 08:39
https://github.com/sindresorhus/refined-github/issues/1786
