### ISSUE TITLE
Create branch from issue

### ISSUE THREAD

**Issue by magick93** [sindresorhus/refined-github#2113] opened 2019-06-02 23:52 UTC
Similar to what gitlab.com has, a user should be able to create a branch from an issue.

Example URL:
 
Please see https://github.com/isaacs/github/issues/1125

**Comment by bfred-it** [comment] 2019-06-03 04:42
Duplicate of https://github.com/sindresorhus/refined-github/pull/1927#issuecomment-482845843

**Closed by bfred-it** 2019-06-03 04:42 UTC
Labels: enhancement, under discussion

**Comment by yakov116** [comment] 2021-07-14 14:15
This will be added to GitHub see https://github.com/github/roadmap/issues/218

**Comment by fregante** [comment] 2022-03-02 15:47
Added https://github.blog/changelog/2022-03-02-create-a-branch-for-an-issue/ 🎉
