### ISSUE TITLE
Sticky file header covers permalinked line

### ISSUE THREAD

**Issue by sompylasar** [sindresorhus/refined-github#919] opened 2017-12-28 19:06 UTC
#### Example

```
https://github.com/sindresorhus/refined-github/blob/7aad28997cdd9d6627c6620e242a17308f259897/source/content.js#L112
``` 
(navigate to this URL in a new tab)

#### Actual

<img width="1018" alt="screen shot 2017-12-28 at 11 02 04 am" src="https://user-images.githubusercontent.com/498274/34420504-d19e3b20-ebbe-11e7-83d1-4174344ebeaf.png">

#### Expected

<img width="1019" alt="screen shot 2017-12-28 at 11 02 23 am" src="https://user-images.githubusercontent.com/498274/34420512-dbdeb24a-ebbe-11e7-883e-95b7f80d31ce.png">

**Comment by bfred-it** [comment] 2017-12-29 03:44
Notice: this is not a bug of RGH

**Comment by sompylasar** [comment] 2017-12-29 03:52
@bfred-it Well, yes, technically not a bug but a consequence of the fixed top bar feature.

**Comment by bfred-it** [comment] 2017-12-29 03:56
No no, the top bar is fixed by GitHub. I didn't mean that as "won't fix this non-bug" but rather "we can improve this as an enhancement"  👍

**Comment by sompylasar** [comment] 2017-12-29 03:58
Oops for some reason I thought it's refined, or without refinement it behaved differently, otherwise I would notice the inconvenience years ago.

**Comment by bfred-it** [comment] 2017-12-29 04:07
It might be a new GitHub bug, can you report it to them? They might just fix it, I can see they're manually calling their function called `scrollToTargetFragment` so they are interested in getting it right.

**Comment by sompylasar** [comment] 2017-12-29 04:38
@bfred-it Yes, will do.

**Comment by bfred-it** [comment] 2017-12-29 07:10
My super-bad. It was indeed a bug of RGH. I disabled the extension and still saw it somehow.

**Comment by jgierer12** [comment] 2018-01-02 23:01
Removed some comments for legibility.

<details>
  <summary>Original discussion</summary><br />
  <p>
    <b>bfred-it</b>
    <blockquote>Notice: this is not a bug of RGH</blockquote>
  </p><br />
  <p>
    <b>sompylasar</b>
    <blockquote>(@)bfred-it Well, yes, technically not a bug but a consequence of the fixed top bar feature.</blockquote>
  </p><br />
  <p>
    <b>bfred-it</b>
    <blockquote>No no, the top bar is fixed by GitHub. I didn't mean that as "won't fix this non-bug" but rather "we can improve this as an enhancement" 👍</blockquote>
  </p><br />
  <p>
    <b>sompylasar</b>
    <blockquote>Oops for some reason I thought it's refined, or without refinement it behaved differently, otherwise I would notice the inconvenience years ago.</blockquote>
  </p><br />
  <p>
    <b>bfred-it</b>
    <blockquote>It might be a new GitHub bug, can you report it to them? They might just fix it, I can see they're manually calling their function called <code>scrollToTargetFragment</code> so they are interested in getting it right.</blockquote>
  </p><br />
  <p>
    <b>sompylasar</b>
    <blockquote>(@)bfred-it Yes, will do.</blockquote>
    <blockquote>:heart: bfred-it</blockquote>
  </p><br />
  <p>
    <b>bfred-it</b>
    <blockquote>My super-bad. It was indeed a bug of RGH. I disabled the extension and still saw it somehow.</blockquote>
  </p><br />
</details>

**Comment by bfred-it** [comment] 2018-01-05 07:21
I looked into fixing this via CSS and it doesn't seem to work with the [padding hacks](https://css-tricks.com/hash-tag-links-padding/) used for regular `#hash` linking, but because it's a table and it has that yellow background, some hacks are hard to apply. The [pseudo-element hack](https://stackoverflow.com/a/24298427/288906) also doesn't seem to work. I think this can only be fixed via JS.

Help wanted 😄

**Comment by bfred-it** [comment] 2018-01-09 07:11
Note: this also affects markdown files: https://github.com/sindresorhus/refined-github/blob/master/readme.md#install

**Closed** 2018-01-20 12:10 UTC
Labels: bug, has PR, help wanted
