### ISSUE TITLE
Star Repo's in HomePage

### ISSUE THREAD

**Issue by NotMoni** [sindresorhus/refined-github#3255] opened 2020-06-19 11:53 UTC
![Screen Shot 2020-06-19 at 7 52 40 AM](https://user-images.githubusercontent.com/40552237/85129857-db2b9780-b201-11ea-802d-4fcc78deaced.png)

Add star button next to repo's So I can star them as well.

**Comment by fregante** [comment] 2020-06-19 13:08
Duplicate of https://github.com/sindresorhus/refined-github/issues/1864

**Closed by fregante** 2020-06-19 13:08 UTC
Labels: enhancement, under discussion

**Comment by NotMoni** [comment] 2020-06-19 13:21
Oh  ok.
