### ISSUE TITLE
Refined Github doesn't work on Chrome/Edge until page is refreshed (reloaded)

### ISSUE THREAD

**Issue by PovilasAtPoq** [sindresorhus/refined-github#4785] opened 2021-09-15 09:25 UTC
**Steps**
I go to PR, click on Files tab, and Refined is not enabled.
I refresh the page (doesn't matter how, F5, hitting enter again in address bar, using mouse gesture) then Refined is enabled.

By enabled I mean I can see whitespace button and other changes which are being brought by the plugin.

-----------
**What I've tried?**

- I've disabled every single plugin on my Chrome
- I've reinstalled plugin
- Different browsers (Edge, Chrome) the same issue.

It started to happen about a month ago, I expected a fix to come out, but it's still not working.

**Comment by kidonng** [comment] 2021-09-15 14:40
Duplicate of #4695, please read the pinned issues carefully next time.

@fregante maybe the title for that issue is too technical? Replace "ajax" with "page" would be better.

**Comment by fregante** [comment] 2021-09-15 17:35
It's ok, duplicate issues are fine.

**Closed** 2021-09-15 17:35 UTC
Labels: under discussion

**Comment by PovilasAtPoq** [comment] 2021-09-15 21:55
> Duplicate of #4695, please read the pinned issues carefully next time.
> 
> @fregante maybe the title for that issue is too technical? Replace "ajax" with "page" would be better.

I would have never worked out that both of these issues are one and the same :)

I'm glad that this was already registered and obviously with more information what's not working.

Have a good day! :)
