### ISSUE TITLE
Extra spaces in comments because of using TAB

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/refined-github#162] opened 2016-04-06 18:38 UTC
This is a side effect of #117 I believe (pretty close to positive).

To use the available autocomplete when inserting a @ mention or emoji, you type <kbd>@</kbd>, <kbd>TAB</kbd> or <kbd>:</kbd>, <kbd>TAB</kbd>. This winds up adding extra spaces to the end of the comment. You don't really notice until you try to quickly get to the end of the text/line with <kbd>⌘</kbd><kbd>→</kbd>.

I have a sneaking suspicion that other keyboard events are adding spacing too, but I can't replicate it.

**Comment by sindresorhus** [comment] 2016-04-06 19:19
// @blackjid

**Comment by hkdobrev** [comment] 2016-04-06 19:31
We can work around that by detecting if we are in a code block or fenced code block. If we can't easily do that, I'd suggest using <kbd>Shift</kbd> + <kbd>Tab</kbd> for indenting.

**Comment by blackjid** [comment] 2016-04-06 20:47
I made a PR where I check whether the suggestion box is active of not before to indent

**Comment by hkdobrev** [comment] 2016-04-07 07:08
Can't we just use <kbd>Shift</kbd> + <kbd>Tab</kbd> for indenting so we won't be affecting the normal <kbd>Tab</kbd> behaviour?

**Comment by blackjid** [comment] 2016-04-08 13:03
I don't like the idea of <kbd>Shift</kbd> + <kbd>Tab</kbd> to fallback to normal. I rather prefer to unindent with that combination. That is what my muscle memory would expect.

Thoughts?

**Comment by paulmolluzzo** [comment] 2016-05-06 02:16
Does anyone have an objection to squashing this one via a revert of the functionality? There are 3 PRs to fix this (#164, #192, #197) and none seem close to completion.

Some motiviation: https://bugs.mysql.com/bug.php?id=16555

**Comment by jamestalmage** [comment] 2016-05-06 02:40
The tab functionality is what finally got me to install this. So I would hate to see it go.

Is there any possibility to display whitespace characters like my editor does? 

<img width="460" alt="screenshot 2016-05-05 22 39 19" src="https://cloud.githubusercontent.com/assets/4082216/15062823/39869bc4-1312-11e6-913b-26c92f5fd1fb.png">

**Comment by paulmolluzzo** [comment] 2016-05-06 02:46
I'd like to keep it too, but I see the bug more than I use the feature.

**Comment by jamestalmage** [comment] 2016-05-06 02:48
> but I see the bug more than I use the feature.

I don't get the problem though. It doesn't        render, so why is it a big deal?

**Comment by paulmolluzzo** [comment] 2016-05-06 03:01
The OP of this issue explains it, but I wind up with extra spaces at the end of the comment that I have to delete.

**Comment by jamestalmage** [comment] 2016-05-06 03:22
I'm      asking why       you feel the      need to delete them.

**Comment by paulmolluzzo** [comment] 2016-05-06 03:33
Because, @jamestalmage this     is why.

**Comment by jamestalmage** [comment] 2016-05-06 03:40
> E: GitHub trims the space? Still annoying. Let's kill the bug

That's my point though. The extra whitespace doesn't matter. Both of my previous messages have tons of added whitespace in them and you never noticed. Even in the email notification has no extra spaces in it. I'm all for killing the bug, but if it's living with this bug or living without the feature, I'll happily live with the bug. (I definitely think we can fix it though).

**Comment by sindresorhus** [comment] 2016-05-19 10:18
We merged a temp fix, but would be nice to fix it properly.

**Comment by Ma27** [comment] 2016-06-13 07:17
I'd also like to see ``Shift`` + ``Tab``.
Although I use refined-github for a while now and I like it, I'm still used to do ``Shift`` + ``Enter`` to submit a comment/PR/etc.

To avoid conflicts between those keyboard shortcuts I'd prefer that solution. If enough people are in favor of it (seen some comments of people who were against it) I could do this in a PR.

**Comment by sindresorhus** [comment] 2016-06-18 20:44
@Ma27 `Shift`+`Tab` is more commonly used for unindenting. I would prefer a solution that preserved `Tab` for indenting.

**Comment by jonhoo** [comment] 2017-05-21 18:04
The current behavior also interacts poorly with using `Ctrl` + `Tab` for switching tabs. If I'm writing a comment and have to switch to another tab for reference, pressing `Ctrl` + `Tab` causes spaces to be inserted into the comment just before the tab switch occurs. When I switch back, I have to erase the spaces before I can continue typing :(

**Comment by bfred-it** [comment] 2017-07-05 20:11
I can't reproduce any of the issues described here, which were probably addressed by https://github.com/sindresorhus/refined-github/blob/f304ff7fcfc8edbe07f4e33794fd2a043024711f/src/content.js#L470-L473

Can we close this?

**Comment by bfred-it** [comment] 2017-07-26 01:54
Reopen if this is still an issue even after #567

**Closed by bfred-it** 2017-07-26 01:54 UTC
Labels: bug

**Comment by Logerfo** [comment] 2019-05-28 19:27
@bfred-it it is an issue for me as for today. It also makes me very disappointed that there are an uncountable number of feature that I can disable, but this is not one.

**Comment by bfred-it** [comment] 2019-05-29 02:31
This is one of them, it’s part of the keyboard shortcuts. 

The only feature you can’t disable are CSS-only ones, and even some of those still have JS switches to be disableable.

**Comment by Logerfo** [comment] 2019-05-29 12:24
If someone is facing the same problem and want to disable it, the feature is called `comment-fields-keyboard-shortcuts`, thank you @bfred-it for the insight.

**Comment by fabiospampinato** [comment] 2019-06-13 00:02
> Reopen if this is still an issue even after #567

This is still absolutely the case, when selecting an emoji from the popover with tab extra whitespaces are inserted for me.

**Comment by bfred-it** [comment] 2019-06-13 01:21
Refer to https://github.com/sindresorhus/refined-github/issues/2148
