### ISSUE TITLE
`link-to-file-in-file-history` breaks when branches contain slashes

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#4271] opened 2021-04-23 13:15 UTC
The issue from #2692 started appearing again and can be observed in the same way (quote from #2692):
> Bug appears on this page: https://github.com/Cog-Creators/Red-DiscordBot/commits/V3/develop/docs/install_linux_mac.rst
>
> Clicking any of "See object at this point in history" buttons redirects to 404 page.

**Comment by jack1142** [comment] 2021-04-23 13:16
It appears that there's another feature that has a similar problem though I'm not sure what it's called and it's not *that* important anyway since it's just visual:
![image](https://user-images.githubusercontent.com/6032823/115876652-e2858800-a446-11eb-837d-e0ebc2671594.png)

**Comment by yakov116** [comment] 2021-04-23 13:30
Duplicate of #4196

**Comment by fregante** [comment] 2021-04-24 09:27
Should be fixed by https://github.com/sindresorhus/refined-github/pull/4187/files#diff-10ea2ac1855ba73fe69bd22a445847d89960717eef20641fb46c5ddaab234ee8

**Closed** 2021-04-29 13:11 UTC
Labels: bug
