### ISSUE TITLE
Minor layout break on PR Toolbar for PRs w/ long name

### ISSUE THREAD

**Issue by filipewl** [sindresorhus/refined-github#2395] opened 2019-09-02 13:22 UTC
Just noticed that the layout for the sticky PR's toolbar in the PR's **Files changed** tab seems to break when the PR has a long name.

|Refined GH|GH|
|-|-|
|[![XXrO25rvU9](https://user-images.githubusercontent.com/381395/64116668-59997480-cd69-11e9-8071-9cc12df457f0.gif)](https://github.com/sindresorhus/refined-github/pull/2387/files)|[![QquaTzxGYL](https://user-images.githubusercontent.com/381395/64116653-4ededf80-cd69-11e9-86a0-46c45bf42dfb.gif)](https://github.com/sindresorhus/refined-github/pull/2387/files)|

PRs with short names don't seem to be affected:
[<img width="1003" alt="Screen Shot 2019-09-02 at 10 07 40" src="https://user-images.githubusercontent.com/381395/64116750-89e11300-cd69-11e9-8c24-96dabb60dde0.png">](https://github.com/sindresorhus/refined-github/pull/2310/files)

Link to a PR with this behavior: https://github.com/sindresorhus/refined-github/pull/2387/files.

---

A possible solution is to remove the left margin for this element:
![M1EcLbbyrO](https://user-images.githubusercontent.com/381395/64117329-412a5980-cd6b-11e9-86d0-6464bba6bb2e.gif)

I'll see if I can come up with a PR for this.

**Comment by busches** [comment] 2019-09-02 14:43
PR welcome, duplicate of #2291.

**Closed by busches** 2019-09-02 14:43 UTC
Labels: bug
