### ISSUE TITLE
Doesn't show changes to line endings when comparing

### ISSUE THREAD

**Issue by veqryn** [sindresorhus/refined-github#3463] opened 2020-08-15 09:56 UTC
I searched out and installed refined github because I had several PR's that show every line in a file is changing due to differences in the line endings (LF vs CRLF).
The only problem is that github doesn't show what the old line ending was or what the new one was (ie: are we going from CRLF to LF, or from LF to CRLF?).
Your extension says it shows whitespace differences, but it doesn't appear to show line ending differences:
![image](https://user-images.githubusercontent.com/1897829/90310033-fdacfa80-deaa-11ea-931d-5e8508a3e135.png)
I think when the line endings differ, it should have the option to show which line endings are being used.

**Comment by fregante** [comment] 2020-08-15 14:59
Duplicate of #3121

**Closed by fregante** 2020-08-15 14:59 UTC
Labels: bug
