### ISSUE TITLE
Prevent accidental leave of a new issue creation page with losing content

### ISSUE THREAD

**Issue by leventov** [sindresorhus/refined-github#2523] opened 2019-11-07 10:41 UTC
It would be nice to pop a modal dialog (window, prompt) when writing a new issue and leaving the page inadvertently (e. g. by clicking on one of those "similar issues"). This may lead to losing the issue comment (it's probably supposed to be saved in local storage by Github, but it definitely fails to be saved sometimes).

Example URL:
https://github.com/sindresorhus/refined-github/issues/new

**Comment by fregante** [comment] 2019-11-10 17:47
I just tried even disabling JavaScript completely and the content of the comment field is stored by the browser, no JavaScript required. Even if you close the tab and reopen it. Heck even if you close the browser and reopen it I think.

**Comment by yakov116** [comment] 2019-11-10 17:49
@fregante known Firefox bug

**Comment by fregante** [comment] 2019-11-12 14:09
I use Firefox

**Comment by fregante** [comment] 2019-11-12 14:12
Duplicate of https://github.com/sindresorhus/refined-github/issues/1598

**Closed by fregante** 2019-11-12 14:12 UTC
Labels: enhancement, under discussion

**Comment by leventov** [comment] 2019-11-12 14:35
@fregante I would not say this issue is a duplicate of #1598. As people mentioned in comments to that issue, there are already built-in support for this in Chrome, but it's **unreliable**, and so will likely be Refined Github's solution. Instead of allowing for a mistake and then reverting it (maybe; maybe not) I think it's better to prevent mistake in the first place with a prompt.

**Comment by fregante** [comment] 2019-11-12 16:00
That issue is not about a prompt. The prompt suggestion issue was closed
