### ISSUE TITLE
Milestone info is hidden in Chrome/MS Edge

### ISSUE THREAD

**Issue by RussKie** [sindresorhus/refined-github#2958] opened 2020-03-31 01:00 UTC
Extension: version 20.3.22
Chrome: version 80.0.3987.149 (Official Build) (64-bit)
MS Edge: version 80.0.361.69 (Official build) (64-bit)

Verified on both browsers by disabling all extensions I had and gradually enabling them one by one until I zeroed in on the extension.

Without the extension the milestone information is rendered correctly:
![image](https://user-images.githubusercontent.com/4403806/77975791-c9df9700-7346-11ea-9838-fa914558325e.png)

With the extension enabled the information is missing:
![image](https://user-images.githubusercontent.com/4403806/77975824-e4b20b80-7346-11ea-8c0a-b26c14de3e4b.png)

**Comment by yakov116** [comment] 2020-03-31 01:04
Duplicate of #2924

Need to wait for chrome to update

**Closed** 2020-03-31 01:27 UTC
Labels: bug

**Comment by RussKie** [comment] 2020-03-31 01:29
Sorry, couldn't find that issue.
