### ISSUE TITLE
Breaks GitHub's new Custom Notifications UI

### ISSUE THREAD

**Issue by rafegoldberg** [sindresorhus/refined-github#3745] opened 2020-11-20 16:54 UTC
<img align=right src=https://user-images.githubusercontent.com/886627/99826391-23324b80-2b0d-11eb-9ce9-8b77bc3f918d.png>

I've tested this with the extension both on and off, and it definitely seems to be due to Refined GitHub! To replicate, try clicking the new Custom option from any repo's Watch dropdown.

- **Current Behavior**:
  With the extension on, the customization panel does open _very_ briefly, but then the Watch dropdown automatically closes itself...
- **Expected Behavior**:
  A secondary customization panel (pictured) should slide, and _stay,_ open!

**Comment by yakov116** [comment] 2020-11-20 17:03
Duplicate of #3742

**Closed by yakov116** 2020-11-20 17:03 UTC
Labels: bug

**Comment by fregante** [comment] 2020-11-20 17:36
Thanks for reporting @rafegoldberg, this was temporarily fixed by @yakov116 earlier. It should no longer happen when you refresh the page.
