### ISSUE TITLE
Cannot set personal access token in firefox options

### ISSUE THREAD

**Issue by Marr11317** [sindresorhus/refined-github#3635] opened 2020-10-09 00:17 UTC
I just installed the firefox add, but get a blank screen when I try to edit any of the options: 
![1](https://user-images.githubusercontent.com/35939574/95527379-203b2b80-09a3-11eb-9d70-57fbf61dfbcc.gif)

I would assume a bug report was already submitted for that, but I couldn't find it. Anyway, it works on chromium-based browsers.

**Comment by fregante** [comment] 2020-10-09 00:32
Duplicate of https://github.com/sindresorhus/refined-github/issues/3506

**Closed by fregante** 2020-10-09 00:32 UTC
Labels: bug

**Comment by fregante** [comment] 2020-10-09 00:33
Can you try opening this page when the extension is enabled? How does it look?

```
moz-extension://a262b5a5-f7cc-ae4c-8af1-b27ad5ee0e9e/options.html
```
