### ISSUE TITLE
hide_empty_meta: Uncaught (in promise) TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by sompylasar** [sindresorhus/refined-github#900] opened 2017-12-21 23:28 UTC
```
Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at hide_empty_meta (content.js:1736)
    at enableFeature (content.js:806)
    at <anonymous>
```
```js
  var hide_empty_meta = function() {
    if (isRepoRoot()) {
      const meta = select_dom_default()(".repository-meta");
      if (select_dom_default.a.exists("em", meta) && !select_dom_default.a.exists(".js-edit-repo-meta-button")) {
        meta.style.display = "none";   // <<<<<<<<<<< HERE <<<<<<<<<<<<<<
      }
    }
  };
```

**Comment by bfred-it** [comment] 2017-12-22 01:09
What page did you see this on?

**Comment by sompylasar** [comment] 2017-12-22 01:15
@bfred-it This was on a private repo, but I reproduced here: https://github.com/sindresorhus/refined-github/tree/faster-reviews?files=1

**Comment by bfred-it** [comment] 2017-12-22 02:46
Essentially a duplicate of #901 (same issue/solution)

**Closed** 2018-05-25 12:37 UTC
Labels: bug
