### ISSUE TITLE
The 'Review changes' dropdown does not work anymore

### ISSUE THREAD

**Issue by votdev** [sindresorhus/refined-github#1808] opened 2019-02-22 13:07 UTC
![peek 2019-02-22 14-04](https://user-images.githubusercontent.com/1897962/53244386-056f5280-36ab-11e9-9ba2-a6d7e48858c4.gif)

Chromium Version 71.0.3578.98 (Offizieller Build) Built on Ubuntu , running on Ubuntu 18.04 (64-Bit)
Firefox 65.0 (64-Bit)

After disabling the plugin everything works normal.

**Comment by busches** [comment] 2019-02-22 13:22
Duplicate of #1805.

**Closed by busches** 2019-02-22 13:22 UTC
Labels: bug
