### ISSUE TITLE
Starring a repo isn't available on the newsfeed

### ISSUE THREAD

**Issue by HemantPawar** [sindresorhus/refined-github#3611] opened 2020-10-02 18:36 UTC
Is this feature intentional? I couldn't find a relevant setting in the extension options to enable starring on the [homepage](https://github.com/).

This is how newsfeed looks without Refined GitHub.

![image](https://user-images.githubusercontent.com/471327/94957477-70ca0900-050b-11eb-9e9f-56e8b327b898.png)

Starring a repo is not visible after installing the extension.

![image](https://user-images.githubusercontent.com/471327/94957676-c7cfde00-050b-11eb-8714-b60d8e814223.png)

**Comment by sindresorhus** [comment] 2020-10-02 18:56
Why would you star stuff without actually checking out the repo?

**Comment by fregante** [comment] 2020-10-02 19:07
Duplicate of https://github.com/sindresorhus/refined-github/issues/1864

**Closed by fregante** 2020-10-02 19:07 UTC
Labels: bug

**Comment by HemantPawar** [comment] 2020-10-03 08:38
My bad. I tried searching for a similar issue before creating a new one. But by default, Github issue search only searches open issues. I'll keep this thing in mind from now on before creating an issue.

Actually, I was starring from the newsfeed itself as I was building some stuff related to starring. But I agree someone wouldn't do it normally without checking the repo.

I'm sorry but is there any way to highlight the star icon of the star counter of already starred repo using Custom CSS? Something like this.

![image](https://user-images.githubusercontent.com/471327/94987119-68acb080-0581-11eb-9929-46b327551204.png)

**Comment by fregante** [comment] 2020-10-03 10:38
> I tried searching for a similar issue before creating a new one

No worries, we're not upset for duplicate issues, it's not easy to find them.
