### ISSUE TITLE
`Update branch` button is misaligned on a draft PR

### ISSUE THREAD

**Issue by trollixx** [sindresorhus/refined-github#3017] opened 2020-04-19 16:05 UTC
Noticed a misaligned `Update branch` button on my draft PR. The button is not there at all with the extension disabled. I am about to update the PR, hence no link, but here's a screenshot:

![image](https://user-images.githubusercontent.com/714940/79692880-a1f09e80-8235-11ea-9e05-c15d8255b53f.png)

**Comment by yakov116** [comment] 2020-04-19 16:07
I think #2723 should take care of this too.

**Comment by fregante** [comment] 2020-04-19 19:53
Duplicate of #2723

**Closed** 2020-05-30 15:27 UTC
Labels: bug
