### ISSUE TITLE
"Edit comment" button is only injected for a first post

### ISSUE THREAD

**Issue by nashbridges** [sindresorhus/refined-github#3632] opened 2020-10-08 13:04 UTC
After recent changes (https://github.com/sindresorhus/refined-github/pull/3407 ?) the "Edit" button is only visible for initial post. This is like that after initial page loading (no interaction with it):

#### First post

![image](https://user-images.githubusercontent.com/380913/95461914-74341900-097f-11eb-8cdc-36b09ee55acb.png)

#### Second and other posts

![image](https://user-images.githubusercontent.com/380913/95461943-80b87180-097f-11eb-94d7-25e08160d5ff.png)

I've tried to reload the page a couple of times with "Disable cache" checkbox enabled in devtools.

**Comment by fregante** [comment] 2020-10-08 17:09
Duplicate of https://github.com/sindresorhus/refined-github/issues/3279

**Closed by fregante** 2020-10-08 17:09 UTC
Labels: bug

**Comment by nashbridges** [comment] 2020-10-08 17:38
Sorry if I created an extra report 😳 
I confirm that everything is OK now. Thank you for your work!
