### ISSUE TITLE
Unable to see destination branch

### ISSUE THREAD

**Issue by netniV** [sindresorhus/refined-github#3590] opened 2020-09-23 00:36 UTC
I was looking at a few Pull Requests and I couldn't figure out which branch they were being merged into as we use several versions concurrently.  When I tried it incognito without Refined GitHub, I could see it OK.  Tried to search past issues, but I haven't found this one so I do apologise if this has already been raised/addressed:

![image](https://user-images.githubusercontent.com/9052188/93951050-2f806f00-fd3d-11ea-8a39-728bc5691261.png)

**Comment by fregante** [comment] 2020-09-23 00:56
If you contribute once to a repository, you know what the default branch is and it's redundant information in every PR.

It's a feature: https://github.com/sindresorhus/refined-github/issues/3089
If you don't like it, you can disable `clean-conversation-headers`

**Comment by yakov116** [comment] 2020-09-23 00:57
The feature is called `clean-conversation-headers` you can disable it in the extention options.

>Because the vast majority of PRs are towards the default branch, so that information is useless in most cases: https://github.com/sindresorhus/refined-github/issues/3089

>`clean-conversation-headers` will instead **highlight** the branch when it's not towards the default branch: https://github.com/sindresorhus/refined-github/pull/3480

>So the feature serves 2 purposes: reduces noise while making _the signal_ clearer.

_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/issues/3508#issuecomment-682212664_

**Comment by fregante** [comment] 2020-09-23 00:57
@yakov116 HA! Beat you by 14 seconds

**Comment by fregante** [comment] 2020-09-23 00:57
Duplicate of https://github.com/sindresorhus/refined-github/issues/3508

**Closed by fregante** 2020-09-23 00:56 UTC
Labels: bug

**Comment by netniV** [comment] 2020-10-09 16:27
Thanks guys, I ended up using a browser without the extension to check them, but I will now remove that option.

**Comment by netniV** [comment] 2020-10-09 16:29
One thing I will say is that the description doesn't quite match what you say... 
![image](https://user-images.githubusercontent.com/9052188/95608340-e1fe4480-0a54-11eb-9c21-76f31677ce79.png)

It's not a duplicate set of information given the branches are different.

**Comment by fregante** [comment] 2021-03-03 19:27
The description has been updated to include some of those keywords 👌
