### ISSUE TITLE
Reference an issue including the title

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [sindresorhus/refined-github#3400] opened 2020-07-25 10:09 UTC
Hi there,

since I'm working with Azure DevOps and GitHub simultaneously I'm clearly missing the issue title in referenced issue links. 

It looks like this in Azure DevOps:

![image](https://user-images.githubusercontent.com/12170676/88454346-40148600-ce6f-11ea-8cee-53ea38f27177.png)

Would be nice to have this on GitHub also.

Some links where people requested this feature also:

https://github.com/isaacs/github/issues/1020
https://stackoverflow.com/questions/31451587/is-there-a-way-to-reference-an-issue-including-title-on-github

What to you say?

So lonG
Daniel

**Comment by fregante** [comment] 2020-07-25 11:32
Duplicate of https://github.com/sindresorhus/refined-github/issues/1867

**Comment by fregante** [comment] 2020-07-25 11:34
There’s a good chance that there’s a userscript or extension that does this already. If not, I’m sure it would have interest from many

**Closed by fregante** 2020-07-25 11:34 UTC
Labels: enhancement, under discussion
