### ISSUE TITLE
First character is hidden in split review view

### ISSUE THREAD

**Issue by tamalsaha** [sindresorhus/refined-github#1455] opened 2018-07-31 00:42 UTC
I noticed in the last day that if the extension is enabled on Chrome (Ubuntu 18.04, Version 68.0.3440.75 (Official Build) (64-bit)), the first character is blocked from view. See here:

![rgh](https://user-images.githubusercontent.com/94814/43430812-aca6aa8c-941f-11e8-9e68-99ba1e46e108.png)

It should look like this (with extension disabled):
![rgh-dis](https://user-images.githubusercontent.com/94814/43430847-d56aeb18-941f-11e8-8b05-647e96f9b3ae.png)

**Comment by yakov116** [comment] 2018-07-31 01:02
@tamalsaha please update your extention.

Also Please search the issues before opening a new one. There are about 7 of them opened in the last 48hrs

**Comment by busches** [comment] 2018-07-31 02:19
Duplicate of #1444, which is now fixed and should be rolling out to the Chrome store soon. For now you can disable `remove-diff-signs`.

**Closed by busches** 2018-07-31 02:19 UTC

**Comment by tamalsaha** [comment] 2018-08-03 00:56
Sorry @yakov116 :pray: . 

Thanks for the quick fix.
