### ISSUE TITLE
"Automatically delete the branch right after merging a PR, if possible" should be optional

### ISSUE THREAD

**Issue by jimklimov** [sindresorhus/refined-github#3636] opened 2020-10-09 09:22 UTC
After installing the browser plugin, the GitHub Web-GUI no longer offers a checkbox to delete original branches of PRs but just kills them off (and then I can "Undo" the action). For many workflows it makes sense, however for some of ours it does not. Can this feature be changed to showing the checkbox like original GitHub does, just perhaps pre-ticking it to keep Refined GitHub's default behavior expected by its long-time users?

I got a bit lost in the long list of options I can configure for the extension in my browser, so not sure if there is a setting for this behavior already, or if the branch deletion is currently hardcoded.

Thanks a lot for the nifty extension :)

**Comment by jimklimov** [comment] 2020-10-09 09:39
Upon some more poring into the extension options, there is a "pr-branch-auto-delete" toggle so at least that is configurable (at least a reference from README about the feature is an easy fix that would help those in my shoes).

**Comment by fregante** [comment] 2020-10-09 16:15
Duplicate of https://github.com/sindresorhus/refined-github/issues/2267

**Closed by fregante** 2020-10-09 16:15 UTC
Labels: change request
