### ISSUE TITLE
Emoji reactions overflowed 

### ISSUE THREAD

**Issue by HangYang** [sindresorhus/refined-github#2144] opened 2019-06-10 05:20 UTC
The emoji reactions got overflowed if a comment has too many reactions
URL to check the bug:
https://github.com/vuejs/rfcs/pull/42

<img width="976" alt="Screen Shot 2019-06-10 at 13 12 33" src="https://user-images.githubusercontent.com/3389447/59174001-09ec4800-8b82-11e9-98df-3927c7ee598c.png">

wanted to add a `flex-wrapper: wrap;` to fix it, but I saw in the code you added the rule to avoid wrapping, so just post the bug.
```
/* Avoid wrapping */
.has-reactions,
.rgh-reactions-near-limit {
	display: flex;
}
```

**Comment by bfred-it** [comment] 2019-06-11 15:42
Duplicate of #1744

**Closed by bfred-it** 2019-06-11 15:42 UTC
Labels: bug
