### ISSUE TITLE
Misaligned diff view with tabs

### ISSUE THREAD

**Issue by fjeremic** [sindresorhus/refined-github#2085] opened 2019-05-27 15:47 UTC
When mixing tabs and spaces within a GitHub diff view Refined GitHub seems to screw up the indentation to make it look like there is a formatting issue when there is actually not. The issue can be seen in [1] and the raw diff in [2] where we can see there is no formatting issue. I've attached screenshots with Refined GitHub enabled and disabled.

[1] https://github.com/eclipse/omr/commit/75c09985f5d5dd6cfd7c9d1e4f4d56e9406a45c4#diff-3990e65f3237ed46d278a1a8aefbaeeaR389
[2] https://raw.githubusercontent.com/eclipse/omr/75c09985f5d5dd6cfd7c9d1e4f4d56e9406a45c4/port/common/j9nls.c

## Refined GitHub enabled
![image](https://user-images.githubusercontent.com/16259104/58429688-ac7dd480-8074-11e9-93ee-02a83a5c56ff.png)

## Refined GitHub disabled
![image](https://user-images.githubusercontent.com/16259104/58429821-1b5b2d80-8075-11e9-8cf9-c6cb3f2ee52f.png)

**Comment by bfred-it** [comment] 2019-05-27 16:40
cc @notlmn 

<img width="" alt="" src="https://user-images.githubusercontent.com/1402241/58431384-036cc380-80e0-11e9-8525-14cb978e578e.png">

From what I'm seeing, the count and size is correct, but `text-indent` isn't behaving the way we want; it looks like it's still trying to follow the tabulation.

On that line, after the feature has run, try changing `line-indent` to -61px... and then to -62px. It will jump more than 1px:

![1px text-indent](https://user-images.githubusercontent.com/1402241/58431601-2055c680-80e1-11e9-8bc4-9e800f8e22ff.gif)

**Comment by notlmn** [comment] 2019-05-28 03:36
I'm not seeing this. Not in commit, review, different diff views in PR files. It's all fine for me everywhere.

![image](https://user-images.githubusercontent.com/37769974/58447382-cc1f0680-8121-11e9-8036-18536955a299.png)

------------------------

> On that line, after the feature has run, try changing `text-indent` to -61px... and then to -62px.

For me the `text-indent` value is `-59.3789px` on a Windows machine running in Chrome 74.0.3729.169 with Consolas at 12px;

I'm not sure why you'd want to change it after the feature has run. And it looks fine in your first screenshot too (with white-spaces enabled).

![image](https://user-images.githubusercontent.com/37769974/58447753-1654b780-8123-11e9-875b-fa490ab24d8b.png)

-----------------------

@fjeremic Which version of RGH are you on. I'm testing https://github.com/sindresorhus/refined-github/tree/19.5.27.1925 manually loading the extension because for some reason RGH on Chrome Web Store is locked to 19.5.22.1921 for me.

**Comment by bfred-it** [comment] 2019-05-28 03:38
> I'm not sure why you'd want to change it after the feature has run

To show what’s happening

**Comment by notlmn** [comment] 2019-05-28 08:03
> > I'm not sure why you'd want to change it after the feature has run
> 
> To show what’s happening

Sorry if I sounded over cautious, what I meant was that `text-indent` wouldn't change once it is set by the feature.

**Comment by bfred-it** [comment] 2019-05-28 08:14
> Sorry if I sounded over cautious, what I meant was that `text-indent` wouldn't change once it is set by the feature.

Nobody is saying that, the gif is only to show that the `tab` is interacting with the `text-indent`, probably depending on the font/OS

**Comment by lode** [comment] 2019-05-28 09:27
I'm seeing the same. A diff in a docblock shows misaligned whitespace, even if the whitespace didn't change.

Also, don't know if it is related, but lines which extend beyond the viewport of the diff are wrapped.

(I'm sorry I don't have a public PR to make a screenshot of.)

Happens to me on FF Ubuntu.

**Comment by notlmn** [comment] 2019-05-28 09:45
I managed to isolate this issue to what might be a possible text rendering bug in Firefox.

The second line in the comment has a similar `padding-left` and `text-indent` values, that should cancel each other out and the line shouldn't move.

| Firefox | Chrome |
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/37769974/58467882-18863880-815a-11e9-96dd-f8c2317722fe.png) | ![image](https://user-images.githubusercontent.com/37769974/58468146-a530f680-815a-11e9-8629-76343589a3f0.png) |

The mixed white-spaces on the second line is probably making Firefox go crazy. I might be wrong but one would expect for this to work as intended, where the tab characters don't collapse in mixed indentation.

-------------------

Isolated bin: https://jsbin.com/jelomov/edit?html,css,output.

In the bin above, all the `*` characters should be aligned.

| Firefox | Chrome |
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/37769974/58468514-4e77ec80-815b-11e9-9bf0-baf14635b258.png) | ![image](https://user-images.githubusercontent.com/37769974/58468249-d5789500-815a-11e9-87fc-059ac8ee5edd.png) |

**Comment by notlmn** [comment] 2019-05-28 09:48
> I'm seeing the same. A diff in a docblock shows misaligned whitespace, even if the whitespace didn't change.
> 
> Also, don't know if it is related, but lines which extend beyond the viewport of the diff are wrapped.

The misaligned white-space is a real issue. But code beyond viewport _is_ expected to wrap onto the next line, that's intended.

**Comment by bfred-it** [comment] 2019-05-28 09:49
Thanks for looking into this! 🤗

**Comment by notlmn** [comment] 2019-05-28 09:52
One possible quick fix I could find without disabling this feature and not waiting for the browser to fix (if this were a browser issue) is surprisingly #2073, where adding `display: inline-block` to `.pl-ws` in the PR _should_ fix this, forcing browser to not collapse tabs inside mixed indentation.

**Comment by lode** [comment] 2019-05-28 10:03
> But code beyond viewport _is_ expected to wrap onto the next line, that's intended.

<small>Thanks, found `indented-code-wrapping`. I find the previous situation more readable, but I can just disable the feature.</small>

**Comment by bfred-it** [comment] 2019-05-28 10:08
If changing the dom is unavoidable, I'd wrap the whitespace in a span and make it `.sr-only` (invisible), so we don't need the `text-indent` but it's more of a last resort.

**Comment by fjeremic** [comment] 2019-05-28 14:27
> @fjeremic Which version of RGH are you on. I'm testing [`19.5.27.1925`](https://github.com/sindresorhus/refined-github/tree/19.5.27.1925) [](/sindresorhus/refined-github/tree/HEAD@{2019-05-28T03:36:49Z})

I'm on Firefox 66.0.5 running RGH 19.5.27. Thanks everyone for looking into this by the way. RGH is by far my most used add-on.

**Comment by notlmn** [comment] 2019-06-02 01:17
Confirmed as Firefox bug on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1555903#a136463_475400.

(Up vote on Bugzilla for possibly quick fix)

**Comment by jerone** [comment] 2019-06-02 09:42
If I change the following inline css for the [example](https://github.com/eclipse/omr/commit/75c09985f5d5dd6cfd7c9d1e4f4d56e9406a45c4#diff-3990e65f3237ed46d278a1a8aefbaeeaR389) it works for me:

```diff
-padding-left: calc((var(--tab-size, 4) * 2ch) + 1ch) !important;
+padding-left: calc((var(--tab-size, 4) * 2ch) + 0ch) !important;
-text-indent: calc((var(--tab-size, 4) * -2ch) - 1ch) !important;
+text-indent: calc((var(--tab-size, 4) * -2ch) - 0ch) !important;
```

![image](https://user-images.githubusercontent.com/55841/58759508-7be1e300-852b-11e9-9a55-ff74883af78e.png)

**Comment by bfred-it** [comment] 2019-06-02 10:40
That does seem to work, perhaps this needs to be tested further, with more indentation types, e.g.

```
 -> hello
 -> •space
 -> ••spaces
```

To repeat, I'm not interested in making it look ok if the indentation is something meaningless like `• -> `

**Comment by notlmn** [comment] 2019-06-02 10:43
@jerone that's specific for this example, what you did there is similar to ignoring space character count and only counting tab characters (the bug with Firefox). It was already thought of by me before opening #2088, but it failed for other cases.

**Comment by bfred-it** [comment] 2019-06-02 11:02
Can that fix be applied only where it works?

e.g. if space = 1 & lastIndent = space & isFirefox

**Comment by jerone** [comment] 2019-06-02 12:31
Are there more test-cases?

**Comment by notlmn** [comment] 2019-06-02 13:43
> Can that fix be applied only where it works?
> 
> e.g. if space == 1 & lastIndent == space & isFirefox, then spaces = 0

The space count be anything, not just 1, as long as it is **under** the value of `--tab-size`. These additional spaces can be substituted for with an additional tab, this wouldn't affect the overall alignment as long as the specified condition is met.

The advantage with this is that it works in both Chrome and Firefox, so some part of the code can be removed.

But the downside to this is that wrapped text would not be at the same level of the actual line, it [would be where the last tab character ended](https://user-images.githubusercontent.com/37769974/58762078-57a4f700-8569-11e9-81a5-8cdf20794df0.png).  And the major downside is that it only works for code indented with tab, any code indented with completely with spaces end up depending on `--tab-size`, which kind of defeats the purpose of space-indented code (spaces are fixed in length, `--tab-size` affects this length).

---------------------------

> Are there more test-cases?

Yes, like code that is completely indented with spaces where there are no tabs (explained above).

**Comment by sindresorhus** [comment] 2019-06-09 07:27
I can reproduce this in Chrome too: https://github.com/sindresorhus/electron-context-menu/pull/76#discussion_r289699052

<img width="446" alt="Screen Shot 2019-06-09 at 14 26 56" src="https://user-images.githubusercontent.com/170270/59156284-a64f1580-8ac2-11e9-8018-e0915bfd1fce.png">

**Comment by notlmn** [comment] 2019-06-09 11:34
> I can reproduce this in Chrome too: [sindresorhus/electron-context-menu#76 (comment)](https://github.com/sindresorhus/electron-context-menu/pull/76#discussion_r289699052)

That's because GitHub adds some extra negative text indentation for inline wrapped code. Originally spotted in https://github.com/sindresorhus/refined-github/pull/1989#issuecomment-493647728, but was ignored in between other issues. 😅

![image](https://user-images.githubusercontent.com/37769974/59158403-3a2adc80-8ad7-11e9-9596-9639b65c9ac6.png)

-----------------

Unfortunately this ended up being a completely different bug in Chrome rather than in Firefox (see https://bugzilla.mozilla.org/show_bug.cgi?id=1555903#c8).

Will have to try a different solution for this based on https://github.com/sindresorhus/refined-github/issues/2085#issuecomment-498032629, but until then this feature remains in a limbo as we have to wait for https://bugs.chromium.org/p/chromium/issues/detail?id=969616 to be solved. If there were to be a fix (considering Firefox does it right), it has to take Chrome's different layout calculation into consideration as a temporary fix.

Will try to see what I can whip up, and how it behaves in different browsers (event if I have to write a bit of code to calculate tab-stops and work from there).

**Closed** 2019-06-21 08:26 UTC
Labels: bug, help wanted
