### ISSUE TITLE
When extension is enabled, first char of each line of diffs is missing

### ISSUE THREAD

**Issue by EReckase** [sindresorhus/refined-github#1454] opened 2018-07-30 17:57 UTC
Disabled:
![screen shot 2018-07-30 at 11 54 58 am](https://user-images.githubusercontent.com/1120643/43414245-751d0640-93ef-11e8-80b1-0af9d81bb06f.png)

Enabled:
![screen shot 2018-07-30 at 11 56 03 am](https://user-images.githubusercontent.com/1120643/43414274-905a7b54-93ef-11e8-8f44-8b76c679e95d.png)

This is on Chrome, OSX, v 18.7.25.1641.

**Comment by busches** [comment] 2018-07-30 17:59
Duplicate of #1444, which is now fixed and should be rolling out to the Chrome store soon. For now you can disable `remove-diff-signs`.

**Comment by EReckase** [comment] 2018-07-30 17:59
Augh, I swear I looked for a dupe issue. Thanks for your help.

**Closed by busches** 2018-07-30 17:59 UTC
