### ISSUE TITLE
The "No Whitespace" button is gone

### ISSUE THREAD

**Issue by dpashkevich** [sindresorhus/refined-github#2633] opened 2019-12-17 19:16 UTC
Since last week the "No Whitespace" button in Pull Request diffs is no longer there.

Example URL: this very repo: https://github.com/sindresorhus/refined-github/pull/2628/files

Expected:
![image](https://user-images.githubusercontent.com/1157741/71026661-b120dd80-20d7-11ea-86ef-761401d3dfb8.png)

Actual:
![image](https://user-images.githubusercontent.com/1157741/71026756-d9104100-20d7-11ea-8a82-604bb7fa6bff.png)

Seeing these console errors for other features, may or may not be related:
![image](https://user-images.githubusercontent.com/1157741/71026650-a9613900-20d7-11ea-9d6f-10c9ec1c033c.png)

Happy to do more debugging if you point me in the right direction

**Comment by dpashkevich** [comment] 2019-12-17 19:17
I also don't see a toggle between unified and side by side diffs

**Comment by fregante** [comment] 2019-12-17 19:26
It was disabled in PRs due to a breaking bug: https://github.com/sindresorhus/refined-github/issues/2291

**Comment by fregante** [comment] 2019-12-17 19:27
Duplicate of https://github.com/sindresorhus/refined-github/issues/2597

**Closed by fregante** 2019-12-17 19:27 UTC
Labels: bug
