### ISSUE TITLE
Choose multiple pull request template

### ISSUE THREAD

**Issue by kevinhassan** [sindresorhus/refined-github#3771] opened 2020-11-27 14:31 UTC
Hi ! I would like to choose among pull request templates when creating one. 

I know for only one template Github integrate automatically but not for multiple templates.
Something like dropdown would be amazing 🤩

**Comment by fregante** [comment] 2020-11-27 22:26
Duplicate of #1621

**Closed by fregante** 2020-11-27 22:26 UTC
