### ISSUE TITLE
Create a greasemonkey plugin

### ISSUE THREAD

**Issue by Tasqa** [sindresorhus/refined-github#947] opened 2018-01-04 10:40 UTC
Since this plugin is mostly inserting JS snippets into github pages I think that this can also be done using Greasemonkey. It is already updated to support Firefox Quantum (57+). See: https://www.greasespot.net/2017/09/greasemonkey-4-announcement.html

**Comment by bfred-it** [comment] 2018-01-04 11:45
Duplicate of https://github.com/sindresorhus/refined-github/issues/654, you can see the discussion there

**Closed by bfred-it** 2018-01-04 11:45 UTC
