### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#2290] opened 2019-07-31 12:12 UTC
```
❌ edit-readme
content.js:2154 TypeError: Cannot read property 'dataset' of null
    at edit_readme_init (content.js:6917)
    at features_run (content.js:2149)
    at content.js:2195
    at content.js:2110
    at onAjaxedPagesRaw (content.js:2105)
```

On any page
```
content.js:2082 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at onNewsfeedLoad (content.js:2082)
```

**Comment by fregante** [comment] 2019-07-31 12:41
- `edit-readme` was fixed by #2278
- can't reproduce the second one. That code only runs on `isDashboard`

**Comment by yakov116** [comment] 2019-07-31 13:06
never mind looks like it was an error on my end

**Comment by notlmn** [comment] 2019-07-31 13:23
> * can't reproduce the second one. That code only runs on `isDashboard`

Can reproduce on issues and PRs on forced reload. That's not related to user dashboard, this issue looks like it's from `show-names`. Specifically `onNewFeedLoad` function used as `load` function for one of `show-names`'s [declaration](https://github.com/sindresorhus/refined-github/blob/1a6850b1d8b088ed568073f3bad9da8f0d3da339/source/features/show-names.tsx#L68-L88) in #2229.

![image](https://user-images.githubusercontent.com/37769974/62214136-0b87fe80-b3c2-11e9-99ef-52ee59df4a3c.png)

This function should not be called on issues/PRs, but somehow it is and fails on https://github.com/sindresorhus/refined-github/blob/bc7d35cda229ea5e282f8cb6f5a62b9e09c1f5a0/source/libs/on-newsfeed-load.ts#L11. Causing `elementReady` on https://github.com/sindresorhus/refined-github/blob/bc7d35cda229ea5e282f8cb6f5a62b9e09c1f5a0/source/libs/on-newsfeed-load.ts#L17 to go into a rAF callback forever. Was experiencing something similar when profiling #2087 (the little callbacks in [this screenshot](https://github.com/sindresorhus/refined-github/pull/2087#issuecomment-515379576) on the either side).

![image](https://user-images.githubusercontent.com/37769974/62214550-e778ed00-b3c2-11e9-9adc-18e12c6a2e62.png)

I suspect this might be the same issue as #2273.

**Comment by yakov116** [comment] 2019-07-31 16:26
@fregante same as above

**Comment by fregante** [comment] 2019-07-31 18:07
Try #2292 

@notlmn those rAFs aren't ours; `elementReady` stops on dom ready.

**Closed** 2019-08-01 05:17 UTC
Labels: bug

**Comment by notlmn** [comment] 2019-08-01 13:36
> @notlmn those rAFs aren't ours; `elementReady` stops on dom ready.

Sorry, found that those are from `hide-files-on-github` extension: https://github.com/sindresorhus/hide-files-on-github/pull/82.
