### ISSUE TITLE
Ability to out-dent text selection.

### ISSUE THREAD

**Issue by itsjamie** [sindresorhus/refined-github#2490] opened 2019-10-15 02:46 UTC
Original GIF: https://user-images.githubusercontent.com/1402241/33802977-beb8497c-ddbf-11e7-899c-698d89298de4.gif

I thought there was a bug where I assumed folks were originally Shift+Tab to outdent the content here and it wasn't working for me, but I assume they were now just Ctrl-Zing after reading other reports. Looked at source, and there is no handling for Shift+Tab. 

It would be really nice honestly to have a paste option standpoint of pasting in code from an editor and you end up with code with leading spaces, to be able to "match" the indentation of the first line for all other lines.

<img width="355" alt="Screenshot 2019-10-14 23 43 55" src="https://user-images.githubusercontent.com/1956521/66795958-9023ec80-eedc-11e9-9922-eef22c7908c3.png">

However, I can see where that would be difficult to "do the right thing", and so having the ability to manually correct this, would be awesome!

```
const tracksList = this.tracks.map((track) => {
          return {
            _id: track.id.toString(),
            label: track.name,
            kind: track.type.toLowerCase(),
            default: track.default
          };
        });
```

**Comment by fregante** [comment] 2019-10-15 12:31
This is has been haphazardly implemented a while ago but I never cleaned it up https://github.com/fregante/indent-textarea/pull/6

**Comment by fregante** [comment] 2019-10-16 09:20
Closing as duplicate of https://github.com/fregante/indent-textarea/issues/1

**Closed** 2019-12-15 16:35 UTC
Labels: enhancement, has PR
