### ISSUE TITLE
"More" overlay constantly open when refined-github is enabled

### ISSUE THREAD

**Issue by mansona** [sindresorhus/refined-github#2383] opened 2019-08-25 20:00 UTC
Hi folks 👋 first of all thanks for a great addon 🎉 

Over the last week I've had this constantly open dropdown under the "more" tab on pretty much all pages on GitHub

<img width="816" alt="Screenshot 2019-08-25 at 20 54 51" src="https://user-images.githubusercontent.com/594890/63655093-2eb48c80-c77b-11e9-838b-739c80556896.png">

that is what it looks like when I visit a page without touching anything. Also clicking the "more" tab doesn't close the dropdown so it's a constant feature of the page 🙈 

I have confirmed that disabling refined-github makes it go away

**Comment by busches** [comment] 2019-08-25 20:17
Duplicate of #2357. Please update the extension.

**Closed by busches** 2019-08-25 20:17 UTC
Labels: bug

**Comment by jdreesen** [comment] 2019-08-25 20:19
Are you using the latest version? Maybe you should take a look at the issue that's visible in your screenshot: `Bug: "More" dropdown always expanded` ;)

**Comment by mansona** [comment] 2019-08-26 08:15
lol I did a search but I didn't see it 🙈 so sorry for the noise. 

I guess Extensions only update on a Chrome restart or something so I was using an old version, oops!
