### ISSUE TITLE
Possible bug with reaction avatars

### ISSUE THREAD

**Issue by kumarharsh** [sindresorhus/refined-github#611] opened 2017-07-11 11:20 UTC
When an issue page is loaded, the people's reaction avatars show up. But as soon as I add my reaction to those, the avatars disappear.

Earlier, I thought this was by design. But recently I realised that this might be a bug due to this scenario;

After adding my reaction, if I subsequently rescind it by clicking the reaction icon again, the avatars become visible again for about half a second, and then disappear. After this, *adding* a reaction starts *showing* the avatars, and *removing* the reaction starts *hiding* them.

Try it with this issue.

**Comment by bfred-it** [comment] 2017-07-11 11:30
Duplicate of https://github.com/sindresorhus/refined-github/issues/233

I'm already working on it :)

**Closed by bfred-it** 2017-07-11 11:30 UTC

**Comment by kumarharsh** [comment] 2017-07-11 11:32
Oh, damn. I did search for reactions, but the issue's subject line was so different from what I expected that I didn't check that issue 🤦‍♂️

**Comment by bfred-it** [comment] 2017-07-11 11:36
No worries, it does sound different :)
