### ISSUE TITLE
PR toolbar overlays background when profile dropdown is showed

### ISSUE THREAD

**Issue by lex111** [sindresorhus/refined-github#1038] opened 2018-01-26 10:58 UTC
![image](https://user-images.githubusercontent.com/4408379/35436685-75c952a0-02a0-11e8-90ce-dc218ed78eeb.png)

**Comment by ramlmn** [comment] 2018-01-26 12:04
Issue added by this commit: https://github.com/sindresorhus/refined-github/commit/03a34f4cb5c3265092eafe1a9c9036a01ef2fd61

*Also happens on other pages like when adding people to a repository*

The issue was also mentioned in the commit comments, and could not be solved back then. Any suggestions are highly accepted.

/cc @sindresorhus @bfred-it @jgierer12 @hkdobrev

**Comment by bfred-it** [comment] 2018-01-26 12:07
Closing this as a duplicate of #994, it’s a z-index issue that can’t be solved without a lot of work.

**Comment by lex111** [comment] 2018-01-26 12:32
In my opinion a bit different things, the problem that you mentioned can be solved simply by setting a larger `z-index`, not 20 as of now, but 40. 

```css
.dropdown-details[open] > summary::before {
	/*... */
	z-index: 40;
}
```

However, this doesn't solve the problem related to the PR toolbar (due to sticky positioning).

**Comment by bfred-it** [comment] 2018-01-26 13:40
The issues talking about different parts of the UI, but it’s the same bug. And you can’t increase the z-index because they don’t stack. You’re welcome to take a stab at it and submit a PR. More context in #995

**Closed** 2018-01-28 07:44 UTC
Labels: bug, duplicate
