### ISSUE TITLE
Copy PR description to "Squash and Merge" commit message

### ISSUE THREAD

**Issue by rcscott** [sindresorhus/refined-github#2103] opened 2019-05-30 18:59 UTC
When using the `Squash and Merge` feature in GitHub, I think would be really useful to copy the PR description and use that as the merge commit message.

Currently, if there are multiple commits in the branch then GitHub uses a list of the commit titles as the default merge commit message. My PR descriptions usually have more details than the commit titles, so I end up manually copying the description into the commit message field.

<img width="796" alt="Screen Shot 2019-05-30 at 2 45 41 PM" src="https://user-images.githubusercontent.com/5572247/58656651-b446ae80-82ea-11e9-8df1-ca0f4709c641.png">

---

#1264 touched on this, but also included changing the merge title. It seems like the negative feedback to that feature request was focused around changing the merge title, so I'm curious if people are supportive of a feature that only changes the commit message functionality.

**Comment by bfred-it** [comment] 2019-05-31 01:23
The title already changed as part of `sync-pr-commit-title` and the other part has been rejected many times

Duplicate of https://github.com/sindresorhus/refined-github/issues/1264

**Closed by bfred-it** 2019-05-31 01:23 UTC
Labels: enhancement, under discussion

**Comment by mrcasals** [comment] 2021-11-26 08:45
I agree with @belm0, could we have this feature? Maybe even have it disabled by default, if you think that's too invasive, but for me it's unexpected that only the PR title is copied. Thanks!

**Comment by dmitry-stepanov-at-cascade** [comment] 2021-12-14 07:38
+1
My team demands that feature too.
Any chance to copy PR description by default or make it configurable?

**Comment by fregante** [comment] 2021-12-14 10:30
> Maybe even have it disabled by default

Refer to: 

- https://github.com/refined-github/refined-github/issues/2960#issuecomment-606765382

However there's a chance that we'll add UI to allow stuff like this 

- https://github.com/refined-github/refined-github/issues/5155

**Comment by edran** [comment] 2022-02-22 11:27
@fregante any chance you would consider reopening this issue? As pointed out by @belm0, the behaviour of `squash-and-merge` is very different from a standard PR merge, and in the current setup we lose information (i.e. the body of a PR) that has roughly the same semantics as the body of a squashed commit.

**Comment by fregante** [comment] 2022-02-22 14:42
> in the current setup we lose information

You can disable the feature.



> any chance you would consider reopening this issue?

https://github.com/refined-github/refined-github/issues/5155 is what you're looking for. There we can make all of these optional
