### ISSUE TITLE
[BUG] `See this view on the default branch` points to non-existing `master`

### ISSUE THREAD

**Issue by webknjaz** [sindresorhus/refined-github#2728] opened 2020-01-22 15:54 UTC
You can observe this here: https://github.com/ansible/pylibssh/blob/devel/README.rst.

The repo default branch is `devel`, `master` doesn't exist. Clicking the button redirects to https://github.com/ansible/pylibssh/blob/master/README.rst with 404.

**Comment by fregante** [comment] 2020-01-22 17:01
Did that repo change branch recently? It works correctly for me, maybe it's just cached: https://github.com/ansible/pylibssh/blob/e3569b2e9446dd05c51ade137040bc7b546cb7e6/README.rst

<img width="357" alt="Screen Shot 2020-01-23 at 00 00 52" src="https://user-images.githubusercontent.com/1402241/72915791-70ba1c80-3d73-11ea-9e83-2c3bd71594aa.png">

**Comment by fregante** [comment] 2020-01-22 17:04
> maybe it's just cached:

Yeah that's it https://github.com/ansible/pylibssh/commit/e3569b2e9446dd05c51ade137040bc7b546cb7e6

**Comment by webknjaz** [comment] 2020-01-22 19:53
> Yeah that's it [ansible/pylibssh@e3569b2](https://github.com/ansible/pylibssh/commit/e3569b2e9446dd05c51ade137040bc7b546cb7e6)

No. That's not it. The repo had `devel` as its main branch from the very beginning. It was just wrong copy-paste when I first added the Travis CI badge there.

**Comment by fregante** [comment] 2020-01-23 07:12
We don’t default to `master`, GitHub tells us via the API or via the DOM. If GitHub tells us `master` then at some point that was the default branch

**Comment by webknjaz** [comment] 2020-01-23 17:08
How can I debug it with DevTools? I've tried inspecting it by sticking debugger in different places but only found out that this func returns master and the implication seems minified so it's hard to put debug inside...

**Comment by fregante** [comment] 2020-01-24 06:34
You can try emptying the cache at the bottom of the options page.

**Comment by webknjaz** [comment] 2020-01-27 23:30
Thanks! Clearing the cache helped. Still have no idea how it got there, though.

**Comment by fregante** [comment] 2020-02-07 07:29
This is kind of weird, for me the link just appeared on a new repo I visited on the root, pointing to the same page. `master` was the right branch, but it should't appear when you're already on master. I cleared the cache and I couldn't reproduce.

**Comment by fregante** [comment] 2020-02-18 11:52
Closing in favor of the above clearer issue

**Closed by fregante** 2020-02-18 11:52 UTC
Labels: bug
