### ISSUE TITLE
remove-diff-signs is not working

### ISSUE THREAD

**Issue by montogeek** [sindresorhus/refined-github#1447] opened 2018-07-27 14:44 UTC
Hello, since yesterday this feature is not working:

Console log:
![image](https://user-images.githubusercontent.com/1002461/43327595-1f0ad12c-91bc-11e8-961c-5a820cd7d799.png)

GitHub diff effect:
![image](https://user-images.githubusercontent.com/1002461/43327618-2e1f168c-91bc-11e8-8f26-65a18c10b2cc.png)

As you can see, when it fails it is stripping the first character.

You could check this PR to see the error https://github.com/webpack/webpack.js.org/pull/2399/files

**Comment by montogeek** [comment] 2018-07-27 14:44
It may be related to the latest GitHub change regarding diff signs.

**Comment by DavidBoike** [comment] 2018-07-27 14:51
Yep, looks like GitHub implemented this feature natively. I added `remove-diff-signs` to my disabled features list and everything works fine.

**Comment by sompylasar** [comment] 2018-07-27 17:39
Duplicate of #1444

**Closed** 2018-07-27 17:47 UTC
