### ISSUE TITLE
`cleanup-repo-filelist-actions`: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by nixel2007** [sindresorhus/refined-github#3864] opened 2021-01-06 09:41 UTC
Tried to disable extension: yes, no error in console if RG is disabled.

URL: https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/context/annotation/CommonAnnotationBeanPostProcessor.java

no screenshot, just console error.

latest Chrome x64, Windows 10 Pro

**Comment by fregante** [comment] 2021-01-06 16:41
Duplicate of https://github.com/sindresorhus/refined-github/issues/3685

**Closed by fregante** 2021-01-06 16:41 UTC
Labels: bug

**Comment by nixel2007** [comment] 2021-01-06 20:28
Oh, sorry, didn't see this is a duplicate :(
