### ISSUE TITLE
`comments-time-machine-links` doesn't work properly with multiple branches

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2903] opened 2020-03-19 21:24 UTC
URL where the bug appears: [the issue you're in right now](https://github.com/sindresorhus/refined-github/issues/2903) (look below for the link with the clock that doesn't work)

Extension uses `HEAD@{2020-03-19T21:24:30Z}` as the revision, which prevents this from working properly when the closest commit to that date is from different branch.

Using `branch_name@{DATETIME}` should work here, i.e. `https://github.com/Cog-Creators/Red-DiscordBot/blob/develop@{2020-03-19T21:24:30Z}/cogs/downloader.py` links the user to proper address.

---

https://github.com/Cog-Creators/Red-DiscordBot/blob/develop/cogs/downloader.py

**Comment by fregante** [comment] 2020-03-19 21:33
Duplicate of https://github.com/sindresorhus/refined-github/issues/1953

**Closed by fregante** 2020-03-19 21:33 UTC
Labels: bug
