### ISSUE TITLE
More-Drop-Down is always open in Vivaldi 2.7.1628.28

### ISSUE THREAD

**Issue by Stelzi79** [sindresorhus/refined-github#2371] opened 2019-08-21 17:55 UTC
The More drop down is always in the "drop down" state. It is not possible to close it with a click on it.

I have tested this behavior in the browsers

* ````Vivaldi 2.7.1628.28 (Official Build) (64-Bit) (Chromium 76.0.3809.110)```` no newer version available => **bugs out**
* ````Microsoft Edge 78.0.250.1 (Official build) canary (64-bit)```` => **correct behavior**
* ````Microsoft Edge Version 78.0.253.0 (Official build) canary (64-bit)```` => **correct behavior**

Both on OS Version ````Windows 10 OS Version 1903 (Build 18362.295)````

1. Disabling reverts it back to default behavior without the More drop down. Disabling the ````more-dropdown```` option reverts it to default behavior of GitHub.
2. It is on every GitHub page where the More drop down is shown.
3. See screenshot of this behavior when I opened this bug report.

![dropdown](https://user-images.githubusercontent.com/969932/63454213-a5cfe500-c44a-11e9-8eeb-5024d5ac3d5b.jpg)

**Comment by yakov116** [comment] 2019-08-21 18:28
@Stelzi79 	please search the issues before opening a new one

**Comment by jerone** [comment] 2019-08-21 18:28
This has been fixed in https://github.com/sindresorhus/refined-github/pull/2359 and a release is available.

**Comment by Stelzi79** [comment] 2019-08-21 18:49
@yakov116 I searched bevor I opened this bug but it didn't showed up in the search (considering it was merged 5 hours before I opened it)

**Comment by yakov116** [comment] 2019-08-21 19:18
![image](https://user-images.githubusercontent.com/16872793/63461573-e87fc600-c426-11e9-965c-10124509f2cc.png)

**Comment by busches** [comment] 2019-08-21 19:35
This is most likely a duplicate of #2357, but if you are running the latest version of the extension released today and still seeing an issue, then something is wrong in Vivaldi. Vivaldi is not officially supported by RGH, so I'm still going to close this. With that said, if you can offer a PR to fix the behavior in Vivaldi and keep it working in others, we're happy to take a look at it.

General reminder, be nice to each other. :)

**Closed by busches** 2019-08-21 19:35 UTC
Labels: bug

**Comment by maniator** [comment] 2020-02-21 17:08
This is happening again and I am not sure what to do as I cannot disable more options...
