### ISSUE TITLE
Checkbox for disabling `wait-for-build` doesn't show up when admin merging

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#3891] opened 2021-01-12 13:44 UTC
I can't really provide you with links, but the repro steps are as follows:
1. Make a PR on a repository that:
    a) has automatic checks (I have some of them be required, but not sure if that's needed to reproduce)
    b) has auto-merge functionality enabled
    c) you have admin powers on.
2. While checks are still running, try admin-merging PR:
![image](https://user-images.githubusercontent.com/6032823/104321767-588f6000-54e4-11eb-8ed6-797f0d67bd0c.png)
![image](https://user-images.githubusercontent.com/6032823/104321496-fa627d00-54e3-11eb-9113-244764c6a401.png)
![image](https://user-images.githubusercontent.com/6032823/104321521-04847b80-54e4-11eb-8a26-4e993f9ab042.png)
3. See that merging takes a long time and notice that it gets merged *once* checks pass.

There are two things that you can notice on the screenshots above:
a) due to auto-merge enabled, the UI looks different; for comparison, here's the same PR with auto-merge disabled:
![image](https://user-images.githubusercontent.com/6032823/104321934-912f3980-54e4-11eb-9b2c-f8b43a703050.png)
![image](https://user-images.githubusercontent.com/6032823/104321976-9db39200-54e4-11eb-9c00-56ab1da0a8d8.png)
b) as said in the title, there's no checkbox for disabling the `wait-for-build`

**Comment by fregante** [comment] 2021-01-12 20:14
Duplicate of https://github.com/sindresorhus/refined-github/issues/3887

**Closed** 2021-01-12 20:15 UTC
Labels: bug
