### ISSUE TITLE
Add feature: Copy branch name in PR-View

### ISSUE THREAD

**Issue by StephanHoyer** [sindresorhus/refined-github#1498] opened 2018-08-29 09:02 UTC
Would be cool to have a copy-button behind the branch-name for easy checkout in the console.

**Comment by salmanulfarzy** [comment] 2018-08-29 09:14
See #77 #78 #1364

**Comment by sindresorhus** [comment] 2018-11-07 08:31
Duplicate of #77

**Closed by sindresorhus** 2018-11-07 08:31 UTC
