### ISSUE TITLE
Display confirmation box when closing an issue with a comment

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/refined-github#3884] opened 2021-01-10 13:58 UTC
Useful to avoid accidentally closing issues.

Should be applied for all issue pages: `https://github.com/*/*/issues/*`

Should be triggered when clicking this button:

![Close with comment](https://user-images.githubusercontent.com/29491356/104139795-af2c6980-5412-11eb-9a43-b7e3222dfde3.png)

**Comment by yakov116** [comment] 2021-01-10 14:55
Don't we already put the close button on the other side to avoid this issue?

**Comment by fregante** [comment] 2021-01-10 22:39
Duplicate of https://github.com/sindresorhus/refined-github/issues/1037

**Comment by Richienb** [comment] 2021-01-11 00:40
@fregante Sorry for the ambiguity, I actually meant this button:

![image](https://user-images.githubusercontent.com/29491356/104139785-98861280-5412-11eb-9dd7-d6f1f822d758.png)

**Comment by fregante** [comment] 2021-01-11 01:48
Sorry I had completely misunderstood. I thought "Closing a tab before submitting a comment"

**Comment by fregante** [comment] 2021-01-11 01:58
> Should be triggered when clicking this button:
> 
> ![Close with comment](https://user-images.githubusercontent.com/29491356/104139795-af2c6980-5412-11eb-9a43-b7e3222dfde3.png)

I did this accidentally a few times, but I don't know if I'd find the confirmation less annoying than just reopening the issue 🤔 

> Don't we already put the close button on the other side to avoid this issue?

Yes: https://github.com/sindresorhus/refined-github/blob/382b398cbaccbb5a3f7135cf873f1302daf5901e/source/features/safer-destructive-actions.css

**Comment by Richienb** [comment] 2021-01-11 02:01
Perhaps, instead, there should be a 2-second countdown that allows you to immediately cancel the action.

**Comment by fregante** [comment] 2021-01-12 03:26
Given the non-destructiveness of the action I don't think it's worth messing with that. That button already has enough logic behind it (and more is coming with #3881)

**Comment by fregante** [comment] 2021-04-27 12:14
As annoying as it is (honestly, just a little), I think having to confirm your action even when you want to close it actually makes it worse.

Now:

- intentional: 1 click
- unintentional: 2 clicks

With a confirmation

- intentional: 2 clicks
- unintentional: 2 clicks

🤷‍♂️

**Closed by fregante** 2021-04-27 12:14 UTC
Labels: enhancement, under discussion

**Comment by sgreene570** [comment] 2022-11-03 18:54
In some cases, closing an issue accidentally can have unintended consequences, such as triggering (the start or end of) different github actions. It can also lead to confusion among PR reviewers, especially if GH events are pushed t some external source (slack channels, etc).

@fregante would it be possible to re-open this issue?
