### ISSUE TITLE
Layout issues in "Show changes since last view" view

### ISSUE THREAD

**Issue by wearhere** [sindresorhus/refined-github#2296] opened 2019-08-01 20:19 UTC
With RGH:
![image](https://user-images.githubusercontent.com/110000/62324368-345dd180-b45e-11e9-8252-8c0392718ecc.png)

Without:
![image](https://user-images.githubusercontent.com/110000/62324408-4e97af80-b45e-11e9-8237-9458713cf328.png)

Issues (highlighted boxes above):

1. the Files header has broken to two lines
2. the first file's header has broken to three lines

### Repro

I think that this only happens when you've selected "Show changes since your last review"
![image](https://user-images.githubusercontent.com/110000/62324432-5b1c0800-b45e-11e9-880e-8becc122bfbe.png)

and mayyybe when the top file in that view is showing "Changed since last view".

I can't get it to happen when I've selected all commits, individual commits, nor commit ranges within the PR.

### Speculating on causes

I'm a bit mystified as to issue 2 above, but issue 1 seems caused by RGH adding these two buttons
![image](https://user-images.githubusercontent.com/110000/62324623-c960ca80-b45e-11e9-9809-17c3bf7379b9.png)
which probably don't have room when "Clear filters" is visible as it is when you have selected "Show changes since your last review".

**Comment by busches** [comment] 2019-08-01 22:29
Duplicate of #2291.

**Closed by busches** 2019-08-01 22:29 UTC
Labels: bug
