### ISSUE TITLE
Add stargazers-you-know from friendly-github

### ISSUE THREAD

**Issue by NightMachinary** [sindresorhus/refined-github#3142] opened 2020-05-26 11:31 UTC
If you think it's intrusive, just make it disabled by default.

https://github.com/Hermanya/friendly-github

**Comment by yakov116** [comment] 2020-05-26 11:47
See https://github.com/sindresorhus/refined-github/pull/1393#issuecomment-403977822

**Comment by fregante** [comment] 2020-05-26 13:26
Duplicate of https://github.com/sindresorhus/refined-github/pull/1392

**Closed by fregante** 2020-05-26 13:26 UTC
Labels: enhancement, under discussion

**Comment by NightMachinary** [comment] 2020-05-26 14:06
@fregante Have can I use friendly-github without conflict with refined-github?
