### ISSUE TITLE
Repository Creation date is incorrect.

### ISSUE THREAD

**Issue by JesterOrNot** [sindresorhus/refined-github#3340] opened 2020-07-12 01:11 UTC
This project was created a few months ago (I made the repo and I'm not even 19)

URL: https://github.com/JesterOrNot/MathExpression

![image](https://user-images.githubusercontent.com/50386709/87236755-89b29a80-c3b2-11ea-9405-e343a75325c1.png)

**Comment by yakov116** [comment] 2020-07-12 04:58
Dont know what happened there but I get 2 months

![image](https://user-images.githubusercontent.com/16872793/87239231-c7c3b480-c3da-11ea-9c1c-24aa524a1307.png)

**Comment by fregante** [comment] 2020-07-12 13:13
<img width="354" alt="Screen Shot 2020-07-12 at 15 13 28" src="https://user-images.githubusercontent.com/1402241/87247143-427be680-c452-11ea-9238-9dadc7aa277d.png">


Also can't replicate. Firefox

**Comment by fregante** [comment] 2020-07-22 21:44
@yakov116 how do you think we should handle this? Why is the item shown even if the API throws an error?

**Comment by yakov116** [comment] 2020-07-22 22:11
What I **think** is happening they had a very old cache version and when it re-ran without an api key, it went haywire. does that make any sence.

I can try it out later tonight and see if that happens.

I tried it without a token and the feature never runs.

**Comment by yakov116** [comment] 2020-07-23 02:05
@fregante confirmed. I changed it to fetch dom. The issue is that we removed the `shouldRevalidate`. Any one the just updated their refined-github (they did not use it in a while) will have this issue.

![image](https://user-images.githubusercontent.com/16872793/88246007-299bde00-cc67-11ea-8e13-81771a244b11.png)


Add the `should revalidate` back? or just ignore?

**Comment by fregante** [comment] 2020-07-23 10:51
No, we're good, thanks for checking. We merged that update 43 days ago and the cache was set to expire after 30 days anyway, not many will see this unless they just updated RGH.

**Comment by fregante** [comment] 2020-07-23 16:32
The timestamp reported in the cache of https://github.com/sindresorhus/refined-github/issues/3394 is actually in the past (June 18th) but `cache.function` still returns the expired value.
 
Here's what's happening:

1. Expired items are not automatically cleared daily (https://github.com/fregante/webext-storage-cache/issues/7), but if you call `cache.get` you will receive `undefined` and the item will be deleted (✅ )
2. `cache.function` doesn't use this "smart" `cache.get` because the intent is to immediately write a new value if the past one is expired. This skips an unnecessary deletion (✅)
2. The problem is that it does not check whether the item is expired at all, so it returns it and then later _revalidates_ it: (⚠️) https://github.com/fregante/webext-storage-cache/issues/21
3. If the supplied `getter` function throws (like in this case if the token is missing), the _revalidation_ fails and the cache is never updated. (❌)

**Comment by fregante** [comment] 2020-07-23 18:27
I'll reopen this to give visibility to https://github.com/fregante/webext-storage-cache/issues/21

PR welcome

**Comment by rossmacarthur** [comment] 2020-08-09 06:37
Hi on [my repository](https://github.com/rossmacarthur/sheldon) I have a main branch `master` and an orphan branch `gh-pages` where I put built documentation. The repository age value uses the `gh-pages` branch first commit instead of `master`.

This results in a very incorrect repository age calculation. I think it should take into account orphaned branches, or perhaps it should always use the default branch or main branch of the repository, not other branches.

**Comment by fregante** [comment] 2020-08-09 13:03
Indeed, that happens if you visit the secondary branch _first_, so it caches that one.

The feature ended up becoming a bit complex. I think it can be reduced to 2 simple API calls. This one and then what's in `getRepoAge` (merged into a single cached function):


```gql
{
  repository(owner: "sindresorhus", name: "refined-github") {
    defaultBranchRef {
      target {
        oid
        ... on Commit {
          history {
            totalCount
          }
        }
      }
    }
  }
}
```

**Comment by fregante** [comment] 2020-09-09 01:57
Fixed by https://github.com/sindresorhus/refined-github/commit/2dc5f263b97730b82ceee8cb64edc5da76fe5893 and https://github.com/fregante/webext-storage-cache/issues/21

**Closed by fregante** 2020-09-09 01:57 UTC
Labels: Please! ♥︎, bug, good first issue, help wanted
