### ISSUE TITLE
Extend `show-whitespaces` to show mixed line endings

### ISSUE THREAD

**Issue by qaisjp** [sindresorhus/refined-github#3121] opened 2020-05-21 18:37 UTC
It would be good if #2073 could be extended to show CRLF / LF indicators **if the file has mixed line endings**. (Ew!)

It could look like how [bat] shows non-printable characters:

[bat]: https://github.com/sharkdp/bat

![image](https://user-images.githubusercontent.com/923242/82593368-51ed5a80-9b9a-11ea-9f39-13fe3aad2369.png)

(Compare line 10 and line 11. Ignore the rest of the screenshot, this feature proposal is _just_ about line endings. Not other non-printable characters.)

**Why?**

The current `show-whitespaces` feature has been fantastic in stopping tabs appears where they shouldn't (`.editorconfig` helps, but not everyone uses an IDE that supports it).

This feature will stop pesky CRLFs appearing where we don't want them.

**Comment by sindresorhus** [comment] 2020-05-21 18:45
Add a `.gitattributes` file with the following to your repo and you'll never have to deal with CRLF again:

```
* text=auto eol=lf
```

**Comment by qaisjp** [comment] 2020-05-21 18:59
Thanks! Had this applied to [one of](https://github.com/multitheftauto/mtasa-blue/blob/7399bf620b7d5846a87642a4f154d8414a58f4a5/.gitattributes) our repos but not [the other](https://github.com/multitheftauto/mtasa-resources/commit/75dfc69dffebf48bc9766e146487719efc3fa84f).

This solves the problem, so I guess feel free to close this if you think this addition would be bloat, but otherwise I still believe this would be a useful feature (for repos that don't have a `.gitattributes` file).

**Comment by sindresorhus** [comment] 2020-05-21 19:01
If this is accepted, it should be a separate feature.

**Comment by fregante** [comment] 2020-05-21 22:28
Duplicate of https://github.com/sindresorhus/refined-github/issues/2150

**Comment by qaisjp** [comment] 2020-05-21 23:16
As requested here is an example URL: https://github.com/qaisjp/test/pull/31/files

Can't get a "real URL" as that has been forced pushed away

**Comment by notlmn** [comment] 2020-05-22 07:39
Yes, having to take a look at any non-printable characters that might've accidentally crept into your code is a huge improvement ([actual example](https://user-images.githubusercontent.com/37769974/59326917-b0148b00-8d05-11e9-9608-314b1659969b.png).

But this addition creates too much noise in the UI, and there's everything mentioned in https://github.com/sindresorhus/refined-github/issues/2150#issuecomment-501133116.

**Comment by qaisjp** [comment] 2020-05-22 13:40
Yes, I agree my suggestion is a subset of #2150. Other than mine strictly only showing line endings if the line endings are _mixed_. 

I'm happy to close this one and move my suggestion there, if someone wants me to do that.

**Comment by fregante** [comment] 2020-05-23 18:49
Not possible. GitHub filters them out in the HTML.

# Source: ✅
```sh
curl https://raw.githubusercontent.com/qaisjp/test/line-endings-dodgy/middleclass.lua | bat -A
```

<img width="359" alt="" src="https://user-images.githubusercontent.com/1402241/82738281-c8bf5a80-9d36-11ea-9941-89c7fc54b2cf.png">

# HTML ❌
<img width="641" alt="" src="https://user-images.githubusercontent.com/1402241/82738288-d1b02c00-9d36-11ea-9e68-90d8c6ad139b.png">

**Closed by fregante** 2020-05-23 18:49 UTC
Labels: enhancement, under discussion

**Comment by fregante** [comment] 2020-07-29 08:46
GitHub seems to show `lf` natively now:

<img width="473" alt="Screen Shot 2020-07-29 at 09 45 28" src="https://user-images.githubusercontent.com/1402241/88778416-67759680-d180-11ea-9676-d8467c4602e5.png">


Demo URL: https://github.com/rollup/plugins/pull/414/files#diff-b197c1539f3dea1e33fceb0a1ace63f3

**Comment by fregante** [comment] 2020-07-29 08:48
Heh, mistake. That file is using the "visible lf" glyph
