### ISSUE TITLE
"Open in tabs" for "Select by" selection

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#4570] opened 2021-07-15 12:58 UTC
GH notifications view recently added a "Select by" action that can select only the matching issues and PRs from the notification list:
![image](https://user-images.githubusercontent.com/183673/125791798-a5bcf6fd-7968-4b79-9a9b-1378d67c116a.png)

After using that, you can e.g. mark all merged PRs as "Done" (and make them go away from your notifications) very quickly which is super neat.

What is missing now is a button to open the selected ones (e.g. only closed issues) in new tabs. That would be super neat to be able to work through your notifications in a more organized manner.

**Comment by yakov116** [comment] 2021-07-15 13:14
That was actually added by us. 😄 

- 35440ceb Add `select-notifications` feature (#4526)

**Comment by cheap-glitch** [comment] 2021-07-15 13:23
> What is missing now is a button to open the selected ones

Duplicate of https://github.com/sindresorhus/refined-github/issues/3503?

**Comment by yakov116** [comment] 2021-07-15 13:50
> Duplicate of #3503?

Correct

**Closed by yakov116** 2021-07-15 13:50 UTC
Labels: enhancement, under discussion

**Comment by janpio** [comment] 2021-07-15 14:47
Oh wow, that is a Refined Github feature 🧠 🤯 

Following https://github.com/sindresorhus/refined-github/issues/3503 then
