### ISSUE TITLE
Wait for status checks to pass if branch protections are enabled

### ISSUE THREAD

**Issue by maxwellainatchi** [sindresorhus/refined-github#3038] opened 2020-04-27 19:40 UTC
Not sure if this counts as a feature request or bug, but if branch protections requiring status checks to complete are enabled and you have admin permissions, it's difficult to get to the checkbox for "wait for status checks to complete before merging". You need to press the merge with admin privileges button, and then click a confirmation checkbox, and then click merge, and it looks very destructive the whole way.

Would be much better if there was a second button on the first PR box in that case that said something like "Merge if status checks are complete", next to the "merge with admin privileges" button

**Comment by fregante** [comment] 2020-04-27 19:52
Duplicate of https://github.com/sindresorhus/refined-github/issues/1325

**Comment by fregante** [comment] 2020-04-27 19:52
Sadly this is impossible

**Closed by fregante** 2020-04-27 19:52 UTC
Labels: enhancement, under discussion

**Comment by maxwellainatchi** [comment] 2020-04-27 20:53
The difference between that issue and mine is that I'm referring specifically to when you have admin privileges - the normal "merge" box is in a hidden form element.

(I had to redact part of it for confidentiality reasons)
```html
<form class="merge-branch-form js-merge-pull-request js-immediate-updates js-tryable-again js-needs-timeline-marker-header js-admin-override-merge js-admin-override-squash js-admin-override-rebase" action="/[username]/[repo_name]/pull/[pr_number]/merge" accept-charset="UTF-8" method="post" style="display: block;">
```

**Comment by fregante** [comment] 2020-04-27 22:06
This is what it looks like for me, which looks and works as I expect it to.

<img width="763" alt="" src="https://user-images.githubusercontent.com/1402241/80425498-079ef380-88e4-11ea-9e3e-587ca277c514.png">


 Can you show me what you'd change?

**Comment by kohtenko** [comment] 2020-04-29 20:56
@fregante is there a specific setup required for this checkbox to appear? I have a number of required checks for my PRs, but I don't see the option.

**Comment by kohtenko** [comment] 2020-04-30 13:22
Sure @fregante. Here's what I see when checks are running.
<img width="689" alt="Screen Shot 2020-04-30 at 9 17 36 AM" src="https://user-images.githubusercontent.com/800103/80715105-e137ae80-8ac3-11ea-890f-35a9889c6c92.png">

When I click `Squash and merge` the checks view hides and  and this is what I see

<img width="681" alt="Screen Shot 2020-04-30 at 9 17 45 AM" src="https://user-images.githubusercontent.com/800103/80715235-117f4d00-8ac4-11ea-894b-ce4810cd715e.png">

**Comment by maxwellainatchi** [comment] 2020-05-04 15:08
ah @fregante sorry, seems like there's a bug that sometimes prevents that checkbox from appearing on the administrator confirm box  (as in what @kohtenko just posted) - not sure what exactly causes it, but a page refresh usually fixes it. Maybe a race condition? I only have 1 check running, so it might need to wait for all status checks to initially report their status before loading that box

**Comment by fregante** [comment] 2020-05-04 19:28
@maxwellainatchi yep, that’s https://github.com/sindresorhus/refined-github/issues/3041
