### ISSUE TITLE
"Approve and Merge" button on Comments and/or Files changed page

### ISSUE THREAD

**Issue by ypresto** [sindresorhus/refined-github#2702] opened 2020-01-14 17:00 UTC
I frequently write "LGTM!" comment and push Approve button on `Files changed` page of PR, then redirected to `Comments` page and then push Merge button.
Because that redirection is quite slow, it'd be better if we have `Approve and Merge` button on `Files changed` page.

Also, Sometimes I write additional review comments on `Comments` page before approving. So it's nice to have that button on `Comments` page too.

**Comment by fregante** [comment] 2020-01-14 18:14
Duplicate of #2700

**Comment by fregante** [comment] 2020-01-14 18:14
Thank for opening the issue, will look into it

**Comment by fregante** [comment] 2020-01-14 18:35
This request sounds like the opposite of https://github.com/sindresorhus/refined-github/issues/883

That request was about "Approving from the Conversation tab" and this one is about "Merge from the Files tab"

Neither one is particularly easy to implement, but this is harder: merging a PR means also writing the commit title and message, so to "Approve and merge" we have to ALSO show those two fields inside the review box.

Can't do. It would be too much.

---

Is your repo set up to **require** approvals before merging? Because if not, you don't need to `Approve and merge`: just leave a regular comment and merge from the Conversation tab.

**Closed by fregante** 2020-01-14 18:35 UTC
Labels: enhancement, under discussion

**Comment by ypresto** [comment] 2020-01-16 17:14
> merging a PR means also writing the commit title and message,

Off-topic: Maybe I need 1-Click® merge button which uses default title and message; I always don't change them.
