### ISSUE TITLE
Repository renaming button does not work

### ISSUE THREAD

**Issue by aminya** [sindresorhus/refined-github#3740] opened 2020-11-20 04:12 UTC
When I am trying to rename an empty repository, the button does not work. Here is the screen capture:
![repo-rename-bug](https://user-images.githubusercontent.com/16418197/99757088-3fee6500-2ab4-11eb-9c36-e297ad2ad0b9.gif)

It works fine when I disable the extension.

**Comment by fregante** [comment] 2020-11-20 04:47
Duplicate of #3732

**Closed by fregante** 2020-11-20 04:47 UTC
Labels: bug
