### ISSUE TITLE
Show branch name in PR list

### ISSUE THREAD

**Issue by thomassnielsen** [sindresorhus/refined-github#190] opened 2016-04-26 07:47 UTC
I'd love to see which branch will be/was merged in the PR list. The use case currently bugging me is that I haven't cleaned my local branches for a while 😊 

Currently I'm going into each PR to see what was merged when.

**Comment by sindresorhus** [comment] 2016-04-26 08:05
Duplicate of https://github.com/sindresorhus/refined-github/issues/103?

**Comment by thomassnielsen** [comment] 2016-04-26 08:47
No, #103 wants to show which branch you're merging into, while I want to see what branch you're merging from 😄

**Comment by thomassnielsen** [comment] 2016-04-26 08:49
So maybe something like

> paulmolluzzo wants to merge 1 commit into master from show-created-repos-css

from the PR details page might cover both.

**Comment by paulmolluzzo** [comment] 2016-04-26 11:12
@thomassnielsen if you want to see what's been merged into `master` just do `git branch --merged master`. This is probably a better way to get that list then visually parsing info out of a list of GitHub.

**Comment by hkdobrev** [comment] 2016-10-24 19:22
@thomassnielsen I'm personally using this:

```
git log --oneline --first-parent --since=1.month.ago origin/master
```

**Closed** 2019-01-17 06:35 UTC
Labels: enhancement, has PR, help wanted
