### ISSUE TITLE
Empty repository glitch on issues page

### ISSUE THREAD

**Issue by steveoh** [sindresorhus/refined-github#222] opened 2016-05-17 20:02 UTC
We have an empty repository where we are building up the issues list to define what we are going to create. 

With this plugin installed the header is repeated twice and the issues are shown below
![image](https://cloud.githubusercontent.com/assets/325813/15337237/fbc2d346-1c37-11e6-9d74-ffbb3d374a18.png)

**Comment by paulmolluzzo** [comment] 2016-05-17 20:20
This is a duplicate of #216, so we'll close this one and discuss there.

I guess a lot of people have empty repos. :)

Thanks!

**Closed by paulmolluzzo** 2016-05-17 20:20 UTC

**Comment by steveoh** [comment] 2016-05-17 20:24
Thanks, that title didn't help my search.

**Comment by paulmolluzzo** [comment] 2016-05-17 20:28
Ha, it happens. If you want to drop your screenshot on that ticket you can. It's pretty much the same as the one there though.
