### ISSUE TITLE
Window/Tab freeze in Firefox (conflict with other extensions)

### ISSUE THREAD

**Issue by azdanov** [sindresorhus/refined-github#4343] opened 2021-05-10 08:07 UTC
**
**Fixed in https://github.com/sindresorhus/refined-github/releases/tag/21.5.10**
**

After updating to the latest version https://github.com/sindresorhus/refined-github/releases/tag/21.5.9 I couldn't load GitHub website (infinite load, unresponsive window/tab and browser offering to stop the Refined GitHub extension).

<img width="824" alt="Screenshot 2021-05-10 at 11 02 22" src="https://user-images.githubusercontent.com/6123841/117626022-5500a280-b17f-11eb-9900-284116ca9ae2.png">

I'm using Firefox Developer Edition `89.0b10 (64-bit)` on macOS Big Sur `11.3.1 (20E241)`

~Couldn't reproduce on Windows with same browser.~ Started to happen on Windows 10 also.

Disabling `reactions-avatars` helps sometimes, but not always.

**Comment by marcphilipp** [comment] 2021-05-10 08:52
This is also happening to me with the regular version of Firefox after upgrading to 21.5.9.

**Comment by azdanov** [comment] 2021-05-10 09:05
It happens even here: https://github.com/sindresorhus/refined-github/issues/4343
As for "Find feature", I can't do it since the github tab is frozen and doesn't refresh.

**Comment by gallais** [comment] 2021-05-10 09:25
I am experiencing the same issue on Ubuntu and firefox is similarly offering to temporarily suspend the extension.

* Firefox 88.0
* Refined github 21.5.9

I ran 'find feature' on two different pages and the verdict was 'warning-for-disallow-edits' both times.

**Comment by fregante** [comment] 2021-05-10 09:44
Thank you! `warning-for-disallow-edits` isn't run on this page so that's likely not the case.

Are other extensions enabled? 

Does it happens spontaneously on load/reload or do you have to click/do something?

Do you see anything on this page that might have triggered it? https://github.com/sindresorhus/refined-github/releases/tag/21.5.9

**Comment by fregante** [comment] 2021-05-10 09:48
What happens when you click on "Debug script"? Can you take a screenshot of the code it shows?

**Comment by s-KaiNet** [comment] 2021-05-10 10:01
I have the same problem - version 21.5.9, FF - 88.0.1

**Comment by s-KaiNet** [comment] 2021-05-10 10:35
> 
> 
> I have the same problem - version 21.5.9, FF - 88.0.1, Win10
> 
> However, I cannot reproduce it all the time. For example, it freezes even on the home page for gists, ie. `https://gist.github.com/`, after few restarts (I also used "clear cache" and "Find feature" from the add-in options), now I can open gists without a problem.

More steps to reproduce on Win10:
1. Create a new clean FF profile.
2. Add extension. 
3. After the installation it navigates to the extension's start page - `https://github.com/sindresorhus/refined-github/issues/3543` - no issues
4. Refresh the page a few times - on some of the subsequent reloads you will receive "Redefined Github is slowing down firefox...". It also starts consuming all available memory and CPU. If you wait, it will finally load after a while (up to a minute) consuming 8-9GB in the firefox process. 
5. If you refresh again - it might for work for a few next refreshes and starts freezing again.

**Comment by fregante** [comment] 2021-05-10 11:25
> More steps to reproduce on Win10:

Can you profile the script in the developer tools to see what part of the code is taking a long time?

**Comment by s-KaiNet** [comment] 2021-05-10 12:19
> 
> 
> > Might be related or not. Usually, GitHub doesn't load and stays blank. Now it's partially loaded.
> 
> It looks like you're running an extra "protection" extension. What is it?
> 
> > More steps to reproduce on Win10:
> 
> Can you profile the script in the developer tools to see what part of the code is taking a long time?

[This is](https://1drv.ms/u/s!Aga8ybrtcxQHga4ycHHepN2LPHKv7w) what I have. However, for some reason, I'm not able to reproduce this issue on a clean profile. Will try later and if it's successful, will attach a profile.

**Comment by s-KaiNet** [comment] 2021-05-10 12:27
[This is](https://1drv.ms/u/s!Aga8ybrtcxQHga4zchfUoUCY8bYWIQ?e=fDF6dg) on a clean profile (did exactly the steps from my previous message). However it looks like that after opening dev tools, enabling\disabling cache, the issue somehow disappears. I'm still not sure which actions lead the bug to be disappeared.

**Comment by s-KaiNet** [comment] 2021-05-10 12:31
@azdanov Just curious if you follow my steps with a clean profile, will you have the same problem (with disabled adguard)?

**Comment by s-KaiNet** [comment] 2021-05-10 12:34
And the last thing - for me it feels like that's a memory problem (leaks on something like that), which occurs only under certain circumstances. Because when it starts freezing it immediately consumes 2-4 additional GB of memory in just a few seconds.

**Comment by s-KaiNet** [comment] 2021-05-10 13:11
Well, in the end for me that's also an anti-virus program. I have a Kaspersky antivirus. I checked different settings and found this: 

![image](https://user-images.githubusercontent.com/10658276/117663674-9c038d80-b1a9-11eb-95bb-aacc1ae597eb.png)

[In English](https://support.kaspersky.com/KIS/2020/en-US/68219.htm):

> Inject script into web traffic to interact with web pages
> If the check box is selected, Kaspersky Internet Security injects a web page interaction script into web traffic. This script ensures the operation of such components as Safe Money, Private Browsing, Parental Control, Anti-Banner, URL Advisor, and Secure Data Input.  

When this is checked, it adds some "safety" information about links like on the image below:
![image](https://user-images.githubusercontent.com/10658276/117663840-c6554b00-b1a9-11eb-951a-bc9f2d986f59.png)

As soon as I uncheck this setting, everything just works. If I have it checked and `redefined-github` **enabled**, then sometimes it freezes a page. If I have it checked and `redefined-github` **disabled** then again it works. So somehow the latest release of `redefined-github` affects some antivirus behaviour.

**Comment by yakov116** [comment] 2021-05-10 13:45
> If the tab freezes completely, my only guess is that it's this new loop: [#4316 (files)](https://github.com/sindresorhus/refined-github/pull/4316/files#diff-cb1dafea7a9c68c5c2ebb2d56f749b3506c13f7d26feeaf56c86521b25c60358R109-R112)
> 
> But it should still not freeze it since it releases the thread every 10ms.
> 
> cc @yakov116 can you replicate this issue in Firefox?

I can't test until tonight. But maybe the anti virus scanning is hacking the loop?

Maybe we should do 20ms and see if it helps?

**Comment by fregante** [comment] 2021-05-10 14:17
👉 Does installing an older version fix it for you?

https://addons.mozilla.org/en-US/firefox/addon/refined-github-/versions/

Does everyone here have some antivirus or AdGuard installed? Please leave a comment

**Comment by Dev-CasperTheGhost** [comment] 2021-05-10 14:30
having the same issue. Tho I can't always reproduce it 🤔 

> 👉 Does installing an older version fix it for you?

All worked fine for me before 12.5.9. 

> Does everyone here have some antivirus or AdGuard installed? Please leave a comment.

nope.

**Comment by fregante** [comment] 2021-05-10 14:49
@azdanov @s-KaiNet can you report this issue to those extensions as well?

**Comment by unixfox** [comment] 2021-05-10 15:53
I also tried version 21.5.1 on Firefox and no issues related to slow-downs or error messages from Firefox.
I'm also running a DNS adblocker called pihole: https://pi-hole.net/

**Comment by yakov116** [comment] 2021-05-10 16:01
@unixfox @Dev-CasperTheGhost can you try https://github.com/sindresorhus/refined-github/suites/2701228648/artifacts/59535951 and see if you have an issue?

**Comment by azdanov** [comment] 2021-05-10 16:14
@yakov116 Works for me.

**Comment by Dev-CasperTheGhost** [comment] 2021-05-10 16:17
> can you try sindresorhus/refined-github/suites/2701228648/artifacts/59535951 and see if you have an issue?

Nope. This works fine :D

**Comment by yakov116** [comment] 2021-05-10 16:19
@fregante I am going to revert that commit and do a release.

Ok With that?

**Comment by Vicente015** [comment] 2021-05-10 16:21
I have the same problem using `Firefox 88.0` on `Linux 5.4 Zorin OS 15.3` with the following extensions: https://gist.github.com/Vicente015/74db589a4760cdb196dadf18af5e4111 

I will try version 21.5.1.

**Comment by yakov116** [comment] 2021-05-10 16:24
Can you try https://github.com/sindresorhus/refined-github/suites/2701228648/artifacts/59535951

**Comment by azdanov** [comment] 2021-05-10 16:43
@Vicente015 You have to temporarily disable `xpinstall.signatures.required` inside `about:config` page in Firefox.

**Comment by Vicente015** [comment] 2021-05-10 16:49
> @Vicente015 You have to temporarily disable `xpinstall.signatures.required` inside `about:config` page in Firefox.

Thanks! Works fine now

**Comment by fregante** [comment] 2021-05-10 18:02
If you encounter the same issue while on version 21.5.10 please leave a comment specifying which version you’re using.

**Comment by fregante** [comment] 2021-05-13 11:08
Closing since it seems to be resolved. 🥳

**Closed by fregante** 2021-05-13 11:08 UTC
Labels: bug, firefox

**Comment by yakov116** [comment] 2021-05-16 04:21
Anyone here can test https://github.com/sindresorhus/refined-github/suites/2743556032/artifacts/60647440. We want to make sure we dont hace a regression.

Thanks!

**Comment by s-KaiNet** [comment] 2021-05-16 07:12
Tested on Dev Edition `89` - for me it works without the issue.

**Comment by Dev-CasperTheGhost** [comment] 2021-05-16 07:13
Yup, been using it for about an hour and all seems to be working well for me too
