### ISSUE TITLE
Settings Page Features section should have sub-sections. 

### ISSUE THREAD

**Issue by AmrBinBashir** [sindresorhus/refined-github#3561] opened 2020-09-16 12:59 UTC
I get lost every time I try to toggle a specific feature, either because I don't know where it is or the exact name of it.
Dividing the features into sections like `PR related features`, will be make looking for features easier.

**Comment by fregante** [comment] 2020-09-16 19:42
Duplicate of https://github.com/sindresorhus/refined-github/issues/3357

**Closed by fregante** 2020-09-16 19:42 UTC
Labels: enhancement, under discussion
