### ISSUE TITLE
Would be cool if we could actually determine what the bug tag should be

### ISSUE THREAD

**Issue by msanz-acclaro** [sindresorhus/refined-github#4109] opened 2021-03-16 09:02 UTC
#### Request explanation
I have checked the code here: https://github.com/sindresorhus/refined-github/blob/main/source/features/bugs-tab.tsx

and I would like to propose a small update, allow to define the tag that determines something is a bug in the extension config, being the default `bug`
```
[...]
const countBugs = cache.function(async (): Promise<number> => {
	const {search} = await api.v4(`
		search(type: ISSUE, query: "label:bug is:open is:issue repo:${getRepo()!.nameWithOwner}") {
			issueCount
		}
	`);
[...]
```

if the search query was something like
`search(type: ISSUE, query: "label:${getUserPreferences()!.bugTagName} is:open is:issue repo:${getRepo()!.nameWithOwner}")`

Of course, it would require to create the `UserPreferences`.

If we could even add more filters like that one for user-stories too, that would be AWESOME :)

#### Background
In our case, we use `Type:bug` as we align many tags. Without a descriptor it looks kindof messy, especially for new team members

**Comment by yakov116** [comment] 2021-03-16 11:56
Thanks for your request.

However this a Duplicate of #2897

**Closed by yakov116** 2021-03-16 11:56 UTC
Labels: change request
