### ISSUE TITLE
Inject custom defined shortcuts into the shortcut pannel

### ISSUE THREAD

**Issue by vanniktech** [sindresorhus/refined-github#1061] opened 2018-02-04 10:43 UTC
I've seen that this plugin allows to use more shortcuts like `g + m` to go to my profile. It would be super beneficial if in the shortcut panel `shift + ?` I could see which shortcuts are applicable for the site I'm seeing.

**Comment by sindresorhus** [comment] 2018-02-04 10:52
Duplicate of #579

**Closed by sindresorhus** 2018-02-04 10:52 UTC
