### ISSUE TITLE
Make `Hide whitespace changes` stay as default

### ISSUE THREAD

**Issue by pvinis** [sindresorhus/refined-github#4812] opened 2021-09-24 07:03 UTC
### Description

This feature here, that would be great to be always selected, or at least persisted. Is that something that refined can help with?

### Screenshot

<img width="460" alt="Screen Shot 2021-09-23 at 10 07 38 AM" src="https://user-images.githubusercontent.com/100233/134632297-94f2dcbe-ef90-4828-b7b8-6dc716fb904e.png">

### Example URL

https://github.com/artsy/eigen/pull/5511/files

**Comment by fregante** [comment] 2021-09-24 07:58
Duplicate of https://github.com/sindresorhus/refined-github/issues/2503

**Closed by fregante** 2021-09-24 07:58 UTC
Labels: enhancement, under discussion

**Comment by yakov116** [comment] 2021-10-14 20:54
https://github.blog/changelog/2021-10-14-hiding-whitespace-is-now-remembered-for-each-pull-request/
