### ISSUE TITLE
Add support for labels other than "bug" in `bugs-tab`

### ISSUE THREAD

**Issue by bl-ue** [sindresorhus/refined-github#4452] opened 2021-06-08 18:38 UTC
I love `bugs-tab` but it doesn't show up https://github.com/nodejs/node, which I work on, because we use the [<kbd>confirmed-bug</kbd>](https://github.com/nodejs/node/issues?q=is%3Aissue+label%3Aconfirmed-bug+is%3Aopen) label for bugs, rather than `bug`.

Could the label name be configurable?  Or, could we list the labels and use ones that match `/\bbug\b/`? 🤔

**Comment by yakov116** [comment] 2021-06-08 18:45
Duplicate of #2897

Another point to take into account is currently logical operators do not work (label:bug OR label::bug: Bug). So any other labels would require a brand new query for every repo.

**Comment by bl-ue** [comment] 2021-06-08 18:48
>Duplicate of #2897

Oh, should've checked first 😆

>Another point to take into account is currently logical operators do not work (label:bug OR label:🐛 Bug). So any other labels would require a brand new query for every repo.

Darn, that's a hard one.

**Comment by busches** [comment] 2021-06-08 21:17
Also, in regards to your regexp, labels like `not-a-bug` would also match :|

**Comment by bl-ue** [comment] 2021-06-08 21:33
Yeah, I though of that but I forgot to write it above 😭

**Comment by fregante** [comment] 2021-07-13 12:29
We _could_ add support either for a specific set of labels by adding another query inside the existing call:

https://github.com/sindresorhus/refined-github/blob/285eaec360f21431757236c6c39cdbe6f303f6e2/source/features/bugs-tab.tsx#L28-L32

Example:

```ts
	const {search, labels} = await api.v4(`
		search(type: ISSUE, query: "label:${cache.get('bugs-label') ?? 'bugs'} is:open is:issue repo:${getRepo()!.nameWithOwner}") {
			issueCount
		}
		labels: repository() {label /*get labels somehow*/}
	`);

	if (search.issueCount > 0) {
		return search.issueCount;
	}

	const bugsLabel = labels.find(/* bugs label */)
	if (bugsLabel) {
		await cache.set('bugs-label', bugsLabel);
		return countBugs() // Recursive
	}

	return 0
```

**Comment by fregante** [comment] 2021-07-13 16:42
> I feel like we may be biting ourselves in the back

True, we do risk getting requests for new labels occasionally, but since there have only ever been 2 requests for custom bug labels I think we'll be fine. 

As for "the wrong label," that's why I suggested using a predefined list instead of using `/bug/i` to guess the label. We can see what the common big repos are using and add those to our list. We can decide which label makes the cut later on.

**Comment by yakov116** [comment] 2021-07-13 17:15
If anyone wants to do this the following is the query

```graphql
    labels(query: "bug", first: 10) {
      nodes {
        name
      }
    }
```

**Comment by yakov116** [comment] 2021-07-19 15:20
Anyone have sample repo's I can test on. So far I have `🐛 Bug` and `confirmed-bug`.

**Closed** 2021-07-28 06:27 UTC
Labels: enhancement, help wanted, under discussion
