### ISSUE TITLE
"Edit comment" button injection is not reliable

### ISSUE THREAD

**Issue by nashbridges** [sindresorhus/refined-github#3279] opened 2020-06-25 07:33 UTC
This is in Brave 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit).
All shields are turned off (gray icon).

Oftentimes when I edit the comment, the button is gone after submitting:

![image](https://user-images.githubusercontent.com/380913/85672836-f730ac80-b6cb-11ea-983d-2d9cfd22e096.png)

After a full page refresh it is back again:

![image](https://user-images.githubusercontent.com/380913/85673097-37902a80-b6cc-11ea-88de-a2c75ced5341.png)

I can't reproduce this bug in Chrome 83.0.4103.116. When I submit the edit there, the icon is hidden for a split second, but then is always back.

In both browsers I see the console error during initial load ([example page](https://github.com/ua-books/ua-books/issues/33)):

```
❌ Refined GitHub → more-dropdown → TypeError: Cannot read property 'append' of null
    at appendBefore (refined-github.js:3157)
    at createDropdown (refined-github.js:3171)
    at more_dropdown_init (refined-github.js:3184)
    at async runFeature (refined-github.js:2837)
    at async setupPageLoad (refined-github.js:2845)
```

however, I doubt it's related, because it does not appear during the submitting.

**Comment by fregante** [comment] 2020-06-25 08:00
Thanks for reporting! This actually happens in chrome too. There’s likely another issue open about this.

**Comment by fregante** [comment] 2020-07-01 14:53
Duplicate of https://github.com/sindresorhus/refined-github/issues/2264

**Closed** 2020-10-07 22:31 UTC
Labels: bug, help wanted

**Comment by nashbridges** [comment] 2020-10-08 12:57
Thanks! I confirm the button is there even after a couple of edits.
