### ISSUE TITLE
Add `line-through` on deleted branches in PRs

### ISSUE THREAD

**Issue by gurrrung** [sindresorhus/refined-github#2274] opened 2019-07-27 07:54 UTC
Only colon is line-throughed here.
![Screenshot from 2019-07-27 13-21-33](https://user-images.githubusercontent.com/30543444/61991691-c0908300-b071-11e9-936e-2311064f1d63.png)

Link to PR in screenshot: https://github.com/sindresorhus/refined-github/pull/2233

**Comment by fregante** [comment] 2019-07-27 09:25
Thanks for the report!

It’s a duplicate of https://github.com/sindresorhus/refined-github/issues/1985

I hope someone sends a PR soon ☺️

**Comment by fregante** [comment] 2019-07-29 18:47
Reopening because now this needs to be re-implemented as its own feature: `cross-deleted-pr-branches`

Most of the logic is in https://github.com/sindresorhus/refined-github/commit/cb8de12eb680475024c21d5586aa31a232493c73 (removed) but now we only need to use the part that adds the strike-through, not the linkifier.

**Comment by gurrrung** [comment] 2019-08-04 08:19
> The feature could also point the link to the repo root (instead of the 404 deleted branch) to make it somewhat useful.  

Forked repo root or the primary repo?

**Comment by fregante** [comment] 2019-08-05 04:40
The head branch could either be from the same repo or from a fork. I think it would only make sense to point to the fork’s default branch and do nothing if it’s the same repo.

**Closed** 2020-03-13 21:37 UTC
Labels: enhancement, good first issue, help wanted
