### ISSUE TITLE
every repository 19-years-old? 

### ISSUE THREAD

**Issue by miyataka** [sindresorhus/refined-github#3394] opened 2020-07-23 14:39 UTC
# every repository 19-years-old, and link is broken.

## URLs
- https://github.com/miyataka/fcmpush
- https://github.com/rails/rails

## ScreenShots
- ![image](https://user-images.githubusercontent.com/15692588/88299336-3428a700-cd3d-11ea-80f4-c6186941dc4c.png)
- ![image](https://user-images.githubusercontent.com/15692588/88299370-3db20f00-cd3d-11ea-8bb5-24789aa9faab.png)

### when the extension disabled, I can't find that info.
- ![image](https://user-images.githubusercontent.com/15692588/88299591-7ce06000-cd3d-11ea-8c4b-0f47b98f8688.png)

**Comment by yakov116** [comment] 2020-07-23 14:41
What version of refined github are you on?

**Comment by miyataka** [comment] 2020-07-23 14:45
It's 20.7.19

![image](https://user-images.githubusercontent.com/15692588/88300505-84543900-cd3e-11ea-951e-02b53b7f0371.png)

**Comment by fregante** [comment] 2020-07-23 15:28
Duplicate of #3340

**Comment by fregante** [comment] 2020-07-23 15:31
Can you click here...

![88300505-84543900-cd3e-11ea-951e-02b53b7f0371](https://user-images.githubusercontent.com/1402241/88305713-b8f5cf80-cd01-11ea-852b-23a785d12659.png)


...and execute this code?

```js
await browser.storage.local.get('cache:repo-age:rails/rails')
```

What's the output?

**Comment by miyataka** [comment] 2020-07-23 16:03
like this.
![Screen Shot 2020-07-24 at 1 02 05](https://user-images.githubusercontent.com/15692588/88309473-4e688200-cd49-11ea-8015-7d7eea22835f.png)

**Comment by miyataka** [comment] 2020-07-23 16:14
@fregante @yakov116 
I got it.
I should set personal token to enable this feature. I've not set that.
after set that, it works.
sorry for spending your time.
and Thank you very much.

**Closed** 2020-07-23 16:15 UTC
Labels: bug

**Comment by kidonng** [comment] 2020-07-23 16:27
> like this.

Hmm, that's the normal output, not the 19 years one 😅

**Comment by yakov116** [comment] 2020-07-23 16:30
Its not. the response should be an array

**Comment by fregante** [comment] 2020-07-23 18:29
For the record, this is what it should look like:

<img width="729" alt="" src="https://user-images.githubusercontent.com/1402241/88323751-9e7c2000-cd1a-11ea-9093-9b27653e0bbc.png">


✅ USERS: add a token to fix the issue.
➡️ CONTRIBUTORS: help fix the core issue: https://github.com/fregante/webext-storage-cache/issues/21
