### ISSUE TITLE
Don't auto turn on new features

### ISSUE THREAD

**Issue by iamsolankiamit** [sindresorhus/refined-github#2743] opened 2020-01-29 14:00 UTC
Whenever there is an update, especially related to PRs, branches, etc please don't enable them by default.

**Comment by sindresorhus** [comment] 2020-01-29 14:21
Why?

**Comment by iamsolankiamit** [comment] 2020-01-29 14:25
Most recent one was updating pr title, which updates PR title when they are merged, which I didn't expect. What we can do is show a page when the extension updates with new features, so user can choose which features they want to turn on.

**Comment by yakov116** [comment] 2020-01-29 14:38
I tried looking back that feature was added waaaaay back

https://github.com/sindresorhus/refined-github/blob/d747ed5c2f550435a908150b41f4bb3b6cb53b50/src/features/fix-squash-and-merge-title.js it goes back even farther...

Regarding new features, I strongly disagree. When ever you update an app do you expect them to have all new features disabled?

**Comment by iamsolankiamit** [comment] 2020-01-29 14:46
I agree that enhancements are expected to be on by default and they should be. But things like deleting branches, updating pr titles, etc should at least be informed to the user. I am not talking about squash and merge by the way, it's sync-pr-commit-title https://github.com/sindresorhus/refined-github/blob/master/source/features/sync-pr-commit-title.tsx

**Comment by yakov116** [comment] 2020-01-29 14:58
@iamsolankiamit that function was just updated to do more.

Lets not get petty.

>Regarding new features, I strongly disagree. When ever you update an app do you expect them to have all new features disabled?

**Comment by iamsolankiamit** [comment] 2020-01-29 15:30
Anything that might affect other contributors, should be informed to user. Visual and other enhancements that only affect the user who installed are fine imo.

**Comment by yakov116** [comment] 2020-01-29 15:37
@fregante Would sending the user to https://github.com/sindresorhus/refined-github/issues/1137 when such a feature be an option?

**Comment by iamsolankiamit** [comment] 2020-01-29 16:02
Yea, that could help.

**Comment by fregante** [comment] 2020-01-30 03:01
Duplicate of https://github.com/sindresorhus/refined-github/issues/2664

If you don’t want new features, disable the updates and only update when needed. Also https://github.com/sindresorhus/refined-github/pull/2668 can help you see which features are new

**Closed by fregante** 2020-01-30 03:01 UTC
Labels: enhancement, under discussion

**Comment by fregante** [comment] 2020-01-30 03:08
> But things like deleting branches, updating pr titles, etc should at least be informed to the user.

We do have a notice for the title change and it’s right by the title. It also allows the user to cancel it in-place. 

Regarding the branches deletion, we already discussed this when the feature was implemented but we consider it non-destructive because:

- you can undo the deletion with one click right there at any time
- if you have long-standing branches, you should mark them as protected in GitHub. This is something you really should do so a git push can’t delete them either
- finally the feature can be disabled if you really don’t like it
