### ISSUE TITLE
High CPU and RAM usage on large files (due to `show-whitespace`)

### ISSUE THREAD

**Issue by pdonias** [sindresorhus/refined-github#2732] opened 2020-01-23 15:11 UTC
Opening the link below with Refined GitHub uses a lot of CPU and eats all the RAM very quickly.

<details>
<summary>Be ready to have your computer freeze before clicking the link</summary>
<a href="https://github.com/teropa/to-sting/blob/master/index.js">https://github.com/teropa/to-sting/blob/master/index.js</a>
</details>

![Capture_2020-01-23_15:59:25](https://user-images.githubusercontent.com/10992860/72995676-98ec5e80-3df9-11ea-9bd7-84d38c92a4fd.png)

Refined GitHub 20.1.22
Firefox 72.0.1 (I couldn't reproduce the issue on Chrome)
Ubuntu 18.04.3 LTS

**Comment by fregante** [comment] 2020-01-23 15:43
Confirmed, this is due to `show-whitespace`. The solution would be "easy": detect the slow loop and stop:

https://github.com/sindresorhus/refined-github/pull/2087/files/c2c44b10e42ff2ccbbf94cf66fef5bf7ef9f6f2e..e3474a401792d5dab19b391208798fd8d5d3e77a

PR welcome. Also perhaps there are improvements in the algorithm but this would be a quick fix.

**Comment by AleksandrHovhannisyan** [comment] 2020-01-24 23:16
> // eslint-disable-next-line no-await-in-loop

What if instead of using `await` we use old-fashioned promise handlers?

**Comment by fregante** [comment] 2020-01-25 10:07
I don't understand. How would you rewrite that loop with "promise handlers"?

**Comment by AleksandrHovhannisyan** [comment] 2020-01-25 14:23
What I probably meant is promise chaining. I don't know the terminology too well.

But `await` is gonna slow down that loop for sure.

**Comment by fregante** [comment] 2020-01-25 22:45
Await isn’t slower than promise chains. The lint rule is because await stops the loop and some users don’t realize that. 

I found the problem of this issue: the feature is currently wrapping each individual character into its own DocumentFragment and then appending the whole thing back. The line in the middle is 200k characters long so you can see how that might take forever to finish. 

I’m rewriting the feature to be a lot more efficient and I’ll probably also add a line length limit for these cases

**Comment by AleksandrHovhannisyan** [comment] 2020-01-25 22:54
> The lint rule is because await stops the loop and some users don’t realize that.

Right, I just figured stopping the loop is what was slowing the whole thing down.

Sorry for sticking my nose in this, though; I'm trying to get more involved in OSS but haven't found something that works for me.

**Comment by fregante** [comment] 2020-01-26 17:41
> I’m rewriting the feature to be a lot more efficient

Fixed without adding limits, but it needs a little more work.

> Right, I just figured stopping the loop is what was slowing the whole thing down.

You got it the other way: `await setTimeout` was there specifically to avoid freezing the browser.

Loops will freeze the browser until they finish. In this case, the loop was doing thousands of operations that probably took minutes in Firefox, without letting the browser _breathe._

`await setTimeout` was there specifically to stop the loop and let the browser remain interactive (i.e. without freezing) but this only checked once per line. In this extreme example, one line was enough to freeze the browser for minutes so it never got to `await`

**Closed** 2020-02-03 07:26 UTC
Labels: bug, has PR
