### ISSUE TITLE
Minor UI inconsistency: "Author" dropdown button has no left padding on the Issues page.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [sindresorhus/refined-github#2656] opened 2019-12-24 23:28 UTC
This makes `Open All` and `Author` appear very close to each other, relative to the other filter buttons.

Example URL: https://github.com/sindresorhus/refined-github/issues

Demo:

![demo](https://user-images.githubusercontent.com/19352442/71427059-97f0d180-2681-11ea-85fc-27a84bcf339b.gif)

Should be a really quick and easy CSS fix. I'd like to take a stab at this if that's cool.

**Comment by fregante** [comment] 2019-12-25 02:28
I think this is a duplicate of #2631 and it’s being fixed by https://github.com/sindresorhus/refined-github/pull/2648

But thank you for the report and quick PR!

**Closed** 2019-12-25 02:29 UTC
Labels: bug

**Comment by AleksandrHovhannisyan** [comment] 2019-12-25 13:13
Ah, oops :D Np.
