### ISSUE TITLE
Broken diff view for commit with rename only

### ISSUE THREAD

**Issue by wagnerand** [sindresorhus/refined-github#2374] opened 2019-08-22 12:31 UTC
Without Refined GitHub:

<img width="1035" alt="without" src="https://user-images.githubusercontent.com/873258/63514645-55f42b00-c4e9-11e9-8fb9-b4382ec70cdd.png">

With Refined GitHub:

<img width="1016" alt="with" src="https://user-images.githubusercontent.com/873258/63514666-5f7d9300-c4e9-11e9-880d-befb6aab0ede.png">

URL: https://github.com/mozilla/addons-server/pull/12182/files/353b86e8f6c40892169aa1947ae211bd315ec846..05f43fb44923b21b7e9b7c4d963dea2f95d2d95a

**Comment by fregante** [comment] 2019-08-22 15:35
Thank you for the report ☺️ 

It’s a duplicate of https://github.com/sindresorhus/refined-github/issues/2291

**Closed by fregante** 2019-08-22 15:35 UTC
Labels: bug
