### ISSUE TITLE
All activity: strange styles

### ISSUE THREAD

**Issue by pustovalov** [sindresorhus/refined-github#4533] opened 2021-07-01 09:28 UTC
1. A REAL URL where the bug appears. If it happens on a private repo, find an equivalent public URL.
https://github.com

2. A screenshot/video/gif of the issue, if it’s visual.
![image](https://user-images.githubusercontent.com/1568885/124100438-24463680-da67-11eb-9dc6-74ad77e9bf35.png)

![image](https://user-images.githubusercontent.com/1568885/124100552-3e801480-da67-11eb-9456-350268a53b8e.png)

without extension:
![image](https://user-images.githubusercontent.com/1568885/124100743-63748780-da67-11eb-90ac-1ddfb2e8da95.png)

3. Any related errors in the browser’s console, if any.
no errors

version: 21.6.17

## Possible solution:
- hide that white block
- don't hide text inside white block

**Comment by fregante** [comment] 2021-07-01 10:22
Duplicate of #4380

**Closed by fregante** 2021-07-01 10:22 UTC
Labels: bug
