### ISSUE TITLE
Adds Trending Menu on Top multiple times

### ISSUE THREAD

**Issue by deadcoder0904** [sindresorhus/refined-github#540] opened 2017-06-25 14:28 UTC
![screenshot from 2017-06-25 19-57-40](https://user-images.githubusercontent.com/16436270/27516922-a3048eb0-59e0-11e7-8b03-b16d796bdbc5.png)

This issue start occuring from past 2-3 days

**Comment by jgierer12** [comment] 2017-06-25 14:39
Duplicate of #479

**Closed by jgierer12** 2017-06-25 14:39 UTC
Labels: duplicate
