### ISSUE TITLE
Make "command line instructions" text visible again

### ISSUE THREAD

**Issue by simonschaufi** [sindresorhus/refined-github#997] opened 2018-01-14 14:36 UTC
Thank you very much for making it possible to configure the addon now! Unfortunatelly CSS stuff is still not possible to configure.

As I need to manually test a lot of pull requests from other people on my own machine, I don't know how other developers are doing it but I always use the command line help text which is hidden if I actiave this addon.

![grafik](https://user-images.githubusercontent.com/941794/34916987-94cb273c-f940-11e7-8c7b-aaeb57a7b080.png)

Can this link be made visible again or is there any better way how to do it?

This is the responsible css for it: https://github.com/sindresorhus/refined-github/blob/master/source/content.css#L125-L127

**Comment by bfred-it** [comment] 2018-01-14 15:13
Duplicate of #963 #610 #227

**Closed by bfred-it** 2018-01-14 15:13 UTC
