### ISSUE TITLE
Keyboard shortcuts to navigate "Files Changed" tab

### ISSUE THREAD

**Issue by Enrico2** [sindresorhus/refined-github#2893] opened 2020-03-14 19:27 UTC
I would love to be able to navigate the "Files Changed" tab with the keyboard. My suggestion would be `j` and `k` for "next" and "previous" file, and `x` to mark file as viewed. 

Currently `j`, `k` and `x` show up as site wide shortcuts for "move selection down", "up" and "toggle selection" respectively, but they don't seem to do anything in the "Files Changed" tab.

Example URL:
https://github.com/org/repo/pull/1234/files

**Comment by fregante** [comment] 2020-03-14 19:44
Duplicate of #853

**Closed by fregante** 2020-03-14 19:44 UTC
Labels: enhancement, under discussion
