### ISSUE TITLE
Duplicate text when user star a repository

### ISSUE THREAD

**Issue by anc** [sindresorhus/refined-github#1166] opened 2018-03-13 11:08 UTC
![screen shot 2018-03-13 at 18 03 59](https://user-images.githubusercontent.com/34530026/37338179-3d230582-26e9-11e8-9fc5-42fa8df28c8c.png)

> Is this a bug or is it actually supposed to do so?

**Comment by ramlmn** [comment] 2018-03-13 12:09
Duplicate of #1152, fixed by #1159.

Update the extension to see the change.

**Comment by bfred-it** [comment] 2018-03-13 15:14
Yes this was recently fixed

**Closed by bfred-it** 2018-03-13 15:14 UTC
Labels: duplicate
