### ISSUE TITLE
diffbar takes more height than available in PR toolbar

### ISSUE THREAD

**Issue by trivikr** [sindresorhus/refined-github#2477] opened 2019-10-05 15:37 UTC
Steps to reproduce:
* Visit any PR in which diff requires scrolling the page.
* Switch to diff tab, and scroll the page.
* Notice that when refined-github is enabled, diffbar takes more height than it's parent PR toolbar

refined-github disabled:
![diffbar-without](https://user-images.githubusercontent.com/16024985/66257243-47856a00-e74b-11e9-8447-bfa8fe75d427.png)

refined-github enabled:
![diffbar-with](https://user-images.githubusercontent.com/16024985/66257247-53712c00-e74b-11e9-8e67-b06a1519e1f7.png)

**Comment by busches** [comment] 2019-10-05 16:07
Duplicate of #2291.

**Closed by busches** 2019-10-05 16:07 UTC
Labels: bug
