### ISSUE TITLE
Add issues with `:bug: Bug` to the bug tab

### ISSUE THREAD

**Issue by aminya** [sindresorhus/refined-github#3494] opened 2020-08-23 09:08 UTC
It would be nice if the issues with `:bug: Bug` or `bug :beetle:` are added to the bug tab. 

Example of a repository that uses this: 
[parcel](https://github.com/parcel-bundler/parcel/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22%3Abug%3A+Bug%22)
[electron](https://github.com/electron/electron/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22bug+%3Abeetle%3A%22)

To generalize this, I guess it is better to search in the label and add it to Bugs if `"bug"` is found.

**Comment by fregante** [comment] 2020-08-23 20:27
Duplicate of https://github.com/sindresorhus/refined-github/issues/2897

**Closed by fregante** 2020-08-23 20:27 UTC
Labels: enhancement, under discussion

**Comment by fregante** [comment] 2020-08-23 20:29
We’re limited by the search (and its API): it doesn’t accept regexes, so we can’t use them

**Comment by aminya** [comment] 2020-08-23 21:43
@fregante Could you keep the issue open? This isn't solved yet. Having it open keeps this on the radar.

**Comment by fregante** [comment] 2020-08-23 22:08
There's no radar if there's no way to solve it
