### ISSUE TITLE
"Mark as unread" button broken?

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#1032] opened 2018-01-24 23:17 UTC
Is it just me or is that button in issues/pr's (right sidebar) not working?

If I hit it, it'll pop-in and grey out, but nothing happens:
![unread](https://user-images.githubusercontent.com/9874850/35362235-dc31f714-0164-11e8-94f4-85099ecd67b6.png)

Reloading shows the fresh and clickable <kbd>Mark as unread</kbd> button again...

Running version `18.1.24.1502` in Firefox 58.0

**Comment by ramlmn** [comment] 2018-01-26 11:16
Are you reloading the same page for which you marked the notification as unread, then it is the expected behavior.

1. Click `Mark as unread` button.
2. The notification icon should turn green.
3. *Behavior changes on what you do next*
    1. If you reload the same page, then it is considered that you read the notification (by loading that page), so the `Mark as unread` button lights back up.
    2. If you go to a completely different page, your notification is still preserved in the notification list.

This would be considered a bug when `3.ii` happens and either if you still don't see the notification in notification page or when the notification icon doesn't lit up.

@bfred-it This cannot be considered a bug if the button is active after loading the page. The button **is** activated when you load the page (notification is read).

**Comment by bfred-it** [comment] 2018-01-26 12:00
I had this issues as well. The button appears, it clicks, but then the notification isn’t actually saved. I can’t reproduce 100% of the times, it might have to do with ajax navigation or timing, I don’t know. 

The whole featured was patched up from the synchronous `localStorage` to the async `chrome.storage`, so I don’t doubt that there are bugs exactly like this.

**Comment by ramlmn** [comment] 2018-01-26 12:15
Happened for me too. But in my case green notification icon lights up, but could not see the notification in notification page. And as always, cannot reproduce it.

I didn't know we were using `browser.storage.local` to store unread notifications. IMO, indexedDB is better and is my go-to option for storing any data in browser, and it has a nice wrapper by @jakearchibald!

**Comment by bfred-it** [comment] 2018-01-26 14:29
It'd be an overkill, it's essentially an array of a few properties. `browser.storage.local` is the right API since it's an extension and if anyone wants to tackle #1036 we'd just be able to use `browser.storage.sync`.

**Comment by tooomm** [comment] 2018-02-01 19:06
>Are you reloading the same page for which you marked the notification as unread, then it is the expected behavior.

Sure, that makes sense.

Here are some more details:

I have 5 unread notifications, I hit `Mark as unread` on two more issues.
If I then go to the github main page my addons to track GitHub notifications  (Advanced GitHub Notifier & Notifications Preview for GitHub) show still 5 notifications. Also, waiting 5-10min doesn't change something.

If I go to https://github.com/notifications I also have a weird result:
![notifications](https://user-images.githubusercontent.com/9874850/35697482-9dbaa784-078a-11e8-8b8c-84e55fb3dba3.png)

It correctly shows `7` unread, but only `4+1` on a repo basis.

**Comment by bfred-it** [comment] 2018-02-01 19:32
> It correctly shows 7 unread, but only the old 4+1 on a repo basis.

Unread / Participating include the "mark as unread" conversations; the repo counts and [Notifications Preview for GitHub](https://github.com/tanmayrajani/notifications-preview-github/issues/38) don't

**Comment by tooomm** [comment] 2018-02-01 19:45
Hmm, it also doesn't mark issues/pr's in their lists as unread again.
There is no such indication displayed again:
![untitled](https://user-images.githubusercontent.com/9874850/35699409-4afca7f8-0790-11e8-892d-8fb443e16913.png)

Other apps on mobile to track GitHub notifications don't pick them up either.
Most of such addons/apps seem to work the same then and only consider the other count.

Is the `Mark as unread` feature useful then at all?
Too me it looks more confusing than helpful... 😕

**Comment by bfred-it** [comment] 2018-02-01 20:07
> Hmm, it also doesn't mark issues/pr's in their lists as unread again.

It should. Pre-existing conversations are brought up.

> There is no such indication displayed again:

That indicator has nothing to do with read status.



> Other apps on mobile to track GitHub notifications don't pick them up either.

Yes, Mark as Unread is local, it doesn't actually mark them as unread on GitHub

> Is the Mark as unread feature useful then at all?

No it's not useful

**Comment by bfred-it** [comment] 2018-03-05 11:25
Closing this as it's hardly reproducible. If you can find a way to reproduce it please post it or send a PR.

**Closed by bfred-it** 2018-03-05 11:25 UTC
Labels: bug, help wanted
