### ISSUE TITLE
Popups on PRs hidden behind content

### ISSUE THREAD

**Issue by mpaw** [sindresorhus/refined-github#2409] opened 2019-09-06 15:45 UTC
All popup windows inside of PRs (Reviewers, Assignees, Labels, etc...) get hidden behind the content in the main area. Have confirmed issue does not happen when Refined Github is disabled. This also only happens on Github Enterprise, does not happen on github.com

![image](https://user-images.githubusercontent.com/5834637/64441440-e317b200-d09b-11e9-9d9f-03cf22346afa.png)

Also, in case it is relevant, we are running `GitHub Enterprise Server 2.17.5`

**Comment by philmcardle** [comment] 2019-09-18 07:19
If it helps, also seeing this on `GitHub Enterprise 2.15.3`, with refined-github `19.9.17`

Tried disabling a number of individual features today in hopes of narrowing it down, but haven't had any luck.

Please let me know if there's anything I can do to help find the cause of or fix for this 🙂

**Comment by fregante** [comment] 2019-09-18 09:19
I don't use Enterprise so it's hard to see what's wrong. Perhaps it's `sticky-discussion-sidebar` but this issue can only be fixed if a GHE user sends a PR.

**Comment by philmcardle** [comment] 2019-09-18 09:29
Oh, it is `sticky-discussion-sidebar` 🙂

**Comment by busches** [comment] 2019-09-18 19:48
If you send a PR I can test it in GH and GHE, otherwise it'll be a few
weeks before I can look at it.

**Comment by Jarvvski** [comment] 2019-09-25 08:21
I can have a look at this after work today :)

**Comment by kamranayub** [comment] 2019-09-25 14:29
Hi, maybe this helps! It looks like `.discussion-sidebar` is missing `position: relative` for `z-index` to take effect. Once I add that, z-index is working:

![image](https://user-images.githubusercontent.com/563819/65610441-f6b98880-df76-11e9-9c51-d04efe73ca0d.png)

**Comment by jvtrigueros** [comment] 2019-09-27 18:22
I've confirmed that @kamranayub solution does fix it. As a workaround, you can add this as Custom CSS in the add-on preferences:
```css
.discussion-sidebar {
  position: relative;
}
```

**Comment by mpaw** [comment] 2019-09-27 18:50
Can confirm that adding @jvtrigueros's CSS to the plugin resolves the issue for me.

**Comment by mpaw** [comment] 2019-09-27 18:54
Can confirm that adding @jvtrigueros's CSS to the plugin custom CSS resolves the issue.

**Comment by fregante** [comment] 2019-09-28 05:51
Does `sticky-discussion-sidebar` work on GHE? Does disabling the feature fix the issue?

`discussion-sidebar` is the old class name (removed in https://github.com/sindresorhus/refined-github/pull/2314)

**Comment by mpaw** [comment] 2019-09-30 20:31
@fregante No, `sticky-discussion-sidebar` does not work on GHE. Can confirm that turning it off also fixes the issue.

**Closed** 2019-10-09 17:38 UTC
Labels: bug, enterprise, has PR, help wanted
