### ISSUE TITLE
Bug: Pull request comment box CSS is hiding upload attachment

### ISSUE THREAD

**Issue by nicknish** [sindresorhus/refined-github#1227] opened 2018-03-28 15:37 UTC
![](https://cl.ly/qV1V/[2369af9605ab0b675139ad93f224701e]_Image%202018-03-28%20at%2010.35.42%20PM.png)

**Comment by shroudedcode** [comment] 2018-03-28 15:39
This is not a bug. The extension removes the button because you can also just use drag and drop. I was not the one making the decision, but I also don't have a problem with it. **Duplicate of #1191.**

**Comment by nicknish** [comment] 2018-03-28 15:41
@shroudedcode Oops, sorry about the dup! Sorry I searched for issues via "attachment" and "image" keywords and those issues didn't come up.

**Closed** 2018-03-28 15:42 UTC
