### ISSUE TITLE
PR Merge Commit Templates

### ISSUE THREAD

**Issue by dstahl-axion** [sindresorhus/refined-github#3039] opened 2020-04-27 20:38 UTC
Any interest in a configurable template (or a sensible default / hard coded one) that would replace the standard "Merge Pull Request #13..." as the title of a merge commit when a PR is merged? I suggest using the title of the PR and maybe the body of the PR opening as the commit message as a start.

I apologize if this is somehow present in GitHub or Refined GitHub and I've missed it. I see templates for opening issues and PRs but not much for merging / closing out.

**Comment by fregante** [comment] 2020-04-27 20:58
Duplicate of https://github.com/sindresorhus/refined-github/issues/2843

**Closed** 2020-05-17 13:56 UTC
Labels: enhancement, under discussion
