### ISSUE TITLE
Wait for checks when merging a PR when the merging is blocked until checks pass

### ISSUE THREAD

**Issue by latata** [sindresorhus/refined-github#3073] opened 2020-05-08 11:50 UTC
It would be great if the feature that waits for the checks when merging worked for PRs for which merging is blocked when PR checks did not pass.
For example in our project we have merging to master branch blocked until the required checks pass.

**Comment by fregante** [comment] 2020-05-08 14:04
Duplicate of #1325

**Closed by fregante** 2020-05-08 14:04 UTC
Labels: enhancement, under discussion
