### ISSUE TITLE
Feature request: Add source branch names to PRs list

### ISSUE THREAD

**Issue by ahmetb** [sindresorhus/refined-github#1589] opened 2018-10-17 03:25 UTC
Take https://github.com/sindresorhus/refined-github/pulls for example.

It would be great to indicate which `user:branch` each PR was from in the PRs list without clicking to the PR to see this information. Something like this can go next to the date or something. Thoughts?

**Comment by yakov116** [comment] 2018-10-17 03:30
@ahmetb seems like a duplicate of #103

**Closed** 2018-10-17 03:37 UTC
