### ISSUE TITLE
Fold package managers lock files

### ISSUE THREAD

**Issue by ofirnk** [sindresorhus/refined-github#3523] opened 2020-09-01 14:30 UTC
Many (me included) never review the diff itself:

![image](https://user-images.githubusercontent.com/8449713/91863870-3e14c280-ec78-11ea-8a1a-1530427feb02.png)
Folding it by default will only take this space:
![image](https://user-images.githubusercontent.com/8449713/91864104-87651200-ec78-11ea-999f-d4a2e6f9d7e5.png)

For example:
https://github.com/sindresorhus/refined-github/commit/6aac0b113c0a8ee51ba5c93e956ad365cd47b5cf

Among these files are
package-lock.json (js)
Pipfile.lock (python)

**Comment by fregante** [comment] 2020-09-01 19:23
Almost a duplicate of https://github.com/sindresorhus/refined-github/pull/1085

Perhaps collapsing a limited number of hardcoded lockfiles would be useful and relatively easy to implement though

**Comment by fregante** [comment] 2020-09-09 00:33
I remember we had an identical issue to this and we resolved it with:

GitHub’s existing solution is good enough:
- files are already collapsed
- they still take a little bit of visual space not to miss them completely.

If you want to have them take even less space, this is doable with CSS

**Closed by fregante** 2020-09-09 00:33 UTC
Labels: enhancement, under discussion
