### ISSUE TITLE
The more dropdown opens automatically and won't disappear on a global click

### ISSUE THREAD

**Issue by kreempuff** [sindresorhus/refined-github#2367] opened 2019-08-21 15:04 UTC
![screencast 2019-08-21 10-59-56](https://user-images.githubusercontent.com/10726831/63443787-6d58e880-c403-11e9-891e-c1529ebd3a5d.gif)

**Comment by kidonng** [comment] 2019-08-21 15:05
Duplicate of #2357

**Closed** 2019-08-21 15:07 UTC
Labels: bug
