### ISSUE TITLE
Automatically merge PR when Merge Conditions pass

### ISSUE THREAD

**Issue by pere-omnidrone** [sindresorhus/refined-github#3683] opened 2020-10-23 10:05 UTC
Refined-Github already supports merging a PR when tests pass successfully if the merge button is enabled.
https://user-images.githubusercontent.com/1402241/35192861-3f4a1bf6-fecc-11e7-8b9f-35ee019c6cdf.gif

It does however not provide this functionality when the button is disabled via 
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/defining-the-mergeability-of-pull-requests

It would be great to have Refined-Github replace the Blocked button with a new one that allows to "start" the merge and wait until the conditions allow it to be merged

This feature would be available at
https://github.com/{user}/{repo}/pull/{pull-id}

**Comment by fregante** [comment] 2020-10-23 10:40
Duplicate of #3038

**Closed by fregante** 2020-10-23 10:40 UTC
Labels: enhancement, under discussion
