### ISSUE TITLE
It overrides GitHub built-in "Tab size preference"

### ISSUE THREAD

**Issue by g-plane** [sindresorhus/refined-github#4832] opened 2021-09-30 03:25 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

If enabled this extension, it will override GitHub built-in "Tab size preference".

### Screenshot

I use 3 spaces as tab size when rendering tabs and it's set in "Tab size preference" of GitHub "Appearance" settings.

When disabled this extension:

![图片](https://user-images.githubusercontent.com/17216317/135381949-ff5d6c57-302b-447d-bcba-0c776643a4e3.png)

When enabled this extension:

![图片](https://user-images.githubusercontent.com/17216317/135382035-528e4932-1ad0-4bc9-8dee-7a3c172611d5.png)

### Example URL

https://github.com/sindresorhus/refined-github/blob/main/.xo-config.json

### Browser(s) used

Firefox

**Comment by kidonng** [comment] 2021-09-30 04:13
Duplicate of #4806

**Comment by fregante** [comment] 2021-09-30 06:58
Thanks for the report @g-plane, I just sent a PR

**Closed by fregante** 2021-09-30 06:58 UTC
Labels: bug
