### ISSUE TITLE
Consider release it on Firefox

### ISSUE THREAD

**Issue by charlesmilette** [sindresorhus/refined-github#243] opened 2016-06-07 18:32 UTC
Currently, with [Chrome Store Foxified](https://addons.mozilla.org/fr/firefox/addon/chrome-store-foxified/), I can install this addon in Firefox Nightly and it is working okay for now.

WebExtensions will land on Firefox stable on August 2.

A guide on how to do so is available [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_from_Google_Chrome)

**Comment by sindresorhus** [comment] 2016-06-07 18:33
Duplicate of https://github.com/sindresorhus/refined-github/issues/71.

When Firefox 48 is released we'll look into it.

**Closed by sindresorhus** 2016-06-07 18:33 UTC

**Comment by bfred-it** [comment] 2017-07-04 10:45
It's been released!

### [Refined GitHub for Firefox](https://addons.mozilla.org/en-us/firefox/addon/refined-github-/) 🎉
