### ISSUE TITLE
Browse activity dashboard is missing almost all entires on Google Chrome

### ISSUE THREAD

**Issue by vanniktech** [sindresorhus/refined-github#1063] opened 2018-02-04 11:19 UTC
**With the plugin:**

<img width="676" alt="screen shot 2018-02-04 at 12 16 45" src="https://user-images.githubusercontent.com/5759366/35776905-4c872244-09a5-11e8-8ace-91270a7bd5ee.png">

**Without the plugin:**

<img width="664" alt="screen shot 2018-02-04 at 12 17 44" src="https://user-images.githubusercontent.com/5759366/35776926-897abf26-09a5-11e8-82bf-9d4d4ab6ecfb.png">

**Comment by jgierer12** [comment] 2018-02-04 12:06
This is intended. Duplicate of #561, #747, #822

**Closed by jgierer12** 2018-02-04 12:06 UTC

**Comment by vanniktech** [comment] 2018-02-04 22:18
Even after putting `hide-useless-newsfeed-events` in I don't see when for instane someone is forking a repository? Is there still another option that I'm missing?

**Comment by bfred-it** [comment] 2018-02-23 15:59
@vanniktech can you see what CSS rule is hiding those fork events?

**Comment by vanniktech** [comment] 2018-02-24 17:10
I can see 'em now again. I've got the following extra features disabled:

```
hide-useless-newsfeed-events
sort-issues-by-update-time
hide-own-stars
monospace-textareas
```

So it's all good. I recently added `hide-own-stars` so maybe that one was causing this - but I'm not sure.
