### ISSUE TITLE
Condensed Activity Page is not Userstyle Friendly

### ISSUE THREAD

**Issue by briank6932** [sindresorhus/refined-github#2458] opened 2019-09-26 02:48 UTC
This is kind of a feature request and a bug report, so under the readme, in the Newsfeed section the feature called, "🔥 Condenses the events to take up less space and uncollapses "User starred X repos" groups." is highly incompatible with userstyles and lacks a toggle or a way to tweak/remove it without disabling the entire extension.
Without Userstyles:
![image](https://user-images.githubusercontent.com/18603393/65653440-46ce3480-dfe3-11e9-9e84-49753fac238c.png)
With Userstyles:
![image](https://user-images.githubusercontent.com/18603393/65654284-42574b00-dfe6-11e9-960e-22751df7932c.png)
With Refined Github Disabled:
![image](https://user-images.githubusercontent.com/18603393/65654358-81859c00-dfe6-11e9-859f-82684d684e58.png)

**Comment by fregante** [comment] 2019-09-26 11:49
Duplicate of #1899 

Refer to https://github.com/darkreader/darkreader/issues/1195 or use the `CSS` field in Refined GitHub's options to undo that background.

**Closed by fregante** 2019-09-26 11:49 UTC
Labels: bug

**Comment by briank6932** [comment] 2019-10-02 07:39
how would I go about fixing this issue through the css field?

**Comment by briank6932** [comment] 2019-11-23 00:48
There's literally no solution in that linked thread @fregante, you closed both threads without giving a proper solution for either.

**Comment by busches** [comment] 2019-11-23 01:26
> There's literally no solution in that linked thread @fregante, you closed both threads without giving a proper solution for either.

Both mention finding the CSS Refined GitHub is applying and undoing them or modifying them to look the way you want with your other extensions.

**Comment by briank6932** [comment] 2019-11-23 01:52
Closing our threads is implying that the issue has been solved, yet the issue is not even being addressed. It's pretty obvious that there was another thread made, This needs to be addressed by adding an option to enable/disable these broken CSS fields, restating the same thing over and over again is going absolutely nowhere.
