### ISSUE TITLE
Option to default to hide whitespace changes in PRs

### ISSUE THREAD

**Issue by osdiab** [sindresorhus/refined-github#4548] opened 2021-07-08 18:20 UTC
should happen on all PR's (maybe scoped per repo?); since whitespace consistency is already enforced by my project's linter, i pretty much never care about whitespace changes, would be sweet if i could just default PRs to open with them hiding whitespace changes unless I explicitly wanna see them.

**Comment by yakov116** [comment] 2021-07-08 18:28
Duplicate of #2503

**Closed by yakov116** 2021-07-08 18:28 UTC
Labels: enhancement, under discussion
