### ISSUE TITLE
Not finding projects tab in a newly created repo can be confusing

### ISSUE THREAD

**Issue by sarupbanskota** [sindresorhus/refined-github#596] opened 2017-07-08 20:40 UTC
Created a new private repo and wanted to set up projects on it. Was pretty confusing why my projects tab won't show until I realised `refined-github` was responsible :)

Maybe it would be worth adding a section in the quick setup page that mentions projects aren't visible cuz 0, and supply a new project button ¯\_(ツ)_/¯

**Comment by jgierer12** [comment] 2017-07-09 08:00
Duplicate of #560 
Also, you dropped this: \\ 😉

**Closed by jgierer12** 2017-07-09 08:00 UTC

**Comment by sarupbanskota** [comment] 2017-07-09 11:03
@jgierer12 fixed it, haha

thanks - didn't realize!

**Comment by bfred-it** [comment] 2017-07-09 11:04
@sarupbanskota now your missing a couple of \_ \_

**Comment by sarupbanskota** [comment] 2017-07-09 11:05
man, such a bad day, haha

fixed it!
