### ISSUE TITLE
More dropdown never closes

### ISSUE THREAD

**Issue by jhoward321** [sindresorhus/refined-github#2814] opened 2020-02-19 18:41 UTC
After installing the chrome extension, the more dropdown never closes.

This happens on any repository, including this repo.

This is the same issue as #2373 , and I am running version 20.2.14.922.

![image](https://user-images.githubusercontent.com/5036794/74864361-129e3c00-5315-11ea-9738-769514000713.png)

**Comment by yakov116** [comment] 2020-02-19 18:44
duplicate of #2796

**Comment by jdreesen** [comment] 2020-02-19 18:45
Maybe because 20.2.14.922 is broken? See: #2796

**Comment by jdreesen** [comment] 2020-02-19 18:46
Duplicate of #2806

**Closed** 2020-02-19 18:58 UTC
Labels: bug
