### ISSUE TITLE
Code size for operator mono is very small

### ISSUE THREAD

**Issue by kgrz** [sindresorhus/refined-github#353] opened 2017-02-08 12:26 UTC
Not sure if this is an issue per se, but since there is no way to either disable this font-family feature or to adjust the size, opening one for recommendations. Should there be an optimal per-font-family size added in the overriding stylesheet? (Not at all sure how this can be achieved though)

**Comment by jgierer12** [comment] 2017-05-14 16:26
Duplicate of #242

**Closed by jgierer12** 2017-05-14 16:26 UTC
Labels: duplicate
