### ISSUE TITLE
Top menu bar disappears

### ISSUE THREAD

**Issue by slmingol** [sindresorhus/refined-github#4171] opened 2021-03-29 22:21 UTC
1. https://github.com/sindresorhus/refined-github
2. With the extension disabled I see that menu bar, when I enable it it disappears.

### Disabled extension
![image](https://user-images.githubusercontent.com/15072/112907128-56887680-90bb-11eb-89e7-5b83d52aed2c.png)

### Enabled extension
![image](https://user-images.githubusercontent.com/15072/112907394-c3037580-90bb-11eb-9370-fd69ae31c395.png)

3. Errors
```
[Deprecation] ::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.
2hooks-frames-web.js:1 SingleFile is hooking the IntersectionObserver API to detect and load deferred images.
y @ hooks-frames-web.js:1
refined-github.js:1884 ❌ Refined GitHub → more-dropdown → TypeError: Cannot read property 'parentElement' of undefined
    at onlyShowInDropdown (refined-github.js:3654)
    at init (refined-github.js:3671)
    at async runFeature (refined-github.js:1902)
    at async setupPageLoad (refined-github.js:1915) 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Cannot%20read%20property%20'parentElement'%20of%20undefined

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60more-dropdown%60%3A%20Cannot%20read%20property%20'parentElement'%20of%20undefined
		
logError @ refined-github.js:1884
refined-github.js:1884 ℹ️ Refined GitHub → latest-tag-button → Personal token required for this feature
refined-github.js:1884 ℹ️ Refined GitHub → repo-age → Personal token required for this feature
refined-github.js:1884 ℹ️ Refined GitHub → bugs-tab → Personal token required for this feature
content.js:1 Uncaught (in promise) Error: Unexpected token u in JSON at position 0
    at A (content.js:1)
refined-github.js:1884 ❌ Refined GitHub → releases-tab → TypeError: Cannot read property 'append' of undefined
    at init (refined-github.js:3835)
    at async runFeature (refined-github.js:1902)
    at async setupPageLoad (refined-github.js:1915) 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Cannot%20read%20property%20'append'%20of%20undefined

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60releases-tab%60%3A%20Cannot%20read%20property%20'append'%20of%20undefined
		
logError @ refined-github.js:1884
github_jira.js:2 GitHub JIRA Issue Links Rewriter Extension is loaded
api.github.com/repos/sindresorhus/refined-github/contents/hotfix.json:1 Failed to load resource: the server responded with a status of 404 ()
github_jira.js:39 JIRA Issue Base URL:  
refined-github.js:1918 Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at webext_storage_cache.function.maxAge.hours (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:1918:183)
    at async getSet (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:1768:30)
api.github.com/_private/browser/stats:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
page_view:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
api.github.com/_private/browser/stats:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
stats.ts:41 POST https://api.github.com/_private/browser/stats net::ERR_BLOCKED_BY_CLIENT
se @ stats.ts:41
requestIdleCallback (async)
(anonymous) @ stats.ts:23
async function (async)
(anonymous) @ stats.ts:20
ie @ stats.ts:14
(anonymous) @ report-long-tasks.ts:6
DevTools failed to load SourceMap: Could not load content for chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://jcioabgeaepidgkoibflheijdcignhcl/src/vendor/lodash.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by filipewl** [comment] 2021-03-29 22:29
Duplicate of https://github.com/sindresorhus/refined-github/issues/4166. 
Shall we close this one, @slmingol?

**Closed** 2021-03-29 22:59 UTC
Labels: bug
