### ISSUE TITLE
`sticky-sidebar` blocking mouseclick

### ISSUE THREAD

**Issue by Araxeus** [sindresorhus/refined-github#4370] opened 2021-05-18 04:50 UTC
Steps to reproduce:
* ⚠️ Switch to any branch that isn't the default branch
* Collapse code browser or go directly to readme file
* Try and switch to a branch that is on top of the sticky-sidebar

Example:
![sticky-header](https://user-images.githubusercontent.com/78568641/118591486-e63dcd80-b7ac-11eb-8462-3f4dcffaf5db.gif)

I find it weird that this only happen if not currently on the default branch..
anyone have any idea why that would happen?

**Comment by fregante** [comment] 2021-05-18 06:07
Duplicate of https://github.com/sindresorhus/refined-github/issues/4240

**Closed by fregante** 2021-05-18 06:07 UTC
Labels: bug
