### ISSUE TITLE
Latest version mostly not working

### ISSUE THREAD

**Issue by fauxpark** [sindresorhus/refined-github#2055] opened 2019-05-19 15:33 UTC
As of 19.5.19.1032 on Firefox 66.0.5 (macOS and Windows 10), I no longer see the dedicated whitespace toggle button on the "Files changed" tab or any of the related stuff in that area, reaction avatars, removed diff signs... pretty much all of the features seem to be not applying. PR and issue lists are not automatically sorted by Recently updated. The previous version (19.5.18.1919) was working for me.

Disabling/enabling the addon affects my /pulls page, with the tags moving around and the Marketplace link appearing/disappearing, but my username is never in bold:
Disabled:
<img width="719" alt="Screen Shot 2019-05-20 at 1 26 20 am" src="https://user-images.githubusercontent.com/4781841/57984364-7c479c00-7a9e-11e9-88ac-03d62c4d61ca.png">
Enabled:
<img width="720" alt="Screen Shot 2019-05-20 at 1 26 37 am" src="https://user-images.githubusercontent.com/4781841/57984365-7e115f80-7a9e-11e9-9fe4-8d25a9915d11.png">

Here's what the browser console spits out:
<img width="1012" alt="Screen Shot 2019-05-20 at 1 23 16 am" src="https://user-images.githubusercontent.com/4781841/57984334-19560500-7a9e-11e9-85d4-51bb0c2e981d.png">
With it disabled, I only get the CSP warning and the next error line.

**Comment by bfred-it** [comment] 2019-05-19 15:37
Duplicate of #2047 

Are you sure are you on 19.5.19? It should be fixed already and it works on my Firefox

**Closed by bfred-it** 2019-05-19 15:37 UTC
Labels: bug

**Comment by fauxpark** [comment] 2019-05-19 15:40
Yep:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/4781841/57984547-2f64c500-7aa0-11e9-8d31-4bd04ff2d142.png">

**Comment by fauxpark** [comment] 2019-05-19 15:42
I just removed, quit Firefox and installed again and no change.

**Comment by bfred-it** [comment] 2019-05-19 15:43
Verified the bug. That's weird. Anyway there was another open issue about it: https://github.com/sindresorhus/refined-github/issues/2054

**Comment by fauxpark** [comment] 2019-05-19 15:44
Thanks, and sorry for the noise.

**Comment by bfred-it** [comment] 2019-05-19 15:47
For some reason there was a new version pushed with an old tag. I released a new version now.

Thanks for reporting this issue.
