### ISSUE TITLE
Readd the jump-to-bottom` feature

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#1897] opened 2019-03-31 21:02 UTC
I was using this button. You guys removed because think no one is using it:

1. https://github.com/sindresorhus/refined-github/pull/1879

If you do not like the button on the UI, why not add a setting `hide-jump-to-bottom-button`?

**Comment by sindresorhus** [comment] 2019-03-31 21:08
You can just use the keyboard shortcut, as mentioned in https://github.com/sindresorhus/refined-github/issues/892.

**Comment by yakov116** [comment] 2019-03-31 21:10
@sindresorhus 	true but not it was a nice shortcut and it was not _intrusive_

**Comment by evandrocoan** [comment] 2019-03-31 21:11
I am glad to use the keyboard shortcut, if I am with my hands on the keyboard. But most times I am not. Then, I just the `Jump to Bottom`.

**Comment by bfred-it** [comment] 2019-04-03 13:37
Duplicate of https://github.com/sindresorhus/refined-github/issues/892

**Closed by bfred-it** 2019-04-03 13:37 UTC
Labels: enhancement, under discussion
