### ISSUE TITLE
Feature Request: wide formatting

### ISSUE THREAD

**Issue by gdevenyi** [sindresorhus/refined-github#1243] opened 2018-04-05 00:57 UTC
There are a number of wide extensions available for github in working or partially working state.

An active project like this is a good place to add such a feature where breaking changes could be caught quickly and fixed :+1:

**Comment by gdevenyi** [comment] 2018-04-05 00:58
https://chrome.google.com/webstore/detail/wide-github/kaalofacklcidaampbokdplbklpeldpj?hl=fr&gl=FR
https://github.com/mdo/github-wide
https://github.com/xthexder/wide-github
https://github.com/sqren/github-widescreen
https://chrome.google.com/webstore/detail/github-widescreen/elikdceclccjilahimjfceoalhdbndan?hl=en

**Comment by yakov116** [comment] 2018-04-05 01:54
@gdevenyi #1171

**Comment by busches** [comment] 2018-04-05 02:24
Closing as a duplicate of #1171 and #1172.

**Closed by busches** 2018-04-05 02:24 UTC

**Comment by gdevenyi** [comment] 2018-04-05 13:39
Oh man come on, the word "wide" isn't anywhere. I promise I searched.
