### ISSUE TITLE
Show pull requests to source repo on fork's branch list

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2914] opened 2020-03-21 12:41 UTC
When some branch on the repo is a head of PR made to that repo, the PR is shown near the branch on branch list:
![image](https://user-images.githubusercontent.com/6032823/77226511-3f927880-6b79-11ea-9900-ef05023ceb9b.png)

I think it would be great if branch list on forks also included the PRs that are made to their source repo so that user could figure out easily which branches can be removed.

Example URL:
https://github.com/jack1142/Red-DiscordBot/branches/all

**Comment by fregante** [comment] 2020-03-28 15:15
This makes sense and indeed the existing Compare buttons _do_ point to a page that links to the open PR already:

<img width="996" alt="compare" src="https://user-images.githubusercontent.com/1402241/77826342-16d92880-710f-11ea-9e09-bba2ffc9a5d9.png">

It's just that for whatever reason GitHub doesn't show this information directly on the list.

Does this information appear in the GraphQL API?

**Comment by fregante** [comment] 2020-03-28 15:27
Here:

```gql
query { 
  repository(owner: "Cog-Creators", name: "Red-DiscordBot") {
    refs(refPrefix: "refs/heads/", first: 100) {
      nodes {
        name
        associatedPullRequests(first: 100, states: OPEN) {
          nodes {
            number
            url
          }
        }
      }
    }
  }
}
```

```json
{
  "data": {
    "repository": {
      "refs": {
        "nodes": [
          {
            "name": "V3/develop",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 42,
                  "url": "https://github.com/ItzSamYeet/Red-DiscordBot/pull/42"
                }
              ]
            }
          },
          {
            "name": "V3/feature/audio",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3459,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3459"
                }
              ]
            }
          },
          {
            "name": "V3/feature/filter-api",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "V3/feature/mutes",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "V3/sqlite_driver",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 2158,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/2158"
                }
              ]
            }
          },
          {
            "name": "develop",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3,
                  "url": "https://github.com/IODisrupt/OmegaBot/pull/3"
                },
                {
                  "number": 3,
                  "url": "https://github.com/Ryne9/Red-DiscordBot-Thunderdogeedit/pull/3"
                }
              ]
            }
          },
          {
            "name": "kowlin/pr/secuity",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3126,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3126"
                }
              ]
            }
          },
          {
            "name": "l10n_V3/develop",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "master",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "v2-duplicate-cmds",
            "associatedPullRequests": {
              "nodes": []
            }
          }
        ]
      }
    }
  }
}
```

**Comment by jack1142** [comment] 2020-03-28 15:29
Looks like it does include them:
```graphql
query { 
  repository(owner: "jack1142", name: "Red-DiscordBot") {
    refs(refPrefix: "refs/heads/", first: 100) {
      nodes {
        name
        associatedPullRequests(first: 100, states: OPEN) {
          nodes {
            number
            url
          }
        }
      }
    }
  }
}
```
```json
{
  "data": {
    "repository": {
      "refs": {
        "nodes": [
          {
            "name": "V3/alias_non_existent_command",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "V3/allow_any_valid_locale",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3676,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3676"
                }
              ]
            }
          },
          {
            "name": "V3/bring_back_role_mention_sanitizer",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3625,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3625"
                }
              ]
            }
          },
          {
            "name": "V3/changelog_pr_labeler",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "V3/changelog_3.3.3",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3660,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3660"
                }
              ]
            }
          },
          {
            "name": "V3/develop",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "V3/feature/audio",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "V3/issue_2527",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "V3/issue_3200",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3200,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3200"
                }
              ]
            }
          },
          {
            "name": "V3/issue_3605",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3679,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3679"
                }
              ]
            }
          },
          {
            "name": "V3/regional_formatting",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3677,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3677"
                }
              ]
            }
          },
          {
            "name": "V3/restore_command",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3681,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3681"
                }
              ]
            }
          },
          {
            "name": "V3/some_fun_with_async_initialize",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "develop",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "jack1142-patch-1",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3649,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3649"
                }
              ]
            }
          },
          {
            "name": "jack1142-patch-2",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "jack1142-patch-5",
            "associatedPullRequests": {
              "nodes": []
            }
          },
          {
            "name": "jack1142-patch-6",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3672,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3672"
                }
              ]
            }
          },
          {
            "name": "patch-3",
            "associatedPullRequests": {
              "nodes": [
                {
                  "number": 3215,
                  "url": "https://github.com/Cog-Creators/Red-DiscordBot/pull/3215"
                }
              ]
            }
          },
          {
            "name": "pr/ghactions",
            "associatedPullRequests": {
              "nodes": []
            }
          }
        ]
      }
    }
  }
}
```

**Comment by fregante** [comment] 2020-03-28 15:35
Alternatively we can go the opposite way, like for #2934, and only query the source repo. This wouldn't support oneFork-to-manyForks PRs but that's pretty rare, I'd say.

The results are shorter and to the point though:

```gql
{
  search(
    first: 100,
    type: ISSUE,
    query: "repo:Cog-Creators/Red-DiscordBot is:pr is:open author:jack1142"
	) {
    nodes {
      ... on PullRequest {
        number
        headRefName
      }
    }
  }
}
```

```json
{
  "data": {
    "search": {
      "nodes": [
        {
          "number": 3681,
          "headRefName": "V3/restore_command"
        },
        {
          "number": 3679,
          "headRefName": "V3/issue_3605"
        },
        {
          "number": 3677,
          "headRefName": "V3/regional_formatting"
        },
        {
          "number": 3676,
          "headRefName": "V3/allow_any_valid_locale"
        },
        {
          "number": 3672,
          "headRefName": "jack1142-patch-6"
        },
        {
          "number": 3660,
          "headRefName": "V3/changelog_3.3.3"
        },
        {
          "number": 3649,
          "headRefName": "jack1142-patch-1"
        },
        {
          "number": 3625,
          "headRefName": "V3/bring_back_role_mention_sanitizer"
        },
        {
          "number": 3215,
          "headRefName": "patch-3"
        },
        {
          "number": 3200,
          "headRefName": "V3/issue_3200"
        }
      ]
    }
  }
}
```

**Comment by jack1142** [comment] 2020-03-28 15:44
Actually one thing I just noticed with both, I think it would be better to do it like GH does and show all PRs, not just open ones.

**Comment by fregante** [comment] 2020-04-08 00:52
Why all PRs? The point here is to highlight forks that you can/cannot delete

**Comment by jack1142** [comment] 2020-04-08 22:53
> The point here is to highlight forks that you can/cannot delete

It's definitely not the point for me, I thought that for the case you're mentioning, there's already this feature:
![image](https://user-images.githubusercontent.com/6032823/78818999-d1054580-79d5-11ea-97d9-8d74bede8ca1.png)

> Why all PRs?

I can think of few reasons:
a) GitHub shows associated PR on branch list no matter if it's closed, merged or open so I think it would be good if this feature were consistent with original behavior.
b) not all branches are associated to a PR therefore you can't differentiate easily between branches that are part of closed or merged PR and branches that never had their PR
c) seeing associated PR can serve as a better summary of the work done in the branch - at the very least you can see the title of PR when you hover on its number in branch list and that view also shows small part of description and PR's labels
![image](https://user-images.githubusercontent.com/6032823/78840722-d7a6b380-79fb-11ea-9364-49eb2be9db6f.png)
That info can be useful even if the PR has already been merged or closed.
d) if PR was just closed instead of getting merged, it's important to know that removing the branch can cause you losing your work. I'm sure there are plenty of cases when PR doesn't end up being merged

**Comment by fregante** [comment] 2020-04-08 23:05
> It's definitely not the point for me, I thought that for the case you're mentioning, there's already this feature:

D'oh, I thought we were talking about _that_ feature. Sorry!

**Comment by fregante** [comment] 2020-04-08 23:22
This could work:

```gql
{ 
  repository(owner: "jack1142", name: "Red-DiscordBot") {
    refs(refPrefix: "refs/heads/", last: 100) {
      nodes {
        name
        associatedPullRequests(last: 1, states: [CLOSED, OPEN]) {
          nodes {
            number
            url
          }
        }
      }
    }
  }
}
```

Ideally you'd query each of the visible branches instead but the query I tried didn't include closed PRs (I tried via `repository.ref().associatedPullRequests()` and `repository().object().associatedPullRequests()`)

**Comment by yakov116** [comment] 2020-04-17 14:13
> Ideally you'd query each of the visible branches instead but the query I tried didn't include closed PRs (I tried via `repository.ref().associatedPullRequests()` and `repository().object().associatedPullRequests()`)

Can you explain what you had in mind with this comment?

Also why are you limiting it to only closed and open states?

**Comment by fregante** [comment] 2020-04-17 22:06
My last example just asks GitHub for the last 100 branches and their related PR. _Ideally_ instead you'd ask GitHub just for the PRs that are currently on screen, like

```gql
{
	repository(...) {
		branchA: ref('branchA') {
			associatedPullRequests(...) {
				...
			}
		}
		branchB: ref('branchB') {
			associatedPullRequests(...) {
				...
			}
		}
		...
	}
}
```

But none of the queries I tried included closed/merged PRs; they only returned open PRs. If anyone finds a way to query branches this way AND their related PR (even if closed) it's preferable instead of [my last example.](https://github.com/sindresorhus/refined-github/issues/2914#issuecomment-611243565)

**Comment by fregante** [comment] 2020-04-17 22:06
> Also why are you limiting it to only closed and open states?

Mistake. I meant opened/closed/merged.

**Comment by yakov116** [comment] 2020-04-19 14:03
@fregante 

```graphql
{
  repository(owner: "yakov116", name: "refined-github") {
    console_errors: ref(qualifiedName: "console_errors") {
      associatedPullRequests(last: 1) {
        nodes {
          state
        }
      }
    }
  }
}
```

```yaml
{
  "data": {
    "repository": {
      "console_errors": {
        "associatedPullRequests": {
          "nodes": [
            {
              "state": "CLOSED"
            }
          ]
        }
      }
    }
  }
}
```

Unless you had something else in mind.

I would much rather do the last 100 PR's since any search will require a new request.
i also think its safe to say that *most* people with a fork have less than 100 branches

**Comment by jack1142** [comment] 2020-04-20 00:47
In that case, isn't it simpler to just do it like here?
https://github.com/sindresorhus/refined-github/issues/2914#issuecomment-611243565

**Comment by yakov116** [comment] 2020-04-20 01:33
> In that case, isn't it simpler to just do it like here?
> [#2914 (comment)](https://github.com/sindresorhus/refined-github/issues/2914#issuecomment-611243565)

I learned the hard way; when @fregante says something follow it, have questions... ask later.

**Comment by fregante** [comment] 2020-04-20 11:54
> In that case, isn't it simpler to just do it like here?

That works, but if the alternative option is possible the result is safer and lighter. If it’s not possible, then sure.

**Comment by fregante** [comment] 2020-04-20 11:55
> I would much rather do the last 100 PR's since any search will require a new request.
i also think its safe to say that most people with a fork have less than 100 branches

Maybe you’re right

**Comment by yakov116** [comment] 2020-04-20 12:09
Confirmed plan b?

**Comment by yakov116** [comment] 2020-04-20 12:10
Confirmed plan b?

**Comment by yakov116** [comment] 2020-04-20 13:44
@fregante I want to do this should I wait until after #3020 and #3006?

**Closed** 2020-05-25 10:16 UTC
Labels: enhancement, help wanted
